### PR TITLE
[READY] Workaround for pytest-dev/pytest-rerunfailures#51

### PR DESCRIPTION
**Pull request by bstaletic**
References:

- https://github.com/pytest-dev/pytest-rerunfailures/issues/51
- https://github.com/pytest-dev/pytest-rerunfailures/issues/56
- https://github.com/pytest-dev/pytest-rerunfailures/issues/126
- https://github.com/box/flaky/issues/128
- https://github.com/box/flaky/issues/128#issuecomment-429855713

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1485)

### CODE REVIEW

**Review by puremourning — APPROVED** [review]
:lgtm:

thanks.

> Reviewed 87 of 87 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1485#-:-MJR7m6j5NZLsQ5xQ3Ww:b-i7on70)* status: 1 of 2 LGTMs obtained

**Comment by bstaletic** [comment]
:lgtm:

**Comment by bstaletic** [comment]
:lgtm_strong:

**Review by puremourning — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1485#-:-MJRSSHW0hC9rd8pEpRT:b-uwkowd)* status: :shipit: complete! 2 of 2 LGTMs obtained

**Pull request merged**
