### PR TITLE
[READY] Rust analyzer code action fixes

### PR DESCRIPTION
**Pull request by bstaletic**
New rust-analyzer, with the following changes:

1. For the past month and some change, rust-analzer takes advantage of `completionItem/resolve` requests, but does not advertise that server capability.
1.1. Link: https://github.com/rust-lang/rust-analyzer/pull/18167#issuecomment-2512868176
3. Sometimes it produces unresolved code action and sometimes it produces a code action literal. Then, if dealing with a code action literal, it errors on `codeAction/resolve` request.
2.1. Link: https://github.com/rust-lang/rust-analyzer/issues/18428
2.2. This is what the added test exercises.
5. Diagnostics are getting more erratic on startup, so I had to modify the message poll test.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1771)

### CODE REVIEW

**Comment by bstaletic** [comment]
Let's wait on https://github.com/rust-lang/rust-analyzer/pull/18589 so we don't have to introduce new hacks.

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 5 of 7 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1771#-:-ODzFap-9nGSZ8b0HIHR:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[`ycmd/tests/rust/get_completions_proc_macro_test.py` line 75 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1771#-ODwaIRGCAvebHTFiIbD:-ODwaIRGCAvebHTFiIbE:b-skcy3f) ([raw file](https://github.com/ycm-core/ycmd/blob/06c50d5fd3489a1cc5d73fc2d8d8522a0b04f367/ycmd/tests/rust/get_completions_proc_macro_test.py#L75)):*
> ```Python
>     for candidate in results:
>       if candidate[ 'insertion_text' ] == 'checkpoint':
>         checked_candidate = candidate
> ```

break?

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1771)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)

___
*[`ycmd/tests/rust/get_completions_proc_macro_test.py` line 75 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1771#-ODwaIRGCAvebHTFiIbD:-ODzHdH61dLITDD-gFlU:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/06c50d5fd3489a1cc5d73fc2d8d8522a0b04f367/ycmd/tests/rust/get_completions_proc_macro_test.py#L75)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

break?
</blockquote></details>

Done.

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1771#-:-ODzOOme3xcNKHbDgy9N:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Pull request merged**
