### PR TITLE
Fixes submodule cwd in build.py

### PR DESCRIPTION
**Pull request by AP2008**
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1562)

### CODE REVIEW

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1562)* status: 0 of 2 LGTMs obtained (waiting on @AP2008)

___
*[build.py, line 35 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1562#-MYnYN4X-iWhlko5XzgF:-MYnYN4X-iWhlko5XzgG:brcq0td) ([raw file](https://github.com/ycm-core/ycmd/blob/239378234e4b3ea605308d40d2e88eba397fc2db/build.py#L35)):*
> ```Python
> DIR_OF_THIRD_PARTY = p.join( DIR_OF_THIS_SCRIPT, 'third_party' )
> LIBCLANG_DIR = p.join( DIR_OF_THIRD_PARTY, 'clang', 'lib' )
> CUR_DIR = p.abspath( os.curdir )
> ```

rather than this, what we normally do is something inline like:

```python
wd = os.getcwd()
try:
   os.chdir( path_i_need_to_be_in )
   # do stuff
finally:
  os.chdir( wd )
```

**Comment by AP2008** [comment]
@puremourning Updated

**Comment by AP2008** [comment]
@puremourning Updated

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1562)* status: 0 of 2 LGTMs obtained (waiting on @AP2008)

___
*[build.py, line 35 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1562#-MYnYN4X-iWhlko5XzgF:-MYnbwsf94fXkgfilxeC:bw6rpdq) ([raw file](https://github.com/ycm-core/ycmd/blob/239378234e4b3ea605308d40d2e88eba397fc2db/build.py#L35)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

rather than this, what we normally do is something inline like:

```python
wd = os.getcwd()
try:
   os.chdir( path_i_need_to_be_in )
   # do stuff
finally:
  os.chdir( wd )
```
</blockquote></details>

I think you missed my point. don't save the global curdir in a global variable, use the one that happens to be current when the function is called. That's what the code I posted does.

don't use `os.curdir`, use `os.getcwd()`

**Review by puremourning — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1562)* status: 0 of 2 LGTMs obtained (waiting on @AP2008)

**Review by puremourning — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1562)* status: 0 of 2 LGTMs obtained (waiting on @AP2008)

___
*[build.py, line 78 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1562#-MYngvvxCvffXJd-BXIH:-MYngvvxCvffXJd-BXII:bnuls0m) ([raw file](https://github.com/ycm-core/ycmd/blob/8d1e53d299910d28fc8a61726040256e9703b3be/build.py#L78)):*
> ```Python
>   abs_folder_path = p.join( DIR_OF_THIRD_PARTY, folder )
>   if p.isdir( abs_folder_path ) and not os.listdir( abs_folder_path ):
>     print( "Updating submodules:" )
> ```

don't use `print` here. Instead, add the `status_message` argument to `CheckCall` so that `--quiet` mode looks sane.

Did you test --quiet mode ?

**Comment by AP2008** [comment]
@puremourning There's a slight problem here. The args are being parsed later in the `Main` function. How do I know if --quiet was passed ?

**Comment by AP2008** [comment]
@puremourning I fixed it and now the --print option works.

**Comment by AP2008** [comment]
@puremourning Why does the CodeCov fail ?

**Review by puremourning — APPROVED** [review]
no idea. that's standard practice for Codecov.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1562#-:-MYolpC23ZCxt2l6t-bi:b-l2gdd8)* status: 1 of 2 LGTMs obtained (waiting on @AP2008)

**Review by puremourning — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1562#-:-MYsYNUJC2rD-a-mUYFa:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @AP2008)

**Review by bstaletic — APPROVED** [review]
Generally looks good. Here's one concern with doing `git submodule update` in general:

1. If we contain it to `ycmd` directory, it won't take care of YCM's submodules. So are we actually helping users in this case?
2. It might be interfering with testing submodule updates. Currently that can only cause annoyances with regex and watchdog submodules. Right now I can update a submodule, compile, run the tests and then commit. With automatic submodule update, that's not the case.

I'd like @puremourning's thoughts on this.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1562#-:-MZ7QIvw7185PD4pqO2u:b-td21j4)* status: 1 of 2 LGTMs obtained (waiting on @AP2008)

**Comment by puremourning** [comment]
1 is a v good point. Though YCM has few submodules now, it still makes this only partially affective. 

2 - I thought of this too then thought ‘it’s ok because it only does this when dir is empty’. But it occurs to me (as it did then) that this change should _omly_ plapply tonempty subdirs ie do it per directory not ‘everywhere’

**Review by bstaletic — APPROVED** [review]
1 - If we adopt ycm-core/YouCompleteMe#3809, YCM's only submodule is ycmd. Perhaps this check should be moved to YCM's `install.py`?
2 - good point. We can do it for empty dirs only. 

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1562#-:-MZ7fHyhD1LOnq-su6QR:bjvztoo)* status: 1 of 2 LGTMs obtained (waiting on @AP2008)

**Comment by puremourning** [comment]
what's the status of this PR ?

**Comment by AP2008** [comment]
@puremourning Do I have to make any changes ?

**Comment by puremourning** [comment]
I think just fix the conflicts and we can merge it?

**Comment by puremourning** [comment]
Seems abandoned, and I'm concerned about installations that aren't from git.

**Pull request closed without merging**
