### PR TITLE
[READY] Drop the dependency on requests

### PR DESCRIPTION
**Pull request by bstaletic**
Turns out we can ditch requests pretty easily. I've left requests in our test suite, but that can be changed easily as well.

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1507)

### CODE REVIEW

**Review by puremourning — APPROVED** [review]
oh boy. i love it.

keeping requests for tests is fine, as requests is actually a nice lib to use, it's just a pain that it's not in the standard library.

tests are failing though

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1507#-:-MMtgLUE7xAIjlWO9h5_:bxrt028)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

**Review by bstaletic — COMMENTED** [review]
Tests are fixed.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1507#-:-MMuCbfO8-evFVQRavDN:bxdvh1m)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

**Review by bstaletic — COMMENTED** [review]
Finally figured out the intended error handling scheme...

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1507#-:-MMu_ZXuBAMb_sEvuHdg:bpwapnc)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

___
*[ycmd/completers/cs/cs_completer.py, line 854 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1507#-MMu_s0H8FbPaDgP3bYR:-MMu_s0H8FbPaDgP3bYS:buailc6) ([raw file](https://github.com/ycm-core/ycmd/blob/c8620a21aab050c3f4a3a6db448715741ab780b3/ycmd/completers/cs/cs_completer.py#L854)):*
> ```Python
>       response = json.loads( response.read() )
>     except urllib.error.HTTPError as response:
>       response = json.loads( response.fp.read() )
> ```

Maybe call this `response_json`, to pretend we have static typing?

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1507#-:-MMyjek70TKrlEJidWf9:bnfp4nl)* status: 1 of 2 LGTMs obtained

**Pull request merged**
