### PR TITLE
[READY] Upgrade C++ dependencies

### PR DESCRIPTION
**Pull request by bstaletic**
- Update to the latest CI images
  - macOS to 10.15 and Ubuntu to 20.04
- Update gmock to 1.10.0
  - Previous version was really old and raised a lot of warnings on new compilers.
- Update pybind11 to v2.6.0
  - A lot of bugfixes here, plus it avoids a crash on python 3.9
- Switch to upstream regex submodule
  - Again, warnings. Plus support for Unicode 13.0.0

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1488)

### CODE REVIEW

**Review by bstaletic — COMMENTED** [review]
One thing we should consider is moving the build dir of `mrab-regex` to something like `third_party/regex_build`. The upstream repo currently has no `.gitignore` and building inside the repo makes git think the submodule is in a dirty state.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1488#-:-MKP-qWU1vfWJsEcDpKV:b-r7m8ed)* status: 0 of 2 LGTMs obtained

**Review by puremourning — CHANGES_REQUESTED** [review]
> Reviewed 326 of 326 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1488)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

*[a discussion](https://reviewable.io/reviews/ycm-core/ycmd/1488#-MKP7j5W9YhMcro_Kn33:-MKP7j5W9YhMcro_Kn34:byzsh2f) (no related file):*
> One thing we should consider is moving the build dir of mrab-regex to something like third_party/regex_build. The upstream repo currently has no .gitignore and building inside the repo makes git think the submodule is in a dirty state.

We could even use the same dir temp area we use   for building ycmd (--build-dir) and just copy the artefacts to third_party/regex-lib. this would reduce the overall installation size further (which I think we have to have as a goal)

---
*[a discussion](https://reviewable.io/reviews/ycm-core/ycmd/1488#-MKPBJws7rzI4duweZWQ:-MKPBJws7rzI4duweZWR:bfgxbe3) (no related file):*
As discussed on Gitter, I don't love having wholesale copies of gtest and gmock here. Can we find a way to avoid it?
I'm not going to block this PR on it, but it seems like a lot of files that we don't need.

---
___
*[.ycm_extra_conf.py, line 198 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1488#-MKP7FjlBhdDRDFBq5dZ:-MKP7FjlBhdDRDFBq5d_:b-1h989r) ([raw file](https://github.com/ycm-core/ycmd/blob/0accd9fec7f495758d3a00bfe0523a6f30e67967/.ycm_extra_conf.py#L198)):*
> ```Python
>   sys_path[ 0:0 ] = [ p.join( DIR_OF_THIS_SCRIPT ),
>                       p.join( DIR_OF_THIRD_PARTY, 'bottle' ),
>                       p.join( DIR_OF_THIRD_PARTY, 'mrab-regex', 'build' ),
> ```

just a note that there are quite a few places we need to update:

- here
- ycmd itself

- build.py?
- run_tests.py ?
- vimspector config ?

- YCM client ?
___
*[update_unicode.py, line 31 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1488#-MKP9ASL71uFheIiHaPY:-MKP9ASL71uFheIiHaPZ:b-scy30b) ([raw file](https://github.com/ycm-core/ycmd/blob/0accd9fec7f495758d3a00bfe0523a6f30e67967/update_unicode.py#L31)):*
> ```Python
> sys.path[ 0:0 ] = [ p.join( DIR_OF_THIRD_PARTY, 'requests_deps', 'requests' ),
>                     p.join( DIR_OF_THIRD_PARTY, 'mrab-regex', 'build' ),
>                     p.join( DIR_OF_THIRD_PARTY, 'mrab-regex', 'build' ),
> ```

duplicate ?

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1488)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

*[a discussion](https://reviewable.io/reviews/ycm-core/ycmd/1488#-MKPBJws7rzI4duweZWQ:-MKPDA0q7t9R7hSLSDa2:b-uni3c3) (no related file):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

As discussed on Gitter, I don't love having wholesale copies of gtest and gmock here. Can we find a way to avoid it?
I'm not going to block this PR on it, but it seems like a lot of files that we don't need.
</blockquote></details>

And like I said on gitter, we could start using conan. Whatever package manager we choose, we have a complete rewrite of cmake waiting for us.

---
*[a discussion](https://reviewable.io/reviews/ycm-core/ycmd/1488#-MKP7j5W9YhMcro_Kn33:-MKPDYjt1nVceEXM6SSi:b-s6epv6) (no related file):*
> this would reduce the overall installation size further

It won't. There's only two object files that get generated, currently in `mrab-regex/build/3`, which already get removed.

---
___
*[.ycm_extra_conf.py, line 198 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1488#-MKP7FjlBhdDRDFBq5dZ:-MKPCnJt75C4FQVlxJ42:bypsykq) ([raw file](https://github.com/ycm-core/ycmd/blob/0accd9fec7f495758d3a00bfe0523a6f30e67967/.ycm_extra_conf.py#L198)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

just a note that there are quite a few places we need to update:

- here
- ycmd itself

- build.py?
- run_tests.py ?
- vimspector config ?

- YCM client ?
</blockquote></details>

YCM client specifically doesn't need to be updated, as we really don't want to load C module in vim. vimspector config didn't mention this path, so I assume it also doesn't need an update.
___
*[update_unicode.py, line 31 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1488#-MKP9ASL71uFheIiHaPY:-MKPDzwJ1ycQHfGS4A20:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/0accd9fec7f495758d3a00bfe0523a6f30e67967/update_unicode.py#L31)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

duplicate ?
</blockquote></details>

Done.

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1488#-:-MKPJ4s510l3yitnRzpB:bnfp4nl)* status: 1 of 2 LGTMs obtained

**Review by bstaletic — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1488#-:-MKPJYNjAnr7PpIpCAom:bnfp4nl)* status: :shipit: complete! 2 of 2 LGTMs obtained

**Pull request merged**
