### PR TITLE
[READY] Rust-analyzer update 

### PR DESCRIPTION
**Pull request by bstaletic**
First commit upgrades rust toolchain to nightly-2021-04-14, which pulls in rust-analyzer 2021-04-05.
Second commit addresses [this breaking change](https://github.com/rust-analyzer/rust-analyzer/issues/4604#issuecomment-814093062).

Pinging @theli-ua, in case he knows a way to break the second commit.

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1553)

### CODE REVIEW

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1553#-:-MYEOZq05j3-Z8-isb9P:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Comment by bstaletic** [comment]
Okay, this is a problem. The diagnostics have never arrived on macOS and Windows. I've seen this once locally, but couldn't repro.

@puremourning Mind giving it a shot on your mac?

**Comment by puremourning** [comment]
> @puremourning Mind giving it a shot on your mac?

Will try  later.

**Review by bstaletic — COMMENTED** [review]
Finally! Ready for review.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1553#-:-MYKUX09COtS4-OeIB3k:b-bkefrv)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)

**Review by puremourning — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1553)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @bstaletic)

**Review by puremourning — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1553#-:-MYLG1-K4eOPWmIvMhJm:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Comment by bstaletic** [comment]
:lgtm:

**Pull request merged**
