### PR TITLE
Modified build.py to add support for MSYS2

### PR DESCRIPTION
**Pull request by AP2008**
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1556)

### CODE REVIEW

**Review by bstaletic — CHANGES_REQUESTED** [review]
The build is broken. I haven't checked, but it's probably something about `flake8 build.py`.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1556#-:-MYTjwVK3BmQm--FtlQF:byy4000)* status: 0 of 2 LGTMs obtained (waiting on @AP2008)

___
*[build.py, line 23 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1556#-MYTjgRC4tMQvv9vMXiR:-MYTjgRC4tMQvv9vMXiS:brgt8pd) ([raw file](https://github.com/ycm-core/ycmd/blob/db84b70548bb6554125fa044abbd57bb2e0e4d0c/build.py#L23)):*
> ```Python
> 
> try:
>   IS_MSYS = "MSYS" in os.environ["MSYSTEM"]
> ```

How about `IS_MSYS = 'MSYSTEM' in os.environ`?

**Comment by AP2008** [comment]
@bstaletic But, the `MSYSTEM` variable can also have the value of `MINGW`.

**Review by bstaletic — CHANGES_REQUESTED** [review]
Please use reviewable for code reviews. It will keep discussion more organized.

> Why is a space required after and before square brackets ?

It's about `foo[ bar ]` vs `foo[bar]`. The checks are enforcing YCM's style.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1556#-:-MYTmP4f16xGrbbAQtrh:by4u29y)* status: 0 of 2 LGTMs obtained (waiting on @AP2008 and @bstaletic)

___
*[build.py, line 23 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1556#-MYTjgRC4tMQvv9vMXiR:-MYTmh2j6gUxLnmdQpik:b-kyrzwi) ([raw file](https://github.com/ycm-core/ycmd/blob/db84b70548bb6554125fa044abbd57bb2e0e4d0c/build.py#L23)):*
> But, the MSYSTEM variable can also have the value of MINGW.

Okay, then `IS_MSYS = 'MSYS" in os.environ.get( 'MSYSTEM', '' )`? That should work.

**Comment by AP2008** [comment]
@bstaletic Yeah, that is working.

**Review by bstaletic — APPROVED** [review]
Mind also squashing the commits?

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1556#-:-MYTpwwQAYK3ZHGKgPB1:b4l83r3)* status: 0 of 2 LGTMs obtained (waiting on @AP2008)

___
*[build.py, line 23 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1556#-MYTjgRC4tMQvv9vMXiR:-MYTpOLI1vU6rysAMK2I:b-kta7k9) ([raw file](https://github.com/ycm-core/ycmd/blob/db84b70548bb6554125fa044abbd57bb2e0e4d0c/build.py#L23)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

> But, the MSYSTEM variable can also have the value of MINGW.

Okay, then `IS_MSYS = 'MSYS" in os.environ.get( 'MSYSTEM', '' )`? That should work.
</blockquote></details>

Is `'MSYS' in os.environ.get( 'MSYSTEM', '' )` good enough or should we go with `os.environ.get( 'MSYSTEM', '' ).startswith( 'MSYS' )`? I.e. Is there a case where `MSYSTEM` is set to something that:

1. Contains the string `MSYS`.
2. `MSYS` is not at the start.
3. We shouldn't match that environment.

**Comment by AP2008** [comment]
@bstaletic The only values for `MSYSTEM` are: `MSYS`, `MINGW64`, `MINGW32`.

**Review by bstaletic — APPROVED** [review]
Thanks for the PR. :lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1556#-:-MYTwaP6DPGh5FdCEYrJ:b-40q4lk)* status: 1 of 2 LGTMs obtained (waiting on @AP2008)

**Review by puremourning — APPROVED** [review]
Does this also work for the msys non native stuff? Ie with msys gcc and msys vim ?

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1556#-:-MYTxg-zCC7-0HaIA05u:bs88zj6)* status: 1 of 2 LGTMs obtained (waiting on @AP2008)

**Review by puremourning — APPROVED** [review]
Thanks for checking, it doesn't but only because abseil doesn't support Cygwin/msys.


:lgtm: 

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1556#-:-MYUCGbGAZMzRXN4ER05:b5g0qt6)* status: :shipit: complete! 2 of 2 LGTMs obtained (waiting on @AP2008)

___
*[build.py, line 22 at r4](https://reviewable.io/reviews/ycm-core/ycmd/1556#-MYUCQuE7aL9A7rUioPR:-MYUCQuE7aL9A7rUioPS:b-1g0af) ([raw file](https://github.com/ycm-core/ycmd/blob/7b3f7fbdd1350b60def0b5ef90f3241f486d3a93/build.py#L22)):*
> ```Python
> import urllib.request
> 
> IS_MSYS = 'MSYS' == os.environ.get( 'MSYSTEM' )
> ```

just fyi I would prefer `os.environ.get( 'MSYSTEM' ) == 'MSYS'` but no need to change it.

**Review by puremourning — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1556)* status: :shipit: complete! 2 of 2 LGTMs obtained (waiting on @AP2008)

**Pull request merged**
