### PR TITLE
Ubuntu 18.04 clang/gcc

### PR DESCRIPTION
**Pull request by Borwe**
Add support for building ycmd with normal gcc 7.5 or clang-10, as tested and works if on ubuntu 18.04 LTS.... Appears to work on my machine.  :smile:

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1528)

### CODE REVIEW

**Review by bstaletic — CHANGES_REQUESTED** [review]
Interesting...

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1528#-:-MS-E7iG8zHNnvl_g7mj:b-yfxp5x)* status: 0 of 2 LGTMs obtained (waiting on @Borwe)

___
*[cpp/CMakeLists.txt, line 27 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1528#-MS-ENRWE2CHGrsbVzdA:-MS-ENRWE2CHGrsbVzdB:b7iw9tc) ([raw file](https://github.com/ycm-core/ycmd/blob/104586efa52c7cedf11b805cd44cb8ef8cd1ab8a/cpp/CMakeLists.txt#L27)):*
> ```CMake
> 
> if ( CMAKE_CXX_COMPILER_ID STREQUAL Clang)
>     add_compile_options("-stdlib=libc++")
> ```

Won't this be a problem for linux users who compile with clang, but don't have libc++ installed?
___
*[cpp/ycm/CMakeLists.txt, line 301 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1528#-MS-Emr8CLl-TK2OlzDq:-MS-Emr8CLl-TK2OlzDr:b-ceuynp) ([raw file](https://github.com/ycm-core/ycmd/blob/104586efa52c7cedf11b805cd44cb8ef8cd1ab8a/cpp/ycm/CMakeLists.txt#L301)):*
> ```CMake
>              SOURCES ${CMAKE_CURRENT_BINARY_DIR}/main.cpp
> 	     CXX_STANDARD 17
>          COMPILE_DEFINITIONS -stdlib=libc++
> ```

This will only work with the libc++ that came with clang >=8.0.0. Libc++ 7.0.0 requires `-lc++fs`. That's why there's this whole dance.

Also, please expand the tabs.
___
*[cpp/ycm/CMakeLists.txt, line 324 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1528#-MS-G1ex8JYNJM-JHHnD:-MS-G1ex8JYNJM-JHHnE:bssib8f) ([raw file](https://github.com/ycm-core/ycmd/blob/104586efa52c7cedf11b805cd44cb8ef8cd1ab8a/cpp/ycm/CMakeLists.txt#L324)):*
> ```CMake
>     if(${STD_OLD_GCC_7_UBUNTU_1804})
>         set(STD_FS_LIB stdc++fs)
>         add_definitions(-DSTD_OLD_GCC_7_UBUNTU_1804)
> ```

Should be `target_compile_definitions`.
___
*[cpp/ycm/IdentifierUtils.cpp, line 191 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1528#-MS-FEOhAczREe-_7nWc:-MS-FEOhAczREe-_7nWd:b-gi4yf) ([raw file](https://github.com/ycm-core/ycmd/blob/104586efa52c7cedf11b805cd44cb8ef8cd1ab8a/cpp/ycm/IdentifierUtils.cpp#L191)):*
> ```cpp
> 
> #ifdef STD_OLD_GCC_7_UBUNTU_1804
>     path = fs::canonical( path_to_tag_file.parent_path() / path );
> ```

`fs::canonical` throws if the path doesn't exist. Long ago @micbou had to rewrite `boost::filesystem::weakly_canonical`, because it was buggy and `boost:filesystem::canonical` throws. You also can't just catch the error and return early, but rather figure out the path.

**Comment by Borwe** [comment]
> `fs::canonical` throws if the path doesn't exist. Long ago @micbou had to rewrite `boost::filesystem::weakly_canonical`, because it was buggy and `boost:filesystem::canonical` throws. You also can't just catch the error and return early, but rather figure out the path.

I didn't know about this, so only other way is bringing back boost?

**Review by bstaletic — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1528)* status: 0 of 2 LGTMs obtained (waiting on @Borwe)

___
*[cpp/ycm/IdentifierUtils.cpp, line 191 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1528#-MS-FEOhAczREe-_7nWc:-MS2w94T0RPirKHW_bgP:b-p1zw3y) ([raw file](https://github.com/ycm-core/ycmd/blob/104586efa52c7cedf11b805cd44cb8ef8cd1ab8a/cpp/ycm/IdentifierUtils.cpp#L191)):*
Please use Reviewable. It's much nicer than github reviews.

> I didn't know about this, so only other way is bringing back boost?

Except `boost::filesystem::weakly_canonical` has been and remains buggy. The only other way is to bring back the reimplementation that was called `YouCompleteMe::NormalizePath`, along with the tests for it.

**Comment by Borwe** [comment]
___
*[cpp/ycm/IdentifierUtils.cpp, line 191 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1528#-MS-FEOhAczREe-_7nWc:-MS8ra8U26Yt6HQVl61t:btljeg8) ([raw file](https://github.com/ycm-core/ycmd/blob/104586efa52c7cedf11b805cd44cb8ef8cd1ab8a/cpp/ycm/IdentifierUtils.cpp#L191)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Please use Reviewable. It's much nicer than github reviews.

> I didn't know about this, so only other way is bringing back boost?

Except `boost::filesystem::weakly_canonical` has been and remains buggy. The only other way is to bring back the reimplementation that was called `YouCompleteMe::NormalizePath`, along with the tests for it.
</blockquote></details>

I think I will let this stay a little on my machine as I gather more info on this boost::filesystem::weak_canonical issue, could you direct me to the last to the YouCompleteMe:NormalizePath implementation?

**Comment by Borwe** [comment]
___
*[cpp/ycm/IdentifierUtils.cpp, line 191 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1528#-MS-FEOhAczREe-_7nWc:-MS8sh5WAzJ-OzmeZCDl:bh7vpof) ([raw file](https://github.com/ycm-core/ycmd/blob/104586efa52c7cedf11b805cd44cb8ef8cd1ab8a/cpp/ycm/IdentifierUtils.cpp#L191)):*
<details><summary><i>Previously, Borwe (Brian Orwe) wrote…</i></summary><blockquote>

I think I will let this stay a little on my machine as I gather more info on this boost::filesystem::weak_canonical issue, could you direct me to the last to the YouCompleteMe:NormalizePath implementation?
</blockquote></details>

You can close after giving me some direction. Might redo later on.

**Comment by bstaletic** [comment]
https://github.com/ycm-core/ycmd/pull/1080

The problems with `boost::filesystem::weakly_canonical`, if I remember correctly, were about paths that have a drive letter, but aren't absolute paths. Yes, this is on Windows and yes, those paths do exist.

**Review by bstaletic — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1528)* status: 0 of 2 LGTMs obtained (waiting on @Borwe, @micbou, and @puremourning)

___
*[cpp/ycm/IdentifierUtils.cpp, line 191 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1528#-MS-FEOhAczREe-_7nWc:-MTS1XmD641Hd7cvAUyg:bf8bdo5) ([raw file](https://github.com/ycm-core/ycmd/blob/104586efa52c7cedf11b805cd44cb8ef8cd1ab8a/cpp/ycm/IdentifierUtils.cpp#L191)):*
<details><summary><i>Previously, Borwe (Brian Orwe) wrote…</i></summary><blockquote>

You can close after giving me some direction. Might redo later on.
</blockquote></details>

Unless @puremourning has anything against it, I'm going to leave this open for a while. Just in case you reconsider.

I know it's not a trivial thing to get to work.

**Comment by Borwe** [comment]
> > _[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1528)_ status: 0 of 2 LGTMs obtained (waiting on @Borwe, @micbou, and @puremourning)
> 
> _[cpp/ycm/IdentifierUtils.cpp, line 191 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1528#-MS-FEOhAczREe-_7nWc:-MTS1XmD641Hd7cvAUyg:bf8bdo5) ([raw file](https://github.com/ycm-core/ycmd/blob/104586efa52c7cedf11b805cd44cb8ef8cd1ab8a/cpp/ycm/IdentifierUtils.cpp#L191)):_
> Previously, Borwe (Brian Orwe) wrote…
> 
> Unless @puremourning has anything against it, I'm going to leave this open for a while. Just in case you reconsider.
> 
> I know it's not a trivial thing to get to work.

LOL! you can actually close, will repost once I get around it.

**Review by Borwe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1528)* status: 0 of 2 LGTMs obtained (waiting on @Borwe, @micbou, and @puremourning)

___
*[cpp/ycm/IdentifierUtils.cpp, line 191 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1528#-MS-FEOhAczREe-_7nWc:-MTuUGDN0gRBxh7pVyJt:b-49bi3c) ([raw file](https://github.com/ycm-core/ycmd/blob/104586efa52c7cedf11b805cd44cb8ef8cd1ab8a/cpp/ycm/IdentifierUtils.cpp#L191)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Unless @puremourning has anything against it, I'm going to leave this open for a while. Just in case you reconsider.

I know it's not a trivial thing to get to work.
</blockquote></details>

Actually you can go ahead and close it, will repost if I get anywhere close. :smile:

**Comment by bstaletic** [comment]
Alright, thanks for trying anyway!

**Pull request closed without merging**
