### PR TITLE
[READY] Execute python tests in separate processes.

### PR DESCRIPTION
**Pull request by inglor**
Tests are grouped by module for test functions and by class for test methods.

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1549)

### CODE REVIEW

**Review by puremourning — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1549)* status: 0 of 2 LGTMs obtained (waiting on @inglor)

___
*[run_tests.py, line 164 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1549#-MXJuT326_2ET2qrcN1P:-MXJuT326_2ET2qrcN1Q:bgmekad) ([raw file](https://github.com/ycm-core/ycmd/blob/230bd298c7aa28fe72780ae45c9a38afb272d6bf/run_tests.py#L164)):*
> ```Python
>                        action = 'store_true',
>                        help = 'Run tests inside valgrind.' )
>   parser.add_argument( '--parallel',
> ```

I think this should be —serial and store_true. Or at least disable-parallel or something.

**Review by puremourning — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1549)* status: 0 of 2 LGTMs obtained (waiting on @inglor)

**Review by puremourning — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1549)* status: 0 of 2 LGTMs obtained (waiting on @inglor)

___
*[cpp/TODO.md, line 1 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1549#-MXMRGDl8w2JQ-r6k6Wj:-MXMRGDm-NDY_1vQPXdn:bj401e4) ([raw file](https://github.com/ycm-core/ycmd/blob/36a6e8438e55dfde294b5436f27ccf6bf9cd1af6/cpp/TODO.md#L1)):*
> ```Markdown
> - Using absl::flat_hash_map
> ```

what's this file?

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1549#-:-MXMS3Qp7WtO2927C4XL:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @inglor)

**Review by inglor — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1549#-:-MXN7VLa3KbVr0gpd-Qc:bnfp4nl)* status: 1 of 2 LGTMs obtained (and 1 stale) (waiting on @inglor)

**Review by inglor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1549)* status: 1 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)

___
*[cpp/TODO.md, line 1 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1549#-MXMRGDl8w2JQ-r6k6Wj:-MXN7YHBA74Y6XbO506e:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/36a6e8438e55dfde294b5436f27ccf6bf9cd1af6/cpp/TODO.md#L1)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

what's this file?
</blockquote></details>

Done.

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1549#-:-MXNCOpj5Ar9De_wjJMP:bnfp4nl)* status: :shipit: complete! 2 of 2 LGTMs obtained (waiting on @inglor)

**Pull request merged**
