### PR TITLE
Fix double `utils.FindExecutable` call

### PR DESCRIPTION
**Pull request by magras**
Double `utils.FindExecutable` call throws an exception if there is no
such executable, which results in the `g:ycm_language_server` option
being ignored in the YCM configuration.

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1565)

### CODE REVIEW

**Comment by bstaletic** [comment]
Thanks for the pull request!

> Double utils.FindExecutable call throws an exception if there is no
such executable

`utils.FindExecutable()` returns `None`. It never throws. So which exception are you seeing?

> which results in the g:ycm_language_server option
being ignored in the YCM configuration.

If `rust_completer.ShouldEnableRustCompleter( use_options )` returns `False`, then [the hook](https://github.com/ycm-core/ycmd/blob/master/ycmd/completers/rust/hook.py#L24) returns `None`. If the hook returns `None`, `server_state.py` checks `language_server` variable.

So please provide more info about the exception you've seen. `ShouldEnableRustCompleter` shouldn't throw any exceptions.

&nbsp;

Either way, you're right that the call second call to `FindExecutable()` is redundant.

**Comment by magras** [comment]
```
  Traceback (most recent call last):
    File "/home/magras/.dotfiles/config/nvim/pack/plugins/start/YouCompleteMe/third_party/ycmd/ycmd/server_state.py", line 106, in FiletypeCompletionAvailable
      self.GetFiletypeCompleter( filetypes )
    File "/home/magras/.dotfiles/config/nvim/pack/plugins/start/YouCompleteMe/third_party/ycmd/ycmd/server_state.py", line 84, in GetFiletypeCompleter
      completers = [ self._GetFiletypeCompleterForFiletype( filetype )
    File "/home/magras/.dotfiles/config/nvim/pack/plugins/start/YouCompleteMe/third_party/ycmd/ycmd/server_state.py", line 84, in <listcomp>
      completers = [ self._GetFiletypeCompleterForFiletype( filetype )
    File "/home/magras/.dotfiles/config/nvim/pack/plugins/start/YouCompleteMe/third_party/ycmd/ycmd/server_state.py", line 66, in _GetFiletypeCompleterForFiletype
      completer = module.GetCompleter( self._user_options )
    File "/home/magras/.dotfiles/config/nvim/pack/plugins/start/YouCompleteMe/third_party/ycmd/ycmd/completers/rust/hook.py", line 23, in GetCompleter
      if not ShouldEnableRustCompleter( user_options ):
    File "/home/magras/.dotfiles/config/nvim/pack/plugins/start/YouCompleteMe/third_party/ycmd/ycmd/completers/rust/rust_completer.py", line 72, in ShouldEnableRustCompleter
      return bool( utils.FindExecutable( RA_EXECUTABLE ) )
    File "/home/magras/.dotfiles/config/nvim/pack/plugins/start/YouCompleteMe/third_party/ycmd/ycmd/utils.py", line 253, in FindExecutable
      if os.path.dirname( executable ):
    File "/usr/lib/python3.9/posixpath.py", line 152, in dirname
      p = os.fspath(p)
  TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Calling `utils.FindExecutable(None)` raises exception in `os.fspath`.

**Comment by magras** [comment]
I might be wrong with calling it exception. I'm sorry if I confused you.

**Comment by bstaletic** [comment]
> Calling utils.FindExecutable(None) raises exception in os.fspath.

Yup, can confirm! Damn dynamically typed languages!  I should really get on with applying type hints to ycmd.

> I might be wrong with calling it an exception. I'm sorry if I confused you.

No, no. You're right, I just wasn't expecting that.

&nbsp;

One test failed, however.

```

    @patch( 'ycmd.completers.rust.rust_completer.RA_EXECUTABLE', 'does_not_exist' )
    def GetCompleter_RANotFound_test( *args ):
>     assert_that( not GetCompleter( user_options_store.GetAll() ) )
E     AssertionError: Assertion failed

ycmd/tests/rust/rust_completer_test.py:32: AssertionError
```

I haven't checked, but I think the test will work if you remove the other call to `FindExecutable()` instead.

**Comment by bstaletic** [comment]
By the way, if you're trying to get ycmd to work with a newer rust-analyzer, there's `g:ycm_rust_toolchain_path`.

**Comment by magras** [comment]
> I haven't checked, but I think the test will work if you remove the other call to FindExecutable() instead.

I figured that I can patch `RA_EXECUTABLE` with `None` instead of string to fix the test. Is it okay, or you prefer changing the types of `RA_EXECUTABLE` and `RUSTC_EXECUTABLE` for consistency?

By the way, as far as I can see `RUSTC_EXECUTABLE` is never used.

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1565)* status: 0 of 2 LGTMs obtained (waiting on @magras)

___
*[ycmd/tests/rust/rust_completer_test.py, line 30 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1565#-MYzrvnx6ksGaB7yhd5o:-MYzrvnx6ksGaB7yhd5p:b-srbfhk) ([raw file](https://github.com/ycm-core/ycmd/blob/595facb0dea5f65e4c86d26e8205606e394af8ab/ycmd/tests/rust/rust_completer_test.py#L30)):*
> ```Python
> 
> 
> @patch( 'ycmd.completers.rust.rust_completer.RA_EXECUTABLE', None )
> ```

just to confirm, does this test fail now without the fix in rust_completer.py?

**Comment by magras** [comment]
> > _[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1565)_ status: 0 of 2 LGTMs obtained (waiting on @magras)
> 
> _[ycmd/tests/rust/rust_completer_test.py, line 30 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1565#-MYzrvnx6ksGaB7yhd5o:-MYzrvnx6ksGaB7yhd5p:b-srbfhk) ([raw file](https://github.com/ycm-core/ycmd/blob/595facb0dea5f65e4c86d26e8205606e394af8ab/ycmd/tests/rust/rust_completer_test.py#L30)):_
> 
> > ```python
> > @patch( 'ycmd.completers.rust.rust_completer.RA_EXECUTABLE', None )
> > ```
> 
> just to confirm, does this test fail now without the fix in rust_completer.py?

Yes, it does:
```
====================================================== FAILURES =======================================================
____________________________________________ GetCompleter_RANotFound_test _____________________________________________
[gw0] linux -- Python 3.9.3 /home/magras/.dotfiles/config/nvim/pack/plugins/start/YouCompleteMe/tests/bin/python3

args = ()

    @patch( 'ycmd.completers.rust.rust_completer.RA_EXECUTABLE', None )
    def GetCompleter_RANotFound_test( *args ):
>     assert_that( not GetCompleter( user_options_store.GetAll() ) )

ycmd/tests/rust/rust_completer_test.py:32:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
ycmd/completers/rust/hook.py:23: in GetCompleter
    if not ShouldEnableRustCompleter( user_options ):
ycmd/completers/rust/rust_completer.py:72: in ShouldEnableRustCompleter
    return bool( utils.FindExecutable( RA_EXECUTABLE ) )
ycmd/utils.py:253: in FindExecutable
    if os.path.dirname( executable ):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

p = None

    def dirname(p):
        """Returns the directory component of a pathname"""
>       p = os.fspath(p)
E       TypeError: expected str, bytes or os.PathLike object, not NoneType

/usr/lib/python3.9/posixpath.py:152: TypeError
```

**Review by puremourning — APPROVED** [review]
:lgtm: thanks.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1565#-:-MYzuBShCdjmbrTA2cl-:brfqlva)* status: 1 of 2 LGTMs obtained (waiting on @magras)

___
*[ycmd/tests/rust/rust_completer_test.py, line 30 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1565#-MYzrvnx6ksGaB7yhd5o:-MYzu1IFBF7yvzoXQw_S:b-6mhywn) ([raw file](https://github.com/ycm-core/ycmd/blob/595facb0dea5f65e4c86d26e8205606e394af8ab/ycmd/tests/rust/rust_completer_test.py#L30)):*
<details><summary><i>Previously, magras wrote…</i></summary><blockquote>

> > ```python
> > @patch( 'ycmd.completers.rust.rust_completer.RA_EXECUTABLE', None )
> > ```
> > 

> 
> just to confirm, does this test fail now without the fix in rust_completer.py?
> 

Yes, it does:
```
====================================================== FAILURES =======================================================
____________________________________________ GetCompleter_RANotFound_test _____________________________________________
[gw0] linux -- Python 3.9.3 /home/magras/.dotfiles/config/nvim/pack/plugins/start/YouCompleteMe/tests/bin/python3

args = ()

    @patch( 'ycmd.completers.rust.rust_completer.RA_EXECUTABLE', None )
    def GetCompleter_RANotFound_test( *args ):


>     assert_that( not GetCompleter( user_options_store.GetAll() ) )
> 

ycmd/tests/rust/rust_completer_test.py:32:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
ycmd/completers/rust/hook.py:23: in GetCompleter
    if not ShouldEnableRustCompleter( user_options ):
ycmd/completers/rust/rust_completer.py:72: in ShouldEnableRustCompleter
    return bool( utils.FindExecutable( RA_EXECUTABLE ) )
ycmd/utils.py:253: in FindExecutable
    if os.path.dirname( executable ):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

p = None

    def dirname(p):
        """Returns the directory component of a pathname"""


>       p = os.fspath(p)
> 

E       TypeError: expected str, bytes or os.PathLike object, not NoneType

/usr/lib/python3.9/posixpath.py:152: TypeError
```

</blockquote></details>

Great, thanks.

**Review by bstaletic — APPROVED** [review]
Go home, codecov!

:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1565#-:-MZ-2mcV52OrpBJSTw0z:b8ix7py)* status: :shipit: complete! 2 of 2 LGTMs obtained (waiting on @magras)

**Comment by bstaletic** [comment]
:lgtm:

**Pull request merged**
