### PR TITLE
[READY] Upgrade to newer Omnisharp

### PR DESCRIPTION
**Pull request by mispencer**
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1610)

### CODE REVIEW

**Comment by puremourning** [comment]
you're... a... magician.

**Review by puremourning — APPROVED** [review]
:lgtm:

Thanks!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1610#-:-MoimTT5AelwLf28BWRU:b9benhj)* status: 1 of 2 LGTMs obtained (waiting on @mispencer)

**Review by mispencer — COMMENTED** [review]
WIP because it is [flaky](https://github.com/mispencer/ycmd/runs/4241219467).

Omnisharp appear to have issues if you call it at certain points in loading process.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1610#-:-MoiyygJDz2XFPBa4Ztw:bxf3iwg)* status: 1 of 2 LGTMs obtained (waiting on @mispencer)

**Comment by bstaletic** [comment]
Woah! @mispencer Thanks a lot!

Only reason I'm not approving is the WIP tag.

**Comment by bstaletic** [comment]
@puremourning Like asked in gitter, should we merge this and then push the ycmd update?

**Comment by puremourning** [comment]
@Mergifyio rebase

**Review by mispencer — COMMENTED** [review]
Well, if you want to deal with flakey tests, you can merge this.

I suspect fixing the flakiness will require fixes upstream, which I haven't had time to look into yet. 

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1610#-:-Mot5x782yxPdfbftcZt:b-m3hf5o)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)

**Comment by puremourning** [comment]
@mergifyio rebase

**Review by puremourning — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1610#-:-Mot4xzREueaDB9gGnAb:b-uwkowd)* status: 1 of 2 LGTMs obtained (waiting on @mispencer)

**Comment by puremourning** [comment]
If CI is green, let's bag it :)

We're kinda used to flaky tests by now. Thanks for doing this @mispencer

**Comment by bstaletic** [comment]
Obviously, if you do know how to make our tests stabler (I'm making that a word), we'll gladly take it!

**Comment by puremourning** [comment]
merged and updated submodule.

**Pull request merged**
