### PR TITLE
[READY] Allow clients to get the docs in sig help response

### PR DESCRIPTION
**Pull request by bstaletic**
At the request of @BorisKozo, we allow clients to access documentation in the signature help responses. Jedi currently can't support that feature, but the others can. LSP requires no changes to work.

Open questions:

- Do we want to make this opt-in or opt-out, to save bandwidth?
- Should I add more tests?
- Should we omit the `documentation` property, if the string is empty?
- What the hell happened to `./update_api_docs.py` that it generated nothing?

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1501)

### CODE REVIEW

**Review by bstaletic — COMMENTED** [review]
Fixed java tests.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1501#-:-MMBi6yI3z0l-H4ZVTgR:b4ss1x6)* status: 0 of 2 LGTMs obtained

**Comment by puremourning** [comment]
* Do we want to make this opt-in or opt-out, to save bandwidth?

Nah.

* Should I add more tests?

I think basic tests are fine.

* Should we omit the documentation property, if the string is empty?

Nah

* What the hell happened to ./update_api_docs.py that it generated nothing?

erm, no clue.

**Comment by bstaletic** [comment]
>> - What the hell happened to ./update_api_docs.py that it generated nothing?

> erm, no clue.

I mean, we should figure it out, because we really need to keep the docs up to date. In case you didn't notice, the `label:` section was indented with only one space. I indented it correctly. I have no idea how that happened.

**Review by puremourning — APPROVED** [review]
:lgtm:

the api update is fine.

> Reviewed 4 of 7 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1501#-:-MMCJKE34G6wm3SZVAp0:b-ur7xwx)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Comment by bstaletic** [comment]
> the api update is fine

So it is.

**Comment by bstaletic** [comment]
:lgtm_strong:

**Pull request merged**
