### PR TITLE
[READY] Stop vendoring GTest, GMock and Google Benchmark

### PR DESCRIPTION
**Pull request by bstaletic**
Now that we require cmake 3.14, we can stop vendoring test/benchmark dependencies.

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1521)

### CODE REVIEW

**Review by puremourning — COMMENTED** [review]
Nice!

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1521#-:-MPs6ZVr3_yG0nSdr1m7:b-83sjoh)* status: 0 of 2 LGTMs obtained

**Comment by bstaletic** [comment]
Hopefully fixed builds on Winblows.

**Comment by bstaletic** [comment]
WTF is MSVC doing?

**Review by puremourning — COMMENTED** [review]
>   set_target_properties can not be used on an ALIAS target.

any idea what it means ?

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1521#-:-MQbkPBiCTvhwti6rtXY:b-u6lwto)* status: 0 of 2 LGTMs obtained

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1521)* status: 0 of 2 LGTMs obtained

___
*[cpp/ycm/benchmarks/CMakeLists.txt, line 53 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1521#-MQfWZuk5XaRNkyo56a6:-MQfWZuk5XaRNkyo56a7:b-5xbzbm) ([raw file](https://github.com/ycm-core/ycmd/blob/303c6a768ddb7b60256fa522fe9af4080ae285dd/cpp/ycm/benchmarks/CMakeLists.txt#L53)):*
> ```CMake
>     string( TOUPPER ${OUTPUTCONFIG} OUTPUTCONFIG )
>     # Can't use benchmark::benchmark ALIAS target here
>     set_target_properties( benchmark PROPERTIES
> ```

This is what cmake complained about, I think.

**Review by bstaletic — COMMENTED** [review]
Right, so the MSVC benchmark was easy to solve. What the hell is up with MSVC core tests?

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1521#-:-MQfa-SF0hs98YkDtfRI:b75i0je)* status: 0 of 2 LGTMs obtained

**Comment by bstaletic** [comment]
Woohoo! Finally green!

**Review by puremourning — CHANGES_REQUESTED** [review]
> Reviewed 143 of 146 files at r1, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1521)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

*[a discussion](https://reviewable.io/reviews/ycm-core/ycmd/1521#-MT_ajdT5J5r6srwnfJY:-MT_ajdT5J5r6srwnfJZ:b7j63z2) (no related file):*
After running `YCM_TESTRUN=1 ./build.py --all --build-dir build`, I'm getting untracked files for `gmock`:

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	cpp/ycm/tests/gmock/
```

Ditto benchmark:

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	cpp/ycm/benchmarks/benchmark/
	cpp/ycm/tests/gmock/
```

Need to add them to the gitignore.

---

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1521)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

*[a discussion](https://reviewable.io/reviews/ycm-core/ycmd/1521#-MT_ajdT5J5r6srwnfJY:-MT_cQHb3o6R4DCW8FKC:b-896fix) (no related file):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

After running `YCM_TESTRUN=1 ./build.py --all --build-dir build`, I'm getting untracked files for `gmock`:

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	cpp/ycm/tests/gmock/
```

Ditto benchmark:

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	cpp/ycm/benchmarks/benchmark/
	cpp/ycm/tests/gmock/
```

Need to add them to the gitignore.
</blockquote></details>

Done.

---

**Review by puremourning — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1521#-:-MTa0FYE21U462rvgrkj:bnfp4nl)* status: 1 of 2 LGTMs obtained

**Review by puremourning — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1521)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Pull request merged**
