### PR TITLE
[READY] Upgrade to LLVM 12

### PR DESCRIPTION
**Pull request by bstaletic**
To be honest, I didn't test this at all. We'll see how much I've messed up.

The new checksums are here, in case you want to double-check:

```
df0ac3ed745ded55ee97f3734fd709e1b38f8ef1c5e1241aed2460084b3a489d: libclang-12.0.0-win32.tar.bz2
d51bb78237695163971c646b1ffdf643c1a09126d21b949ef35e23a1d573dc86: libclang-12.0.0-win64.tar.bz2
8c07f90986edf5561dd1b81a8960f2e09372c583d4cd79dfac87a074f4b01b24: libclang-12.0.0-x86_64-apple-darwin.tar.bz2
24925c0f757f8eefa8062466f4006ba9973c83fada945e701fbb1d80dc42a7eb: libclang-12.0.0-x86_64-unknown-linux-gnu.tar.bz2
bc5bff4810f8ed174ca586af39fe3eca96c5031eb6e68ba037299612f5e24ebf: libclang-12.0.0-i386-unknown-freebsd11.tar.bz2
d1fba4923972cb4a1c795fbf841d6f0eed4aa84ad3db67a753ada0cabcd078ed: libclang-12.0.0-amd64-unknown-freebsd11.tar.bz2
75f465939dc71883d1961cc29a91839f1958e6036d771d2c3be5e5968cb748e5: libclang-12.0.0-aarch64-linux-gnu.tar.bz2
bc4775609488463c87d6b9833b5b5d1c3494c35b82dc31bdd2a5cfe073d9d1d0: libclang-12.0.0-armv7a-linux-gnueabihf.tar.bz2
91b8921d8d345e601f24a7c75caff2dd4ce6846265b4eb54e7f2a7ba35a937e7: clangd-12.0.0-win32.tar.bz2
3b12320182d091ffe4119bc5682fb94e8eece77a20ea5c84cfb5b3b045b5ab02: clangd-12.0.0-win64.tar.bz2
15197624243a35a721202f6666e638dfe77621c1b0a217ba51b4d587a89d34f7: clangd-12.0.0-x86_64-apple-darwin.tar.bz2
35f9f93d186c01424d8828a843267c7ba9753d19ed149866e1a9b0fd94f9bdd9: clangd-12.0.0-x86_64-unknown-linux-gnu.tar.bz2
8d683c5bf9c282ccb5d023ae8915f284d6c178a77e85bc4f0032a754fa3b0ef1: clangd-12.0.0-i386-unknown-freebsd11.tar.bz2
88b516b2a721aa7659f53d7db5016cf80b82667a1668b361b02141727d2a6da8: clangd-12.0.0-amd64-unknown-freebsd11.tar.bz2
595dc0f7e33fa6e16be7085e2a828a287cf04d12e07e1b86c7880f2c7d82f9bd: clangd-12.0.0-aarch64-linux-gnu.tar.bz2
5078fca2fe3792123577d5aa4314d0811a276fe5cd729ae19169600a86551b29: clangd-12.0.0-armv7a-linux-gnueabihf.tar.bz2
```

And I'll ping @inglor because external dependencies and the bump to clangd 12.

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1568)

### CODE REVIEW

**Comment by puremourning** [comment]
Corrected checksums:

```


Ben Jackson @puremourning 16:09
Checksum for libclang-12.0.0-win32.tar.bz2: 3823025d32ff03f6d010e84f1727f63119f49bcf56309f3e29d8dd08cb7f42ea
Checksum for clangd-12.0.0-win32.tar.bz2: f7cbd73e99783687898a7370b8ae8875ac25e97ef2b1a9fc7c7e3c4b2fc8e5c5
Checksum for libclang-12.0.0-win64.tar.bz2: 3d34f5df6270ed69731eb6d9f8e077b6efae3eed39df70a5616007dc29acf5f6
Checksum for clangd-12.0.0-win64.tar.bz2: c9e4f11822a60b49b9cd0be0673302c7595df09ce2eed4c030559b4102589c54
Checksum for libclang-12.0.0-x86_64-apple-darwin.tar.bz2: e3a703b97a01c2a35cbd25498609ec0db5a0e7025077c09efb2f1af273d13fbe
Checksum for clangd-12.0.0-x86_64-apple-darwin.tar.bz2: 4982c5e56274102ce0c830aad4cdbe21efd51883e5fc2cbe05ef29e4b820e6ec
Checksum for libclang-12.0.0-x86_64-unknown-linux-gnu.tar.bz2: dc7b08d63fcf504fdbcfc5b96c446beee8ee79dc96e8d315666b20030c41e29a
Checksum for clangd-12.0.0-x86_64-unknown-linux-gnu.tar.bz2: 0bb712b8d2a2d6861ea28b11167fc01c21336e5bce8682caab60257e32d9bba1
Checksum for libclang-12.0.0-i386-unknown-freebsd11.tar.bz2: e94fd35b48dac10e04846fc4a6d1a8b5b2392c20618b9b36b1f6b11f7ec6b64b
Checksum for clangd-12.0.0-i386-unknown-freebsd11.tar.bz2: b0e5b88fb628a9b21e50c92136b184326f48d6b5f99d779694dfc361614f641e
Checksum for libclang-12.0.0-amd64-unknown-freebsd11.tar.bz2: 00e4aceec213dc17b82485ee46edce1c2fb5b4742d234ca79fce33ebbff31d93
Checksum for clangd-12.0.0-amd64-unknown-freebsd11.tar.bz2: 0aaf368d65d03299c593a5a2eac9eeb6b7a15f6348096b225b6428dc254e7d25
Checksum for libclang-12.0.0-aarch64-linux-gnu.tar.bz2: 5a8007c70b617109c2816543fe8fc9baf0a250a0054063ef624763a97db88808
Checksum for clangd-12.0.0-aarch64-linux-gnu.tar.bz2: 5057ef4fafd5aaf7aefb0916603314e58658a166e76a33ea5c3810dabe2b2480
Checksum for libclang-12.0.0-armv7a-linux-gnueabihf.tar.bz2: 38b3ac02ae89907a75da159d72567481d2a705c56d41d4fc6e699ab6db13010f
Checksum for clangd-12.0.0-armv7a-linux-gnueabihf.tar.bz2: 31588fef3fcab8c5859a6372406921029ea16d80e2119ca532ee384330b177ce

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 170 of 170 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1568#-:-MZslx3i8MM8gKEvLjtI:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[ycmd/tests/clangd/testdata/virtual.cpp, line 1 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1568#-MZsluRICOGRrLIT4i0h:-MZsluRICOGRrLIT4i0i:bh95tte) ([raw file](https://github.com/ycm-core/ycmd/blob/c3b3bab959a20ed1d089e313681409b39284e2f6/ycmd/tests/clangd/testdata/virtual.cpp#L1)):*
> ```cpp
> struct foo_t {
> ```

what's this file used for ?

**Review by puremourning — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1568)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Review by bstaletic — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1568#-:-MZsn1hk9Z6QO4MuqCPY:bnfp4nl)* status: :shipit: complete! 2 of 2 LGTMs obtained (waiting on @puremourning)

___
*[ycmd/tests/clangd/testdata/virtual.cpp, line 1 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1568#-MZsluRICOGRrLIT4i0h:-MZsn6gVEXmYJtGs3R4-:b-pb2jv6) ([raw file](https://github.com/ycm-core/ycmd/blob/c3b3bab959a20ed1d089e313681409b39284e2f6/ycmd/tests/clangd/testdata/virtual.cpp#L1)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

what's this file used for ?
</blockquote></details>

For testing `GoToImplementation`. Clangd can provide a location list of all the "implementations" of a virtual member function or a virtual base class.

Should I have named it something else?

**Review by puremourning — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1568)* status: :shipit: complete! 2 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[ycmd/tests/clangd/testdata/virtual.cpp, line 1 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1568#-MZsluRICOGRrLIT4i0h:-MZsoh4SAryjzzXQMB5Q:bbnaf3c) ([raw file](https://github.com/ycm-core/ycmd/blob/c3b3bab959a20ed1d089e313681409b39284e2f6/ycmd/tests/clangd/testdata/virtual.cpp#L1)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

For testing `GoToImplementation`. Clangd can provide a location list of all the "implementations" of a virtual member function or a virtual base class.

Should I have named it something else?
</blockquote></details>

oh stupid reviewable saying diff skipped to avoid melting my cpu.

That's so enraging. SO ENRAGING.

**Pull request merged**
