### PR TITLE
Update abseil to the latest LTS.

### PR DESCRIPTION
**Pull request by bstaletic**
This should be enough to fix ycm-core/YouCompleteMe#4212

@Jaywalker, would you mind double checking my choice of abseil commit?

@puremourning Abseil's cmake is warning about this:

https://github.com/abseil/abseil-cpp/blob/lts_2023_08_02/CMakeLists.txt#L73-L78

We should figure out how to set that.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1725)

### CODE REVIEW

**Review by puremourning — APPROVED** [review]
:lgtm:

What happens if we enable that flag? Our build is c++17 so abseil should just use that and STFU

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1725#-:-Nnh0l_CE7mFJVS1cWkI:b8225uf)* status: 1 of 2 LGTMs obtained

**Review by puremourning — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1725)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Comment by Jaywalker** [comment]
An eyes-only review shows it has the patch necessary for the OpenBSD/FreeBSD fix. I'll do full build of it on my OpenBSD machine in a little bit and confirm it works, but I fully expect it will!

**Review by bstaletic — COMMENTED** [review]
> What happens if we enable that flag? Our build is c++17 so abseil should just use that and STFU

Tried it, it's fine. In general, a dependency saying "needs C++14" means "needs C++14 or newer". Plus abseil knows about C++17 and switches to it after turning the option on.

```
-- Performing Test ABSL_INTERNAL_AT_LEAST_CXX17
-- Performing Test ABSL_INTERNAL_AT_LEAST_CXX17 - Success
```

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1725#-:-NnkXQeA5qtiKSMi3jJh:b6ddths)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1725#-:-No7blFoCzitb9xx33h6:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Pull request merged**
