### PR TITLE
[READY] Catch exceptions and reject server-to-client requests

### PR DESCRIPTION
**Pull request by bstaletic**
If an unexpected exception happens during `_ServerToClientRequest`, we
used to erroneously close the connection with the server.

This can happen with gopls, as it tells us to just "watch everything"
which can hit the user's limit on the number of open files.

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1547)

### CODE REVIEW

**Review by puremourning — APPROVED** [review]
:lgtm:

Thanks.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1547#-:-MXEVtIr69h83mBRZDxJ:b9benhw)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Comment by bstaletic** [comment]
:lgtm:

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1547)* status: 0 of 2 LGTMs obtained (and 2 stale) (waiting on @bstaletic and @puremourning)

___
*[ycmd/completers/language_server/language_server_completer.py, line 619 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1547#-MXJKbsvB3RfjsV48b8I:-MXJKbsvB3RfjsV48b8J:b-bttan4) ([raw file](https://github.com/ycm-core/ycmd/blob/78115c19e3d73b70c2bcee8a4f04012c2dec02e3/ycmd/completers/language_server/language_server_completer.py#L619)):*
> ```Python
>           if reg[ 'method' ] == 'workspace/didChangeWatchedFiles':
>             self._CancelWatchdogThreads()
>         self.SendResponse( lsp.Void( request ) )
> ```

Can't be right to send the response then _also_ send a reject.

**Comment by bstaletic** [comment]
Yeah, all the tests are failing in CI. I'm looking at it.

**Comment by bstaletic** [comment]
Okay, before my screwup, this PR wasn't handling a case where `method == 'garbage'` (one of the methods we don't recognize). Here's an actual fix!

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1547)* status: 0 of 2 LGTMs obtained (and 2 stale) (waiting on @bstaletic and @puremourning)

___
*[ycmd/completers/language_server/language_server_completer.py, line 621 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1547#-MXJNSAM3SiKI7ygqlwh:-MXJNSANCnEbPgFLRPfd:b-c175vn) ([raw file](https://github.com/ycm-core/ycmd/blob/2ce6be25176e8a1c0bcd0ca03a99322b4867c16a/ycmd/completers/language_server/language_server_completer.py#L621)):*
> ```Python
>         self.SendResponse( lsp.Void( request ) )
>       else: # method unknown - reject
>         self.SendResponse( lsp.Reject( request, lsp.Errors.MethodNotFound ) )
> ```

I think we're still sending this twice.
we need the `return` back :)

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1547)* status: 0 of 2 LGTMs obtained (and 2 stale) (waiting on @bstaletic and @puremourning)

**Comment by bstaletic** [comment]
:lgtm:

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1547)* status: 1 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)

___
*[ycmd/completers/language_server/language_server_completer.py, line 619 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1547#-MXJKbsvB3RfjsV48b8I:-MXJfE0WChCSrMcAwrPV:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/78115c19e3d73b70c2bcee8a4f04012c2dec02e3/ycmd/completers/language_server/language_server_completer.py#L619)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Can't be right to send the response then _also_ send a reject.
</blockquote></details>

Done.
___
*[ycmd/completers/language_server/language_server_completer.py, line 621 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1547#-MXJNSAM3SiKI7ygqlwh:-MXJfEc_D7f0uSSvMifV:b8vf4bh) ([raw file](https://github.com/ycm-core/ycmd/blob/2ce6be25176e8a1c0bcd0ca03a99322b4867c16a/ycmd/completers/language_server/language_server_completer.py#L621)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I think we're still sending this twice.
we need the `return` back :)
</blockquote></details>

Yes, yes... Fixed.

**Review by puremourning — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1547#-:-MXJjSlK1PjtZFceB3pb:bnfp4nl)* status: :shipit: complete! 2 of 2 LGTMs obtained (waiting on @puremourning)

**Pull request merged**
