### PR TITLE
[READY] Print diagnostic code field

### PR DESCRIPTION
**Pull request by kadircet**
Clangd started populating diagnostic's code field with relevant information with https://reviews.llvm.org/D60822 and https://reviews.llvm.org/D58291. 

This patch aims to surface that information to ycmd users, as vscode does.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/ycmd/1239)

### CODE REVIEW

**Comment by puremourning** [comment]
@kadircet can you rebase and push the PR ? It still has the old CI system on the commit checks !

**Comment by puremourning** [comment]
Tests are failing on RLS

**Comment by kadircet** [comment]
yup just saw. I believe rust was not merged when I've written the patch?

They appear to be reporting codes like 'E0609', I have no idea whether they are meaningful or not. Anyone knows if these are worth keeping ?

**Comment by puremourning** [comment]
Latest master should be more flake-free. So maybe one more rebase ?

**Pull request merged**
