### PR TITLE
Display tsserver tags from docstrings in GetDoc and extra_menu_info

### LINKED ISSUE #1675: TS: include `@param` and `@returns` in docs
Hi,

would you consider adding `@param` and `@returns` for JavaScript/TypeScript docs? Like

```diff
--- a/ycmd/completers/typescript/typescript_completer.py
+++ b/ycmd/completers/typescript/typescript_completer.py
@@ -1128,6 +1128,27 @@ def _BuildCompletionExtraMenuAndDetailedInfo( request_data, entry ):
     extra_menu_info = re.sub( '\\s+', ' ', signature )
     detailed_info = [ signature ]
 
+  interface = []
+  returns = None
+
+  for tag in entry.get("tags", []):
+    if tag["name"] == "param":
+      text = tag["text"]
+      match = re.search("\s", text)
+      index = len(text) if match is None else match.start(0)
+      interface.append((text[:index], text[index + 1 :].strip()))
+
+    elif tag["name"] == "returns":
+      returns = tag["text"]
+
+  if returns is not None:
+    interface.append(("return", returns))
+
+  if len(interface) != 0:
+    length = max(len(name) for name, _ in interface)
+    _ = '\n'.join(f'{name.rjust(length)}: {text}' for name, text in interface)
+    detailed_info.append(_)
+
   docs = entry.get( 'documentation', [] )
   detailed_info += [ doc[ 'text' ].strip() for doc in docs if doc ]
   detailed_info = '\n\n'.join( detailed_info )
```
https://github.com/ycm-core/ycmd/blob/f53e7acf511748dd50f733c11b7de93416410c17/ycmd/completers/typescript/typescript_completer.py#L1130

The format (e.g. `.rjust` and `": "`) is obviously a matter of taste.

### PR DESCRIPTION
**Pull request by bstaletic**
Fixes #1675

- - -
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1716)

### CODE REVIEW

**Review by puremourning — APPROVED** [review]
:lgtm:

Out of curiosity, What other tags are there?

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1716#-:-NghCmMu6A4rATodCq3W:bqr4oa9)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[`ycmd/completers/typescript/typescript_completer.py` line 915 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1716#-NghC_bD43sR7wLZ8Lf2:-NghC_bD43sR7wLZ8Lf3:bl1a2er) ([raw file](https://github.com/ycm-core/ycmd/blob/1377a7bd6376a0c8e56fc74c2caa2fbf5b91e307/ycmd/completers/typescript/typescript_completer.py#L915)):*
> ```Python
> 
>     extra_info = []
>     for tag in info.get( 'tags', [] ):
> ```

Worth pulling this block into a func? Seems to be duplicated.

**Review by bstaletic — COMMENTED** [review]
Fixed flake8 errors.

There's a ton of tags:
https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html

I'm open for a more general solution if we can think of one.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1716#-:-NghJUyw1NHTF1U0eMWO:blelzfq)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)

**Review by bstaletic — COMMENTED** [review]
Taking a look at the tags, this pull request is incomplete. We miss `arg` as an alternative to `param` and `return` as the alternative to `returns` and probably a lot more.

Maybe we should take all tags and display them as `tag_name: tag_text`? Maybe without `:`?

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1716#-:-NghKSk8DLWoGttr5ALN:b-kzvh0p)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @bstaletic and @puremourning)

___
*[`ycmd/completers/typescript/typescript_completer.py` line 915 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1716#-NghC_bD43sR7wLZ8Lf2:-NghLfCXEVz4vdBPbKUw:b-94istg) ([raw file](https://github.com/ycm-core/ycmd/blob/1377a7bd6376a0c8e56fc74c2caa2fbf5b91e307/ycmd/completers/typescript/typescript_completer.py#L915)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Worth pulling this block into a func? Seems to be duplicated.
</blockquote></details>

Will do, but let's first decide how we want to handle other tags.

**Review by bstaletic — COMMENTED** [review]
Rebased. Ready for another round of review.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1716#-:-Nmqb79H5M5ZxPIXwSSD:bqy1vrx)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)

___
*[`ycmd/completers/typescript/typescript_completer.py` line 915 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1716#-NghC_bD43sR7wLZ8Lf2:-NmqasiV6JbV6m-i3SFQ:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/1377a7bd6376a0c8e56fc74c2caa2fbf5b91e307/ycmd/completers/typescript/typescript_completer.py#L915)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Will do, but let's first decide how we want to handle other tags.
</blockquote></details>

Done.

**Review by bstaletic — COMMENTED** [review]
Fixed the javascriptreact test.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1716#-:-NmrOX6f3OKwq-1GltqU:buuwfwu)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)

**Review by puremourning — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1716)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @bstaletic)

___
*[`ycmd/completers/typescript/typescript_completer.py` line 1133 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1716#-NmrWhO2-rewq4WqOhC4:-NmrWhO2-rewq4WqOhC5:b-q1w652) ([raw file](https://github.com/ycm-core/ycmd/blob/b3dcac52299ce9754d9fba8286b2c5a3c03a7324/ycmd/completers/typescript/typescript_completer.py#L1133)):*
> ```Python
>       extra_info.append( 'returns ' + tag_text )
>     elif tag_text:
>       extra_info.append( tag_text )
> ```

worth including the name? what do these look like?

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1716)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)

___
*[`ycmd/completers/typescript/typescript_completer.py` line 1133 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1716#-NmrWhO2-rewq4WqOhC4:-NmrZQhp1SJgdyEUAbia:bsbo2ry) ([raw file](https://github.com/ycm-core/ycmd/blob/b3dcac52299ce9754d9fba8286b2c5a3c03a7324/ycmd/completers/typescript/typescript_completer.py#L1133)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

worth including the name? what do these look like?
</blockquote></details>

It's the name of the tag, so in case of `@arg a - thing` the name is `arg` and `a - thing` is the text.

At least for arguments it felt redundant. I honestly don't know about the rest...

Here's the list of all officially defined tags:

https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1716)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)

___
*[`ycmd/completers/typescript/typescript_completer.py` line 1133 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1716#-NmrWhO2-rewq4WqOhC4:-NmvZJ9N6E2NAji7vg_u:bwozlir) ([raw file](https://github.com/ycm-core/ycmd/blob/b3dcac52299ce9754d9fba8286b2c5a3c03a7324/ycmd/completers/typescript/typescript_completer.py#L1133)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

It's the name of the tag, so in case of `@arg a - thing` the name is `arg` and `a - thing` is the text.

At least for arguments it felt redundant. I honestly don't know about the rest...

Here's the list of all officially defined tags:

https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html
</blockquote></details>

Included the tag name as well.

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1716#-:-Nmv_1mH4wuNStuYtnQw:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1716)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[`ycmd/tests/typescript/subcommands_test.py` line 629 at r4](https://reviewable.io/reviews/ycm-core/ycmd/1716#-Nmv_8t6DCKHJLoRq4g-:-Nmv_8t6DCKHJLoRq4g0:b-tcgbzg) ([raw file](https://github.com/ycm-core/ycmd/blob/bca9c2160767132b774bf61c92d02b9a9b6341ed/ycmd/tests/typescript/subcommands_test.py#L629)):*
> ```Python
>               'function single_argument_with_doc(a: string): string\n\n'
>               'A function with a single argument\n\n'
>               'a - The argument\n'
> ```

Wait why no ‘param:’ ?

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1716)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)

___
*[`ycmd/tests/typescript/subcommands_test.py` line 629 at r4](https://reviewable.io/reviews/ycm-core/ycmd/1716#-Nmv_8t6DCKHJLoRq4g-:-NmvdJjSCerg1eDM8YUN:bt2vr1b) ([raw file](https://github.com/ycm-core/ycmd/blob/bca9c2160767132b774bf61c92d02b9a9b6341ed/ycmd/tests/typescript/subcommands_test.py#L629)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Wait why no ‘param:’ ?
</blockquote></details>

Fixed.

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1716#-:-NmvnpHc3VPbLyfYaUra:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Pull request merged**
