### PR TITLE
[READY] Upgrade to LLVM11

### PR DESCRIPTION
**Pull request by bstaletic**
Finally! Finally the armv7a archive is ready.

For the record, I had to do the upload part manually. Seems like python, at least in version 3.8.6, ignores `os.path.basename()` when formatting the string, which causes a problem on the following line:

        file_path = os.path.basename( bundle_file_name ) ),

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1496)

### CODE REVIEW

**Review by puremourning — APPROVED** [review]
:lgtm:

tests are failing, I'll take a quick look

> Reviewed 161 of 161 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1496#-:-MKyzBrICK0-zVjzfUCr:b848b1g)* status: 1 of 2 LGTMs obtained

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1496)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

*[a discussion](https://reviewable.io/reviews/ycm-core/ycmd/1496#-MKyzSG79zWstkQc_lLw:-MKyzSG79zWstkQc_lLx:biz2370) (no related file):*
Looks like some code actions have changed, and there's a test for the min version that needs updating.

---

**Review by bstaletic — COMMENTED** [review]
One test is still failing, but that was left broken intentionally.

https://releases.llvm.org/11.0.0/tools/clang/tools/extra/docs/ReleaseNotes.html#diagnostics

That part says that we don't need to send the empty `textDocument/didChange` notification any more, yet the test goes broken if we don't.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1496#-:-MKzAoOO4q4nXJ4ugjE5:b1kyfdk)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)

*[a discussion](https://reviewable.io/reviews/ycm-core/ycmd/1496#-MKyzSG79zWstkQc_lLw:-MKzAmk84zvnpwx0wpPB:b-896fix) (no related file):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Looks like some code actions have changed, and there's a test for the min version that needs updating.
</blockquote></details>

Done.

---

**Review by bstaletic — COMMENTED** [review]
I think I got Winblows tests working too, now.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1496#-:-MKz_4ds0nb_PdfVoRmr:bby23po)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)

**Review by puremourning — APPROVED** [review]
:lgtm_strong: 

> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1496#-:-MKzdHo5CS3qpE09-0TV:b-uwkowd)* status: 1 of 2 LGTMs obtained

**Review by bstaletic — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1496#-:-MKze_sn0JdE05Osp4Lg:bnfp4nl)* status: :shipit: complete! 2 of 2 LGTMs obtained

**Pull request merged**
