### PR TITLE
[READY] Use abseil hash tables

### PR DESCRIPTION
**Pull request by bstaletic**
Here we replace standard associative containers with Abseil's "Swiss tables". It provides a massive performance improvement, but it takes a while to compile. Similar question as for parallel algorithms/TBB: Should it be opt-in? Opt-out?

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1546)

### CODE REVIEW

**Review by puremourning — CHANGES_REQUESTED** [review]
I don't think we should make this optional. It just increases our testing requirements. I would love for the standard library to have some sensible containers, but that does seem like a bit of a pipe dream.

It's a little sad that we have to build the entirety of absl just to use one file though.

On my laptop (not a very scientific experiment), I took 2 ycmd (one with this and one without) and did:

* git clean -xdf
* time ./buid.py --clang-completer
* git clean -xdf
* time ./build.py
* git clean -xdf

Results

With --clang-completer  (note, somewhat variable and perhaps dominated by download of libclang)

* With absl: ./build.py --clang-completer  143.20s user 12.12s system 248% cpu 1:02.63 total
* Wihtou absl : ./build.py --clang-completer  84.77s user 5.12s system 120% cpu 1:14.86 total

Without clang-completer:

* ./build.py  108.67s user 10.48s system 306% cpu 38.883 total
* Without absl: ./build.py  47.11s user 3.15s system 213% cpu 23.587 total


So it's a pretty big difference. Though it _felt_ faster than the boost days to me.

I'm not sure how I feel about this. If the runtime performance is _drastically_ better, then compile time is a small price to pay. I like that the change is brutally simple too.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1546#-:-MXHoHr8Cgz-XP3Wg4rd:b-amf364)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[cpp/CMakeLists.txt, line 235 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1546#-MXHvLVn1n62VeOUdYVc:-MXHvLVn1n62VeOUdYVd:blm0uh3) ([raw file](https://github.com/ycm-core/ycmd/blob/1c10761f7b454c4dffbab99397f0c63ed4b87573/cpp/CMakeLists.txt#L235)):*
> ```
> d9a31a2d440f33aa40d88b3b8a98f4c19ffaa182
> ```

What's this tag? Is this a LTS release ? Should we use one ? This commit has a [bug](https://github.com/abseil/abseil-cpp/issues/930) meaning that AppleClang is not properly recognised.

**Review by bstaletic — COMMENTED** [review]
> So it's a pretty big difference.

It is a significant difference.

> I would love for the standard library to have some sensible containers, but that does seem like a bit of a pipe dream.

I actually tested [what almost made it into C++20](https://github.com/WG21-SG14/SG14/blob/master/SG14/flat_map.h). I don't remember the numbers but it wasn't as good as Abseil. In fact, no hash map was as good as Abseil and I tested about a dozen.

> It's a little sad that we have to build the entirety of absl just to use one file though.

We actually don't compile the whole thing. It's just that hash tables have a million Abseil dependencies, especially in debug mode (the random library is extra).

> If the runtime performance is drastically better

It was drastic on my laptop. I'll rerun the benchmarks and come back to you.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1546#-:-MXI-WwDCRa_rkFZSz_R:bqlcw4u)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

___
*[cpp/CMakeLists.txt, line 235 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1546#-MXHvLVn1n62VeOUdYVc:-MXI-e6e5QBhIK6cYsPA:bqdnx9x) ([raw file](https://github.com/ycm-core/ycmd/blob/1c10761f7b454c4dffbab99397f0c63ed4b87573/cpp/CMakeLists.txt#L235)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

> ```
> d9a31a2d440f33aa40d88b3b8a98f4c19ffaa182
> ```

What's this tag? Is this a LTS release ? Should we use one ? This commit has a [bug](https://github.com/abseil/abseil-cpp/issues/930) meaning that AppleClang is not properly recognised.


</blockquote></details>

That was master at the time my branch was made. With Google libraries LTS branches are an afterthought in the "you nagged us too much, we'll make a stable branch once every 200 years" way. Google really wants everyone to stick to master.

I know you're not a fan of that, so I'm open for ideas.

**Review by bstaletic — COMMENTED** [review]
I reran the benchmarks. Each benchmark reports between 20 and 30% less time needed. Here are the raw numbers:

Abseil:
```
IdentifierCompleterFixture/CandidatesWithCommonPrefix/1/0                            762 ns          762 ns       885976
IdentifierCompleterFixture/CandidatesWithCommonPrefix/16/0                          4176 ns         4170 ns       167885
IdentifierCompleterFixture/CandidatesWithCommonPrefix/256/0                        84641 ns        84514 ns         8352
IdentifierCompleterFixture/CandidatesWithCommonPrefix/4096/0                     1558490 ns      1554263 ns          449
IdentifierCompleterFixture/CandidatesWithCommonPrefix/65536/0                   47058767 ns     46811844 ns           16
IdentifierCompleterFixture/CandidatesWithCommonPrefix_BigO                         44.85 NlgN      44.61 NlgN
IdentifierCompleterFixture/CandidatesWithCommonPrefix_RMS                              3 %             3 %
IdentifierCompleterFixture/CandidatesWithCommonPrefix/1/10                           758 ns          757 ns       913078
IdentifierCompleterFixture/CandidatesWithCommonPrefix/16/10                         4112 ns         4109 ns       169292
IdentifierCompleterFixture/CandidatesWithCommonPrefix/256/10                       45299 ns        45242 ns        15393
IdentifierCompleterFixture/CandidatesWithCommonPrefix/4096/10                     696128 ns       695548 ns         1005
IdentifierCompleterFixture/CandidatesWithCommonPrefix/65536/10                  15128297 ns     15075807 ns           47
IdentifierCompleterFixture/CandidatesWithCommonPrefix_BigO                         14.43 NlgN      14.38 NlgN
IdentifierCompleterFixture/CandidatesWithCommonPrefix_RMS                              0 %             0 %
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/1/0            4052 ns         4068 ns       172572
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/16/0          36293 ns        36311 ns        19290
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/256/0        497165 ns       496770 ns         1411
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/4096/0      7722883 ns      7713535 ns           92
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/65536/0   139670701 ns    139440629 ns            5
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix_BigO        2130.25 N       2126.74 N
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix_RMS               2 %             2 %
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/1/50           4167 ns         4192 ns       170205
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/16/50         35613 ns        35628 ns        19727
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/256/50       455046 ns       454751 ns         1527
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/4096/50     7112332 ns      7102186 ns          100
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/65536/50  118425480 ns    118204609 ns            6
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix_BigO        1806.75 N       1803.39 N
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix_RMS               1 %             1 %
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/1/0               827 ns          827 ns       860985
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/16/0             4864 ns         4861 ns       142451
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/256/0           91510 ns        91440 ns         7686
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/4096/0        1586782 ns      1582886 ns          445
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/65536/0      40269545 ns     40116670 ns           17
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix_BigO            38.39 NlgN      38.24 NlgN
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix_RMS                 2 %             2 %
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/1/50              826 ns          825 ns       835745
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/16/50            4883 ns         4880 ns       143241
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/256/50          58165 ns        58117 ns        12004
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/4096/50        935066 ns       932689 ns          737
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/65536/50     20415394 ns     20299864 ns           35
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix_BigO            19.47 NlgN      19.36 NlgN
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix_RMS                 0 %             0 %
```

STL
```
IdentifierCompleterFixture/CandidatesWithCommonPrefix/1/0                            838 ns          838 ns       842862
IdentifierCompleterFixture/CandidatesWithCommonPrefix/16/0                          4942 ns         4939 ns       142390
IdentifierCompleterFixture/CandidatesWithCommonPrefix/256/0                       102659 ns       102576 ns         6740
IdentifierCompleterFixture/CandidatesWithCommonPrefix/4096/0                     2228390 ns      2225810 ns          286
IdentifierCompleterFixture/CandidatesWithCommonPrefix/65536/0                   59668797 ns     59448737 ns           10
IdentifierCompleterFixture/CandidatesWithCommonPrefix_BigO                         56.88 NlgN      56.67 NlgN
IdentifierCompleterFixture/CandidatesWithCommonPrefix_RMS                              2 %             2 %
IdentifierCompleterFixture/CandidatesWithCommonPrefix/1/10                           843 ns          842 ns       849397
IdentifierCompleterFixture/CandidatesWithCommonPrefix/16/10                         4840 ns         4837 ns       140978
IdentifierCompleterFixture/CandidatesWithCommonPrefix/256/10                       61482 ns        61427 ns        11261
IdentifierCompleterFixture/CandidatesWithCommonPrefix/4096/10                     938727 ns       937755 ns          758
IdentifierCompleterFixture/CandidatesWithCommonPrefix/65536/10                  19134373 ns     19060760 ns           37
IdentifierCompleterFixture/CandidatesWithCommonPrefix_BigO                         18.25 NlgN      18.18 NlgN
IdentifierCompleterFixture/CandidatesWithCommonPrefix_RMS                              1 %             1 %
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/1/0            5729 ns         5619 ns       125409
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/16/0          47396 ns        47309 ns        15011
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/256/0        635581 ns       635010 ns         1115
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/4096/0     10049235 ns     10033486 ns           71
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/65536/0   177628372 ns    177271162 ns            4
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix_BigO        2709.39 N       2703.95 N
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix_RMS               1 %             1 %
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/1/50           5761 ns         5647 ns       124867
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/16/50         47908 ns        47809 ns        14789
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/256/50       598658 ns       598174 ns         1174
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/4096/50     9346271 ns      9331111 ns           74
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix/65536/50  164552175 ns    164263230 ns            4
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix_BigO        2509.97 N       2505.57 N
PythonSupportFixture/FilterAndSortUnstoredCandidatesWithCommonPrefix_RMS               1 %             1 %
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/1/0               917 ns          916 ns       763588
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/16/0             5749 ns         5745 ns       124016
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/256/0          101697 ns       101610 ns         6822
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/4096/0        1788952 ns      1784598 ns          396
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/65536/0      49896759 ns     49709205 ns           14
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix_BigO            47.56 NlgN      47.38 NlgN
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix_RMS                 2 %             2 %
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/1/50              902 ns          901 ns       782158
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/16/50            5514 ns         5510 ns       128922
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/256/50          65835 ns        65776 ns        10847
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/4096/50       1119397 ns      1116458 ns          620
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix/65536/50     29037651 ns     28932560 ns           26
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix_BigO            27.68 NlgN      27.58 NlgN
PythonSupportFixture/FilterAndSortStoredCandidatesWithCommonPrefix_RMS                 2 %             2 %
```

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1546#-:-MXI3at5CBsIDYQK489A:b-knx8rb)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

**Comment by puremourning** [comment]
OK then, I'm ok to trade off a few seconds of compile time for a 30% performance increase in the critical code.

Though I have to admit that at this point I would wager that the performance of ycmd is less limited by the c++ parts of the project; I expect it is the python layer and the downstream servers/communications that dominate real-world performance of ycmd, and that the performance of the synchronous YCM client code to be the most important factor that we can control.

**Review by bstaletic — COMMENTED** [review]
I won't even try to argue the point about python and vim being a bottleneck in the real world. If you feel this PR isn't such a good idea, I have no issues with closing it.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1546#-:-MXI7QJq3FaZ2WIvdZTZ:b-kgep5i)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

**Comment by puremourning** [comment]
I think it's good. I like it a lot.

Just wondering about the macOS compiler detection bug. I wonder what the impact is.

**Review by puremourning — COMMENTED** [review]
Looks like just warning flags:

https://abseil.io/docs/cpp/platforms/compilerflags#clang-flags

:lgtm: 

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1546#-:-MXI90HQ06hHjEs4spuZ:bquy2cg)* status: 1 of 2 LGTMs obtained (waiting on @puremourning)

**Review by puremourning — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1546)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Comment by bstaletic** [comment]
:lgtm:

**Pull request merged**
