### PR TITLE
Update gopls to v0.6.4

### PR DESCRIPTION
**Pull request by icholy**
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1530)

### CODE REVIEW

**Comment by bstaletic** [comment]
Thanks! :lgtm:, assuming the tests pass.

**Comment by icholy** [comment]
@bstaletic tests passed

**Comment by icholy** [comment]
@puremourning ping

**Review by puremourning — APPROVED** [review]
pong!

:lgtm: !

thanks!!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1530#-:-MSt37tCDeecwCpg3NiT:b-ph0z7q)* status: :shipit: complete! 2 of 2 LGTMs obtained (waiting on @icholy)

**Pull request merged**
