### PR TITLE
Fix GHA warnings

### PR DESCRIPTION
**Pull request by bstaletic**
This should shut GHA up for real this time.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1708)

### CODE REVIEW

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1708#-:-Ne9Al288paNPpVTgJyi:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Review by puremourning — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1708)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @bstaletic)

**Review by puremourning — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1708#-:-Ne9Ku0D3v0QvjSff7ge:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Comment by bstaletic** [comment]
Let's keep this pull request open until tomorrow. I want to see if turning that "lock old issues" bot was the culprit of rate limiting.

**Review by bstaletic — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1708#-:-NeEFjnj5NLXzr9ygEXM:bnfp4nl)* status: :shipit: complete! 2 of 2 LGTMs obtained (waiting on @bstaletic)

**Pull request merged**
