### PR TITLE
[READY] Call hierarchy support for LSP and typescript

### PR DESCRIPTION
**Pull request by bstaletic**
It works by returning a GoToResponse and it retrieves, not the whole call stack, but just the list off immediate callers.

Comments a very much needed, even if they are "WTF, who would want to use that implementation?!"

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1607)

### CODE REVIEW

**Comment by bstaletic** [comment]
Should be ready for review.

**Review by puremourning — CHANGES_REQUESTED** [review]
Essentially LGTM with some nits.

> Reviewed 1 of 3 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1607#-:-MpB-qSGBS3YkXS6fXri:bjf96bk)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[ycmd/completers/language_server/language_server_completer.py, line 51 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1607#-MpAxgV9A1Vk3MGK6pYe:-MpAxgV9A1Vk3MGK6pYf:b-hlqmjm) ([raw file](https://github.com/ycm-core/ycmd/blob/40db72905df0014481507ae0df4140f09a5f7c95/ycmd/completers/language_server/language_server_completer.py#L51)):*
> ```Python
> MAX_QUEUED_MESSAGES = 250
> 
> PROVIDERS_MAP = {
> ```

confused why we're not using this for the new commands?
___
*[ycmd/completers/language_server/language_server_completer.py, line 2464 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1607#-MpAy61m7TIOC7z1Tt-t:-MpAy61m7TIOC7z1Tt-u:bo4k0mq) ([raw file](https://github.com/ycm-core/ycmd/blob/40db72905df0014481507ae0df4140f09a5f7c95/ycmd/completers/language_server/language_server_completer.py#L2464)):*
> ```Python
>       raise RuntimeError( f'No { args[ 0 ] } calls found.' )
> 
>     assert len( preparation_item ) == 1 # I have no idea what else to do.
> ```

do we know under what circumstances we would get multiple results ?

Could it be like where there are multiple definitions of a function ? like in python:

```python
if something:
   def MyFunction( a , b ):
      # stuff
      pass
else:
  def MyFunction( d, e, f ):
      # other stuff
      pass
```

At least if this is possible can we trap this case with a friendlier error like "Not available: Multiple hierarchies were received, this is not currently supported."
___
*[ycmd/completers/language_server/language_server_completer.py, line 2481 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1607#-MpAzAHaEZvz4kem5XW0:-MpAzAHaEZvz4kem5XW1:bre1vp9) ([raw file](https://github.com/ycm-core/ycmd/blob/40db72905df0014481507ae0df4140f09a5f7c95/ycmd/completers/language_server/language_server_completer.py#L2481)):*
> ```Python
>       start_position = hierarchy_item[ 'fromRanges' ][ 0 ][ 'start' ]
>       goto_line = start_position[ 'line' ]
>       line_value = GetFileLines( request_data, filepath )[ goto_line ]
> ```

I think this can throw IndexError. We normally catch it IIRC
___
*[ycmd/completers/typescript/typescript_completer.py, line 685 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1607#-MpAzyg0E44I3IfYHx7V:-MpAzyg0E44I3IfYHx7W:big91qp) ([raw file](https://github.com/ycm-core/ycmd/blob/40db72905df0014481507ae0df4140f09a5f7c95/ycmd/completers/typescript/typescript_completer.py#L685)):*
> ```Python
>   def _CallHierarchy( self, request_data, args ):
>     self._Reload( request_data )
>     prepare_response = self._SendRequest( 'definition', {
> ```

what's this actually used for ? it doesn't appear to be necessary ?
___
*[ycmd/tests/clangd/subcommands_test.py, line 876 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1607#-MpB-DKH6kkUktkaIOdX:-MpB-DKIACGWMK1Jp2c7:b-qs20mb) ([raw file](https://github.com/ycm-core/ycmd/blob/40db72905df0014481507ae0df4140f09a5f7c95/ycmd/tests/clangd/subcommands_test.py#L876)):*
> ```Python
> 
>   @SharedYcmd
>   def test_Subcommands_GoToCallees( self, app ):
> ```

the test actually calls GoToCallers ...
___
*[ycmd/tests/java/subcommands_test.py, line 1961 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1607#-MpB-arX5t01WVPVxztO:-MpB-arX5t01WVPVxztP:brwwypw) ([raw file](https://github.com/ycm-core/ycmd/blob/40db72905df0014481507ae0df4140f09a5f7c95/ycmd/tests/java/subcommands_test.py#L1961)):*
> ```Python
>         'description': 'GoToCallers on a function call.' },
>       { 'request': { 'line': 20, 'col': 16, 'filepath': TEST_JAVA },
>         'response': [ has_entries( { 'line_num': 15, 'column_num': 41, 'filepath': TEST_JAVA } ) ],
> ```

seems awfully like this is > 80 chars ..

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1607)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

___
*[ycmd/completers/language_server/language_server_completer.py, line 51 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1607#-MpAxgV9A1Vk3MGK6pYe:-MpBEIC_-vO9v2tnUBe9:b-vjzeqg) ([raw file](https://github.com/ycm-core/ycmd/blob/40db72905df0014481507ae0df4140f09a5f7c95/ycmd/completers/language_server/language_server_completer.py#L51)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

confused why we're not using this for the new commands?
</blockquote></details>

I tried. The problem is that we have a single provider (`callHierarchyProvider`) and two subcommands (`GoToCallees` and `GoToCallers`).
___
*[ycmd/completers/language_server/language_server_completer.py, line 2464 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1607#-MpAy61m7TIOC7z1Tt-t:-MpBEtmK-gRHKeA2GoFC:b-s887yh) ([raw file](https://github.com/ycm-core/ycmd/blob/40db72905df0014481507ae0df4140f09a5f7c95/ycmd/completers/language_server/language_server_completer.py#L2464)):*
> do we know under what circumstances we would get multiple results ?

Not really. Never happened to me. The LSP specs allow that, but that's as far as my knowledge goes.

> can we trap this case with a friendlier error like "Not available: Multiple hierarchies were received, this is not currently supported."

Sure, why not.
___
*[ycmd/completers/language_server/language_server_completer.py, line 2481 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1607#-MpAzAHaEZvz4kem5XW0:-MpBGcE40uJMRFr2CnK1:be6xhtb) ([raw file](https://github.com/ycm-core/ycmd/blob/40db72905df0014481507ae0df4140f09a5f7c95/ycmd/completers/language_server/language_server_completer.py#L2481)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I think this can throw IndexError. We normally catch it IIRC
</blockquote></details>

Hmm...

- Typescript completer doesn't guard against `IndexError` in these cases.
- C# completer does.
- LSP completer does not guard against `IndexError`.
___
*[ycmd/completers/typescript/typescript_completer.py, line 685 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1607#-MpAzyg0E44I3IfYHx7V:-MpBFjbd8Xo8o3xLhnCR:b-b8wrxz) ([raw file](https://github.com/ycm-core/ycmd/blob/40db72905df0014481507ae0df4140f09a5f7c95/ycmd/completers/typescript/typescript_completer.py#L685)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

what's this actually used for ? it doesn't appear to be necessary ?
</blockquote></details>

Good point. Removed. That's what happens when the API has no docs.
___
*[ycmd/tests/clangd/subcommands_test.py, line 876 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1607#-MpB-DKH6kkUktkaIOdX:-MpBFYSW9nwq1nVQ4APV:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/40db72905df0014481507ae0df4140f09a5f7c95/ycmd/tests/clangd/subcommands_test.py#L876)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

the test actually calls GoToCallers ...
</blockquote></details>

Done.
___
*[ycmd/tests/java/subcommands_test.py, line 1961 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1607#-MpB-arX5t01WVPVxztO:-MpBK04C4bINfvP-Pfw8:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/40db72905df0014481507ae0df4140f09a5f7c95/ycmd/tests/java/subcommands_test.py#L1961)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

seems awfully like this is > 80 chars ..
</blockquote></details>

Done.

**Review by puremourning — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1607)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic and @puremourning)

___
*[ycmd/completers/language_server/language_server_completer.py, line 2481 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1607#-MpAzAHaEZvz4kem5XW0:-MpBWKWd8T4TwPepq3ye:b-uf5jhj) ([raw file](https://github.com/ycm-core/ycmd/blob/40db72905df0014481507ae0df4140f09a5f7c95/ycmd/completers/language_server/language_server_completer.py#L2481)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Hmm...

- Typescript completer doesn't guard against `IndexError` in these cases.
- C# completer does.
- LSP completer does not guard against `IndexError`.
</blockquote></details>

LSP handles it in _LocationListToGoTo

**Review by puremourning — COMMENTED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1607)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1607)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

___
*[ycmd/completers/language_server/language_server_completer.py, line 2481 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1607#-MpAzAHaEZvz4kem5XW0:-MpC9C-qAHRh71VstSxT:b-44k7c3) ([raw file](https://github.com/ycm-core/ycmd/blob/40db72905df0014481507ae0df4140f09a5f7c95/ycmd/completers/language_server/language_server_completer.py#L2481)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

LSP handles it in _LocationListToGoTo
</blockquote></details>

Okay, we're now dropping locations when we encounter `IndexError` in `CallHierarchy()`. Is that a reasonable approach?

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1607#-:-MpCQune99xho0PxslOO:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Pull request merged**
