### PR TITLE
[READY] Do not use Abseil on unsupported environments

### PR DESCRIPTION
**Pull request by bstaletic**
Instead of checking for `__CYGWIN__`, I decided to `try_compile()` `absl/base/policy_checks.h` to know if Abseil can be used.

The preprocessor blocks seem to have a lot of repetition. Not sure where to draw the line between readability and smaller diffs.

The `-DYCM_ABSEIL_SUPPORTED` in the extra conf is debatable. If someone on cygwin decides to edit ycmd's code, there will be errors. If we remove the flag from the extra conf, *we* will see `YouCompleteMe::HashMap` as an alias of `std::unordered_map` instead of `absl::flat_hash_map`.

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1557)

### CODE REVIEW

**Comment by bstaletic** [comment]
Someone does need to try this out.

**Review by puremourning — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1557)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

*[a discussion](https://reviewable.io/reviews/ycm-core/ycmd/1557#-MYVUhO46nvb-vAeZe6Q:-MYVUhO46nvb-vAeZe6R:b-rxt2w6) (no related file):*
By the looks of things, my Mac is not "supporting" abseil with this patch:

```
Found Python library: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin/libpython3.9.dylib
Found Python headers folder: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python3: /usr/local/opt/python@3.9/bin/python3.9 (found suitable version "3.9.1", required range is "3.6...3.10") found components: Interpreter Development Development.Module Development.Embed
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Using libclang archive: /Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/../clang_archives/libclang-11.0.0-x86_64-apple-darwin.tar.bz2
-- Using libclang to provide semantic completion for C/C++/ObjC
-- Using external libclang: /Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/build/lib/libclang.dylib
-- NOT using clang-tidy for static analysis.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/build
Scanning dependencies of target ycm_core
[  0%] Building CXX object ycm/CMakeFiles/ycm_core.dir/Candidate.cpp.o
[  8%] Building CXX object ycm/CMakeFiles/ycm_core.dir/Character.cpp.o
[  8%] Building CXX object ycm/CMakeFiles/ycm_core.dir/IdentifierDatabase.cpp.o
[  8%] Building CXX object ycm/CMakeFiles/ycm_core.dir/CodePoint.cpp.o
[ 25%] Building CXX object ycm/CMakeFiles/ycm_core.dir/IdentifierUtils.cpp.o
[ 25%] Building CXX object ycm/CMakeFiles/ycm_core.dir/IdentifierCompleter.cpp.o
[ 25%] Building CXX object ycm/CMakeFiles/ycm_core.dir/PythonSupport.cpp.o
[ 33%] Building CXX object ycm/CMakeFiles/ycm_core.dir/Repository.cpp.o
[ 33%] Building CXX object ycm/CMakeFiles/ycm_core.dir/Result.cpp.o
[ 41%] Building CXX object ycm/CMakeFiles/ycm_core.dir/Utils.cpp.o
[ 41%] Building CXX object ycm/CMakeFiles/ycm_core.dir/Word.cpp.o
[ 50%] Building CXX object ycm/CMakeFiles/ycm_core.dir/versioning.cpp.o
[ 50%] Building CXX object ycm/CMakeFiles/ycm_core.dir/ycm_core.cpp.o
[ 58%] Building CXX object ycm/CMakeFiles/ycm_core.dir/ClangCompleter/ClangCompleter.cpp.o
[ 58%] Building CXX object ycm/CMakeFiles/ycm_core.dir/ClangCompleter/ClangHelpers.cpp.o
[ 66%] Building CXX object ycm/CMakeFiles/ycm_core.dir/ClangCompleter/ClangUtils.cpp.o
[ 66%] Building CXX object ycm/CMakeFiles/ycm_core.dir/ClangCompleter/CompilationDatabase.cpp.o
[ 75%] Building CXX object ycm/CMakeFiles/ycm_core.dir/ClangCompleter/CompletionData.cpp.o
[ 75%] Building CXX object ycm/CMakeFiles/ycm_core.dir/ClangCompleter/Documentation.cpp.o
[ 83%] Building CXX object ycm/CMakeFiles/ycm_core.dir/ClangCompleter/Range.cpp.o
[ 83%] Building CXX object ycm/CMakeFiles/ycm_core.dir/ClangCompleter/TranslationUnit.cpp.o
[ 91%] Building CXX object ycm/CMakeFiles/ycm_core.dir/ClangCompleter/TranslationUnitStore.cpp.o
[100%] Linking CXX shared library /Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.cpython-39-darwin.so
[100%] Built target ycm_core
The build files are in: /Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/build
running build
running build_py
```

i.e. it didn't build abseil.

---
___
*[cpp/ycm/CMakeLists.txt, line 321 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1557#-MYVUSVV0lzix344CC8W:-MYVUSVV0lzix344CC8X:b-huf5vo) ([raw file](https://github.com/ycm-core/ycmd/blob/68bd31a7eeb2518e08cb9f335616ad9016fcc35f/cpp/ycm/CMakeLists.txt#L321)):*
> ```CMake
> 
> if( ${ABSL_SUPPORTED} )
>   set( EXTRA_LIBS ${EXTRA_LIBS} absl::flat_hash_map absl::flat_hash_set )
> ```

maybe print a message here and in an else block so that we can see when users report issues if they are using stl or abseil.

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1557)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

*[a discussion](https://reviewable.io/reviews/ycm-core/ycmd/1557#-MYVUhO46nvb-vAeZe6Q:-MYVX2wk-FGF9xdzrsUs:b-v2q4yz) (no related file):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

By the looks of things, my Mac is not "supporting" abseil with this patch:

```
Found Python library: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin/libpython3.9.dylib
Found Python headers folder: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python3: /usr/local/opt/python@3.9/bin/python3.9 (found suitable version "3.9.1", required range is "3.6...3.10") found components: Interpreter Development Development.Module Development.Embed
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Using libclang archive: /Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/../clang_archives/libclang-11.0.0-x86_64-apple-darwin.tar.bz2
-- Using libclang to provide semantic completion for C/C++/ObjC
-- Using external libclang: /Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/build/lib/libclang.dylib
-- NOT using clang-tidy for static analysis.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/build
Scanning dependencies of target ycm_core
[  0%] Building CXX object ycm/CMakeFiles/ycm_core.dir/Candidate.cpp.o
[  8%] Building CXX object ycm/CMakeFiles/ycm_core.dir/Character.cpp.o
[  8%] Building CXX object ycm/CMakeFiles/ycm_core.dir/IdentifierDatabase.cpp.o
[  8%] Building CXX object ycm/CMakeFiles/ycm_core.dir/CodePoint.cpp.o
[ 25%] Building CXX object ycm/CMakeFiles/ycm_core.dir/IdentifierUtils.cpp.o
[ 25%] Building CXX object ycm/CMakeFiles/ycm_core.dir/IdentifierCompleter.cpp.o
[ 25%] Building CXX object ycm/CMakeFiles/ycm_core.dir/PythonSupport.cpp.o
[ 33%] Building CXX object ycm/CMakeFiles/ycm_core.dir/Repository.cpp.o
[ 33%] Building CXX object ycm/CMakeFiles/ycm_core.dir/Result.cpp.o
[ 41%] Building CXX object ycm/CMakeFiles/ycm_core.dir/Utils.cpp.o
[ 41%] Building CXX object ycm/CMakeFiles/ycm_core.dir/Word.cpp.o
[ 50%] Building CXX object ycm/CMakeFiles/ycm_core.dir/versioning.cpp.o
[ 50%] Building CXX object ycm/CMakeFiles/ycm_core.dir/ycm_core.cpp.o
[ 58%] Building CXX object ycm/CMakeFiles/ycm_core.dir/ClangCompleter/ClangCompleter.cpp.o
[ 58%] Building CXX object ycm/CMakeFiles/ycm_core.dir/ClangCompleter/ClangHelpers.cpp.o
[ 66%] Building CXX object ycm/CMakeFiles/ycm_core.dir/ClangCompleter/ClangUtils.cpp.o
[ 66%] Building CXX object ycm/CMakeFiles/ycm_core.dir/ClangCompleter/CompilationDatabase.cpp.o
[ 75%] Building CXX object ycm/CMakeFiles/ycm_core.dir/ClangCompleter/CompletionData.cpp.o
[ 75%] Building CXX object ycm/CMakeFiles/ycm_core.dir/ClangCompleter/Documentation.cpp.o
[ 83%] Building CXX object ycm/CMakeFiles/ycm_core.dir/ClangCompleter/Range.cpp.o
[ 83%] Building CXX object ycm/CMakeFiles/ycm_core.dir/ClangCompleter/TranslationUnit.cpp.o
[ 91%] Building CXX object ycm/CMakeFiles/ycm_core.dir/ClangCompleter/TranslationUnitStore.cpp.o
[100%] Linking CXX shared library /Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.cpython-39-darwin.so
[100%] Built target ycm_core
The build files are in: /Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/build
running build
running build_py
```

i.e. it didn't build abseil.
</blockquote></details>

Huh... can you try again? I've just pushed an update.

---
___
*[cpp/ycm/CMakeLists.txt, line 321 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1557#-MYVUSVV0lzix344CC8W:-MYVX7tw4uhAXAElBXgr:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/68bd31a7eeb2518e08cb9f335616ad9016fcc35f/cpp/ycm/CMakeLists.txt#L321)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

maybe print a message here and in an else block so that we can see when users report issues if they are using stl or abseil.
</blockquote></details>

Done.

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1557)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic and @puremourning)

*[a discussion](https://reviewable.io/reviews/ycm-core/ycmd/1557#-MYVUhO46nvb-vAeZe6Q:-MYVb3C12yxzgvbCufs7:b-i9yr1v) (no related file):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Huh... can you try again? I've just pushed an update.
</blockquote></details>

Same, but with the message:

```
./build.py --build-dir build --clang-completer
Searching Python 3.9 libraries...
Found Python library: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin/libpython3.9.dylib
Found Python headers folder: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python3: /usr/local/opt/python@3.9/bin/python3.9 (found suitable version "3.9.1", required range is "3.6...3.10") found components: Interpreter Development Development.Module Development.Embed
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Using libclang archive: /Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/../clang_archives/libclang-11.0.0-x86_64-apple-darwin.tar.bz2
-- Using libclang to provide semantic completion for C/C++/ObjC
-- Using external libclang: /Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/build/lib/libclang.dylib
-- Using STL hash tables
-- NOT using clang-tidy for static analysis.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/build
Scanning dependencies of target ycm_core
[  0%] Building CXX object ycm/CMakeFiles/ycm_core.dir/Candidate.cpp.o
[  8%] Building CXX object ycm/CMakeFiles/ycm_core.dir/CodePoint.cpp.o
[  8%] Building CXX object ycm/CMakeFiles/ycm_core.dir/Character.cpp.o
```

---

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1557)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

*[a discussion](https://reviewable.io/reviews/ycm-core/ycmd/1557#-MYVUhO46nvb-vAeZe6Q:-MYVm6Ks692wGddFFx93:b-4spska) (no related file):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Same, but with the message:

```
./build.py --build-dir build --clang-completer
Searching Python 3.9 libraries...
Found Python library: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin/libpython3.9.dylib
Found Python headers folder: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python3: /usr/local/opt/python@3.9/bin/python3.9 (found suitable version "3.9.1", required range is "3.6...3.10") found components: Interpreter Development Development.Module Development.Embed
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Using libclang archive: /Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/../clang_archives/libclang-11.0.0-x86_64-apple-darwin.tar.bz2
-- Using libclang to provide semantic completion for C/C++/ObjC
-- Using external libclang: /Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/build/lib/libclang.dylib
-- Using STL hash tables
-- NOT using clang-tidy for static analysis.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/build
Scanning dependencies of target ycm_core
[  0%] Building CXX object ycm/CMakeFiles/ycm_core.dir/Candidate.cpp.o
[  8%] Building CXX object ycm/CMakeFiles/ycm_core.dir/CodePoint.cpp.o
[  8%] Building CXX object ycm/CMakeFiles/ycm_core.dir/Character.cpp.o
```
</blockquote></details>

This time it should actually work.

---

**Comment by bstaletic** [comment]
I can't make sense of this. Reverting just the `IdentifierDatabase.h` fixes everything.

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1557)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

___
*[cpp/ycm/CMakeLists.txt, line 329 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1557#-MYeli3I0dJC7JR7NUKs:-MYelEQM0jTUh4GlJWy5:bqz2x53) ([raw file](https://github.com/ycm-core/ycmd/blob/68bd31a7eeb2518e08cb9f335616ad9016fcc35f/cpp/ycm/CMakeLists.txt#L329)):*
> ```CMake
> 
> if ( ${ABSL_SUPPORTED} )
>   target_compile_definitions( ${PROJECT_NAME} PRIVATE YCM_ABSEIL_SUPPORTED )
> ```

This was causing troubles. `PRIVATE` means "add definition to this target only", so `ycm_core` saw `absl::flat_hash_map` and `ycm_core_tests` saw `std::unordered_map`. `PUBLIC` means "add definition to this target and every target that depends on it".
___
*[cpp/ycm/CMakeLists.txt, line 334 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1557#-MYem7cI5ejESb1oVZcG:-MYem7cI5ejESb1oVZcH:b-qo57l3) ([raw file](https://github.com/ycm-core/ycmd/blob/68bd31a7eeb2518e08cb9f335616ad9016fcc35f/cpp/ycm/CMakeLists.txt#L334)):*
> ```CMake
> # Makes MSVC conform to the standard
> if ( MSVC )
>   target_compile_options( ${PROJECT_NAME} PRIVATE "/permissive-" )
> ```

I changed this one as well, because we should prefer a more standard compiler.

**Comment by bstaletic** [comment]
Rebased.

**Review by puremourning — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1557)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic and @puremourning)

*[a discussion](https://reviewable.io/reviews/ycm-core/ycmd/1557#-MYVUhO46nvb-vAeZe6Q:-MZ7vGrq8R0WrIYOKQMW:bs3o1cz) (no related file):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

This time it should actually work.
</blockquote></details>

looks ok to me but the ci is still busted.

---

**Review by puremourning — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1557)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1557)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

*[a discussion](https://reviewable.io/reviews/ycm-core/ycmd/1557#-MYVUhO46nvb-vAeZe6Q:-MYemMObExvCslO6tEdd:b-xjxzyb) (no related file):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

looks ok to me but the ci is still busted.
</blockquote></details>

Not busted. Got cancelled, for whatever reason.

---

**Review by puremourning — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1557#-:-MZ7yF5o4-jYeTFChmwO:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Pull request merged**
