### PR TITLE
fix build.py for Solaris OS - add lib/64 to search paths (fix #1645)

### LINKED ISSUE #1645: ./build.py fails on Solaris OS
On Solaris the libpython.so is located in `$prefix/lib/64/` dir. But because `build.py:GetPossiblePythonLibraryDirectories()`  https://github.com/ycm-core/ycmd/blob/d1707c14883ced0e32fcca9c0f5dbd6849b5f751/build.py#L292-L296  does not check this directory, the build fails on Solaris OS.

### PR DESCRIPTION
**Pull request by jenda1**
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1646)

### CODE REVIEW

**Review by jenda1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1646)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1646#-N5pwwbh8gik73q1Zd4L):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Please write a commit message that describes the fix and why it works. 
</blockquote></details>

Solaris OS convention is to store the 64bit libraries in $prefix/lib/64/ path (see [Default Search Paths](https://docs.oracle.com/cd/E36784_01/html/E36857/chapter3-32.html). Because the build.py does not search by default just $prefix/lib and $prefix/lib64, it fails to find the python libraries and the build fails. I add the lib/64 path to the list of search options. This fix the build process for Solaris OS.

**Review by puremourning — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1646)* status: 0 of 2 LGTMs obtained (waiting on @jenda1)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1646#-N5pwwbh8gik73q1Zd4L):*
<details><summary><i>Previously, jenda1 wrote…</i></summary><blockquote>

Solaris OS convention is to store the 64bit libraries in $prefix/lib/64/ path (see [Default Search Paths](https://docs.oracle.com/cd/E36784_01/html/E36857/chapter3-32.html). Because the build.py does not search by default just $prefix/lib and $prefix/lib64, it fails to find the python libraries and the build fails. I add the lib/64 path to the list of search options. This fix the build process for Solaris OS.
</blockquote></details>

That's fine, but can you make it the commit message by `git commit --amend` and force push the branch? I don't want a commit that just says "fix [some number]" in the history if possible, thanks!

**Comment by jenda1** [comment]
sorry for misunderstanding. Fixed.

**Comment by puremourning** [comment]
it doesn't appear to have been fixed: https://github.com/ycm-core/ycmd/pull/1646/commits

**Review by puremourning — APPROVED** [review]
:lgtm:

Thanks!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1646#-:-N6lZcgp4zYyHc1jJTbc:b9benhj)* status: 1 of 2 LGTMs obtained (waiting on @jenda1)

**Review by jenda1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1646)* status: 1 of 2 LGTMs obtained (waiting on @jenda1)

**Comment by puremourning** [comment]
sorry my bad, I forgot to add a label. go bot, do your thing.

**Comment by puremourning** [comment]
Sorry about the delay, there's a weird flake8 error that's just appeared. it will be resolved soon and I'm sure the bot will eventually deign to merge this!

**Comment by puremourning** [comment]
@MergifyIO rebase

**Comment by puremourning** [comment]
Thanks!

**Pull request merged**
