### PR TITLE
Make --quiet mode default. Add --verbose switch

### PR DESCRIPTION
**Pull request by puremourning**
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1604)

### CODE REVIEW

**Review by bstaletic — CHANGES_REQUESTED** [review]
CI is red, because it failed to download that lombok thing.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1604#-:-MoPk7HKB1xx3v6QtJ_q:b-uie8um)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

___
*[build.py, line 1207 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1604#-MoPj7g00czr4Xj3SDlw:-MoPj7g00czr4Xj3SDlx:bmjxvql) ([raw file](https://github.com/ycm-core/ycmd/blob/5183113d9782b5b536eb916cf626748b855d1a00/build.py#L1207)):*
> ```Python
>       import shlex
>       sys.stderr.write( 'For example, run this: '
>                         + shlex.join(
> ```

A few suggestions:

1. Use `print('some message', file=sys.stderr)`.
2. Once you're using `print()` you can just do `print('first part', shlex.join( whatever ), 'second part')` and have python worry about formatting.
3. We have encountered an error. We should not exit `build.py` with a default exit code.
4. `build.py` already has a `BUILD_ERROR_MESSAGE`. Either use/change it, or drop it.

**Review by puremourning — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1604)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[build.py, line 1207 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1604#-MoPj7g00czr4Xj3SDlw:-MoQSto5CqwhbOlHL4uk:bx36yt5) ([raw file](https://github.com/ycm-core/ycmd/blob/5183113d9782b5b536eb916cf626748b855d1a00/build.py#L1207)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

A few suggestions:

1. Use `print('some message', file=sys.stderr)`.
2. Once you're using `print()` you can just do `print('first part', shlex.join( whatever ), 'second part')` and have python worry about formatting.
3. We have encountered an error. We should not exit `build.py` with a default exit code.
4. `build.py` already has a `BUILD_ERROR_MESSAGE`. Either use/change it, or drop it.
</blockquote></details>

1. ok, done (though I'm not sure this is all that much better :)
2. this stuffs it all on one line, which I didn't want
3. good shout, fixed
4. also fixed to make sure this makes sense. I've replaced all the sys.exit calls with a custom exception type and made the output sensible in both quiet and verbose modes.

**Review by bstaletic — APPROVED** [review]
The important points have been addressed. Bikeshedding a proper way to format a string to stderr is not particuularly useful. Thus :lgtm:.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1604#-:-MoQX7dY06BBT9v09pB3:b-sref0w)* status: 1 of 2 LGTMs obtained (waiting on @puremourning)

___
*[build.py, line 1207 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1604#-MoPj7g00czr4Xj3SDlw:-MoQVSUjBHRJvQjH1UgI:b-7jo4dt) ([raw file](https://github.com/ycm-core/ycmd/blob/5183113d9782b5b536eb916cf626748b855d1a00/build.py#L1207)):*
> ok, done (though I'm not sure this is all that much better :)

I just didn't want to look up how a raw `sys.stderr.write` handles flushing/buffering. I already know what `print()` does.

> this stuffs it all on one line, which I didn't want

You can always use explicit `\n` where you want them. Or even `sep = '\n'`/

**Review by puremourning — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1604)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @bstaletic)

___
*[build.py, line 1207 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1604#-MoPj7g00czr4Xj3SDlw:-MoQZgeM3alkZhIQ8WRd:bb6un1j) ([raw file](https://github.com/ycm-core/ycmd/blob/5183113d9782b5b536eb916cf626748b855d1a00/build.py#L1207)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

> ok, done (though I'm not sure this is all that much better :)

I just didn't want to look up how a raw `sys.stderr.write` handles flushing/buffering. I already know what `print()` does.

> this stuffs it all on one line, which I didn't want

You can always use explicit `\n` where you want them. Or even `sep = '\n'`/
</blockquote></details>

Done

**Review by puremourning — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1604#-:-MoQZmUD6WPEsdpZRi9D:bnfp4nl)* status: 1 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)

**Pull request merged**
