### PR TITLE
[READY] Use the archive with precompiled binaries for updating the resource dir

### LINKED ISSUE #1740: arm_neon.h missing from clang
including arm_neon.h always shows up as an error:
image

My local clang on my Mac M1 includes the arm_neon.h file, and I can compile my project locally.
```
$ ls /Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include/arm_neon.h
/Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include/arm_neon.h
```
However the YCM version of clang does not:
```
ls /Users/patchin/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/17.0.1/include/arm_*
/Users/patchin/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/17.0.1/include/arm_acle.h
/Users/patchin/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/17.0.1/include/arm_neon_sve_bridge.h
/Users/patchin/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/17.0.1/include/arm_cmse.h
```

It seems these headers need to be built but are not:
https://github.com/llvm/llvm-project/blob/main/clang/lib/Headers/CMakeLists.txt#L379

the file `arm_neon_sve_bridge.h` also includes the `arm_neon.h` file which doesn't exist

My :YcmDebugInfo 
```
:YcmD
YcmDebugInfo  YcmDiags
Printing YouCompleteMe debug information...
-- Resolve completions: Up front
-- Client logfile: /var/folders/nc/vzmrvhj95ldb1p36bmvgshg40000gn/T/ycm_y4ldp0y0.log
-- Server Python interpreter: /opt/homebrew/opt/python@3.11/bin/python3.11
-- Server Python version: 3.11.6
-- Server has Clang support compiled in: True
-- Clang version: clang version 17.0.1 (https://github.com/ycm-core/llvm f0e018b8aadf1be25e3af0daa7a87d505de67957)
-- No extra configuration file found
-- C-family completer debug information:
--   Clangd running
--   Clangd process ID: 36225
--   Clangd executable: ['/Users/patchin/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd', '-header-insertion-decorators=0', '-resource-dir=/Users/patchin/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party/clang/lib
/clang/17.0.1', '-limit-results=500']
--   Clangd logfiles:
--     /var/folders/nc/vzmrvhj95ldb1p36bmvgshg40000gn/T/clangd_stderrpujipwgw.log
--   Clangd Server State: Initialized
--   Clangd Project Directory: /Users/patchin/Workspace/media-framework
--   Clangd Open Workspaces: {'/Users/patchin/Workspace/media-framework'}
--   Clangd Settings: {}
--   Clangd Compilation Command: False
-- Server running at: http://127.0.0.1:55943
-- Server process ID: 36218
-- Server logfiles:
--   /var/folders/nc/vzmrvhj95ldb1p36bmvgshg40000gn/T/ycmd_55943_stdout_cfj40g1z.log
--   /var/folders/nc/vzmrvhj95ldb1p36bmvgshg40000gn/T/ycmd_55943_stderr_fw7dxnu6.log
-- Semantic highlighting supported: True
-- Virtual text supported: True
-- Popup windows supported: True
```

### PR DESCRIPTION
**Pull request by bstaletic**
While most headers in the resource directory are present in the clang source archive, some are generated during compiling.

As a bonus, non-header files do not exist in the resource directory, in the archives containing binaries. Previously we have manually removed a CMakeLists.txt, but have been leaving behind some READMEs.

HLSL headers are not installed, because the feature is highly experimental.
openmp_wrappers/{stdlib.h,time.h} are not intended to be included in resource directory.

Closes #1740

- - -
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1741)

### CODE REVIEW

**Review by bstaletic — COMMENTED** [review]
Here's when and why the change to clang resource directory was introduced.
https://github.com/llvm/llvm-project/commit/c17d9b4b125e5561925aa85aaa0b113e383a2ee5

In short, ARM intrinsics are 1MB and RISC-V are 10MB.

Now I wonder if we should commit these headers or maybe package them with `clangd` and `libclang` and  have them only be available if user enables clangd/libclang completer.
I'm definitely leaning towards making these things optional.

Additional benefit of that approach would be always using the resource dir that comes from the same archive as `clangd` and `libclang`.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1741#-:-Nugpty9E9jT3lkfO1Y5:b-31ofiw)* status: 0 of 2 LGTMs obtained

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1741)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[`update_clang_headers.py` line 69 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1741#-NugztlQ8MNoxLex_9Pb:-NugztlQ8MNoxLex_9Pc:bnf8rbz) ([raw file](https://github.com/ycm-core/ycmd/blob/60d43a577921e3077dad4d14233706f2d24d3bfb/update_clang_headers.py#L69)):*
> ```Python
> def UpdateClangHeaders( version, temp_dir ):
>   # The headers do not seem to differ between archives, so pick the smallest
>   archive_name = 'clang+llvm-18.1.1-arm64-apple-darwin.tar.xz'
> ```

Don’t hard-code version?

**Review by puremourning — COMMENTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1741)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

**Review by bstaletic — COMMENTED** [review]
Assuing the CI passes, this is ready.

Not vendoring the headers is a bit of a hassle. Part of download and extract should be done in `cpp/CMakeLists.txt`, because of libclang completer. The resource directory should be done by both clangd and libclang, but such that they don't step on one another's toes. Should the header archives be cached somewhere? It's a bit annoying to deal with and it is not fixing a user-facing problem.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1741#-:-NvNORWR4Hdmw1cLelth:b5ympw9)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

___
*[`update_clang_headers.py` line 69 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1741#-NugztlQ8MNoxLex_9Pb:-NvNONdG06AnPkbZRjSf:bt2vr1b) ([raw file](https://github.com/ycm-core/ycmd/blob/60d43a577921e3077dad4d14233706f2d24d3bfb/update_clang_headers.py#L69)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Don’t hard-code version?
</blockquote></details>

Fixed.

**Comment by bstaletic** [comment]
Seems to be working!

**Comment by puremourning** [comment]
:lgtm:

**Review by puremourning — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1741#-:-NvciB-_CKErMdt23dOa:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Pull request merged**
