### PR TITLE
Switch source header

### PR DESCRIPTION
**Pull request by mokchira**
Implements clangd's SwitchSourceHeader feature. Currenly issued as a GoTo response that will jump to the first line and column of the corresponding header/source of the current buffer.

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1623)

### CODE REVIEW

**Review by puremourning — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1623)* status: 0 of 2 LGTMs obtained (waiting on @mokchira)

___
*[ycmd/completers/cpp/clangd_completer.py, line 300 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1623#-MsZNGtE5UwPf8qr2oIX:-MsZNGtE5UwPf8qr2oIY:b-r8hku7) ([raw file](https://github.com/ycm-core/ycmd/blob/240a9bfafbbce530e3b8ce521e30a70c8bf7eff5/ycmd/completers/cpp/clangd_completer.py#L300)):*
> ```Python
>         lambda self, request_data, args: self.GetDoc( request_data )
>       ),
>       'SwitchSourceHeader': (
> ```

Pretty much all of our "go to" style subcommands start with `GoTo` and have some semantic meaning. Should we perhaps use `GoToAssociatedFile` or something?
___
*[ycmd/completers/cpp/clangd_completer.py, line 315 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1623#-MsZXiUKEIPlg7TEIUPP:-MsZXiUKEIPlg7TEIUPQ:ba5oqxf) ([raw file](https://github.com/ycm-core/ycmd/blob/240a9bfafbbce530e3b8ce521e30a70c8bf7eff5/ycmd/completers/cpp/clangd_completer.py#L315)):*
> ```Python
>     request  = lsp.BuildRequest( request_id, "textDocument/switchSourceHeader",
>             { "uri": uri } )
>     response = self.GetConnection().GetResponse( request_id, request, 30 )
> ```

There are constants defined for different timeout types. In this case I think you want `language_server_completer.REQUEST_TIMEOUT_COMMAND`
___
*[ycmd/completers/cpp/clangd_completer.py, line 317 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1623#-MsZYGGr6FjixpjMpWWa:-MsZYGGr6FjixpjMpWWb:b-233z5r) ([raw file](https://github.com/ycm-core/ycmd/blob/240a9bfafbbce530e3b8ce521e30a70c8bf7eff5/ycmd/completers/cpp/clangd_completer.py#L317)):*
> ```Python
>     response = self.GetConnection().GetResponse( request_id, request, 30 )
>     filepath = lsp.UriToFilePath( response[ 'result' ] )
>     return responses.BuildGoToResponse( filepath, 1, 1, "switch" )
> ```

As discussed, I think the description here should be the target filename.

We can also comment why we're supplying 1,1

Finally, we can perhaps specialise this GoTo response to add a flag that says "Ignore the line/column, this is file only". Perhaps adding a `"file_only": true/false` to the Location.

I'd suggest internal api like:

```
responses.BuildGoToResponse( filepath, 1, 1, description = filepath, file_only = True )
```

The file_only flag should only be added if supplied and is a hint to the client, not a requirement of the client.

We should also update the api docs to reflect this change.

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1623)* status: 0 of 2 LGTMs obtained (waiting on @mokchira)

*[a discussion](https://reviewable.io/reviews/ycm-core/ycmd/1623#-MsfNSZN1LdJVduez1vP:-MsfNSZN1LdJVduez1vQ:bb6nlnv) (no related file):*
looks like CI is failing. when we add new subcommands we have to update the subcommand list in the test.

---

**Comment by mokchira** [comment]
The main reasons for choosing SwitchSourceHeader are:

1) It maps directly to the clangd command name https://code.woboq.org/llvm/clang-tools-extra/clangd/ClangdLSPServer.h.html#130 
Note that clangd also has commands of the GoTo* style, and it has decided not to use that for SwtichSourceHeader either.

2) It is more explicit than GoToAssociatedFile. 

There are plusses and minusses to explicitness of course. The looseness of GoToAssociatedFile means that command could be repurposed for other types of jumps in other languages. The downside is if there ever came about another kind of jump in C/C++, that is if we had some notion of an associated file that is not the corresponding source or header and a server that can allow us to jump to it, then we would not be able to simple use GoToAssociatedFile for that. What might the associated file be if not the source or header? I don't know. Perhaps C++ 20 modules will have some need for something like that (or not, I am not read up on them) or a future version of the language. 

But I'm not completely against GoToAssociatedFile either. Just wanted to raise my rationale.

**Comment by mokchira** [comment]
I believe I've made all changes _except_ for the name change to GoToAssociatedFile in e01b536f081aac73aa12c490553b059b8a3af46b
If you still feel it should be GoToAssociatedFile given my rational above, then I'll go ahead and make that change as well.

**Review by bstaletic — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1623)* status: 0 of 2 LGTMs obtained (waiting on @mokchira and @puremourning)

___
*[ycmd/responses.py, line 85 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1623#-Mt9ISdK0N55MAE2N4wp:-Mt9ISdK0N55MAE2N4wq:bsu164s) ([raw file](https://github.com/ycm-core/ycmd/blob/e01b536f081aac73aa12c490553b059b8a3af46b/ycmd/responses.py#L85)):*
> ```Python
>   if description:
>     response[ 'description' ] = description
>   response[ 'file_only' ] = file_only
> ```

If we're doing this, we have to document the API extension. That consists of two parts:

1. Updating `docs/openapi.yml`
2. Running `update_api_docs.py`
___
*[ycmd/completers/cpp/clangd_completer.py, line 300 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1623#-MsZNGtE5UwPf8qr2oIX:-Mt9HiFW--7nAOZyImuj:bu0srmw) ([raw file](https://github.com/ycm-core/ycmd/blob/240a9bfafbbce530e3b8ce521e30a70c8bf7eff5/ycmd/completers/cpp/clangd_completer.py#L300)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Pretty much all of our "go to" style subcommands start with `GoTo` and have some semantic meaning. Should we perhaps use `GoToAssociatedFile` or something?
</blockquote></details>

Going by [this plugin's](https://github.com/compactcode/alternate.vim) convention, that would be `GoToAlternateFile`, but that could be misunderstood as `:h CTRL-^`.

**Review by puremourning — APPROVED** [review]
Thanks!

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1623#-:-MtiuIEgBsISahKZrZSP:b-ucfknh)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic and @mokchira)

*[a discussion](https://reviewable.io/reviews/ycm-core/ycmd/1623#-MtiuG5v1mVkv-SqV2Hh:-MtiuG5v1mVkv-SqV2Hi:bu7l6i4) (no related file):*
Need to update the API doc

---
___
*[ycmd/completers/cpp/clangd_completer.py, line 300 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1623#-MsZNGtE5UwPf8qr2oIX:-Mtiu2uY4-YHlIu3g2bK:b2m8hgm) ([raw file](https://github.com/ycm-core/ycmd/blob/240a9bfafbbce530e3b8ce521e30a70c8bf7eff5/ycmd/completers/cpp/clangd_completer.py#L300)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Going by [this plugin's](https://github.com/compactcode/alternate.vim) convention, that would be `GoToAlternateFile`, but that could be misunderstood as `:h CTRL-^`.
</blockquote></details>

Alternate sounds good to me. We already have GoToInclude which mirrors `gf` (and co)

**Review by mokchira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1623)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic and @puremourning)

*[a discussion](https://reviewable.io/reviews/ycm-core/ycmd/1623#-MtiuG5v1mVkv-SqV2Hh:-Mu6qNbr2lYUmKjDUhge:bpkd3b5) (no related file):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Need to update the API doc
</blockquote></details>

Ok updated docs/openapi.yml and ran update_api_docs.py

---
___
*[ycmd/responses.py, line 85 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1623#-Mt9ISdK0N55MAE2N4wp:-Mu7AdRjET8ReWGxE6N7:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/e01b536f081aac73aa12c490553b059b8a3af46b/ycmd/responses.py#L85)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

If we're doing this, we have to document the API extension. That consists of two parts:

1. Updating `docs/openapi.yml`
2. Running `update_api_docs.py`
</blockquote></details>

Done.
___
*[ycmd/completers/cpp/clangd_completer.py, line 300 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1623#-MsZNGtE5UwPf8qr2oIX:-Mu7AJQp8tyL93GF1y-B:bmk8nmz) ([raw file](https://github.com/ycm-core/ycmd/blob/240a9bfafbbce530e3b8ce521e30a70c8bf7eff5/ycmd/completers/cpp/clangd_completer.py#L300)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Alternate sounds good to me. We already have GoToInclude which mirrors `gf` (and co)
</blockquote></details>

Changed the name to GoToAlternateFile.
___
*[ycmd/completers/cpp/clangd_completer.py, line 315 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1623#-MsZXiUKEIPlg7TEIUPP:-Mu7AhA73TfQea8CM40U:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/240a9bfafbbce530e3b8ce521e30a70c8bf7eff5/ycmd/completers/cpp/clangd_completer.py#L315)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

There are constants defined for different timeout types. In this case I think you want `language_server_completer.REQUEST_TIMEOUT_COMMAND`
</blockquote></details>

Done.

**Review by puremourning — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1623)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic, @mokchira, and @puremourning)

___
*[ycmd/responses.py, line 80 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1623#-Mu7CHViC1vtfVTtehh5:-Mu7CHViC1vtfVTtehh6:b81zo9e) ([raw file](https://github.com/ycm-core/ycmd/blob/c488e909940b5102667590f480ec67b128be8afa/ycmd/responses.py#L80)):*
> ```Python
> 
> def BuildGoToResponseFromLocation( location, description = None,
>         file_only = False ):
> ```

our style is not to bin-pack arguments. break each argument at `,` and align them with the `( `

(same above)
___
*[ycmd/completers/cpp/clangd_completer.py, line 309 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1623#-Mu7CCTY2xcmnNJB5V5V:-Mu7CCTZAlOCqB6p_Zmw:b-s52dub) ([raw file](https://github.com/ycm-core/ycmd/blob/c488e909940b5102667590f480ec67b128be8afa/ycmd/completers/cpp/clangd_completer.py#L309)):*
> ```Python
>       # )
>     }
> ```

two empty lines between methods
___
*[ycmd/completers/cpp/clangd_completer.py, line 313 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1623#-Mu7CPiO1HPBpk0FzbGK:-Mu7CPiO1HPBpk0FzbGL:b-lv9gl6) ([raw file](https://github.com/ycm-core/ycmd/blob/c488e909940b5102667590f480ec67b128be8afa/ycmd/completers/cpp/clangd_completer.py#L313)):*
> ```Python
>     request_id = self.GetConnection().NextRequestId()
>     uri = lsp.FilePathToUri( request_data[ 'filepath' ] )
>     request  = lsp.BuildRequest( request_id, "textDocument/switchSourceHeader",
> ```

don't bin-pack arguments. if they don't fit, break at `,` and align with first argument after `( ` .
if that doesn't fit break at `(` and use 1 hanging indent for each arg

same below
___
*[ycmd/completers/cpp/clangd_completer.py, line 314 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1623#-Mu7Cx2NDDDLRMKdRNjg:-Mu7Cx2NDDDLRMKdRNjh:bfdwj1v) ([raw file](https://github.com/ycm-core/ycmd/blob/c488e909940b5102667590f480ec67b128be8afa/ycmd/completers/cpp/clangd_completer.py#L314)):*
> ```Python
>     uri = lsp.FilePathToUri( request_data[ 'filepath' ] )
>     request  = lsp.BuildRequest( request_id, "textDocument/switchSourceHeader",
>             { "uri": uri } )
> ```

this should use `lsp.TextDocumentIdentifier`
___
*[ycmd/completers/cpp/clangd_completer.py, line 317 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1623#-Mu7D8vUAvVaQFK70peg:-Mu7D8vUAvVaQFK70peh:b-r7asby) ([raw file](https://github.com/ycm-core/ycmd/blob/c488e909940b5102667590f480ec67b128be8afa/ycmd/completers/cpp/clangd_completer.py#L317)):*
From [the spec](https://clangd.llvm.org/extensions#switch-between-sourceheader):

> If the corresponding file can’t be determined, "" is returned. bug?

if this is `""` then we should raise `ValueError()` or something like we normally do when a GoTo has no target. 

We should have a test for that case, as they may change it (given the `bug?` above)
___
*[ycmd/tests/clangd/subcommands_test.py, line 767 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1623#-Mu7DWNSCPAV0qHC5TK_:-Mu7DWNSCPAV0qHC5TKa:bhwflyl) ([raw file](https://github.com/ycm-core/ycmd/blob/c488e909940b5102667590f480ec67b128be8afa/ycmd/tests/clangd/subcommands_test.py#L767)):*
> ```Python
>     ]:
>       with self.subTest( test = test ):
>         RunGoToTest_all( app, '', 'GoToAlternateFile', test )
> ```

need test for failure cases too.

**Comment by puremourning** [comment]
Thanks for the updates! Looking good. Just a few style nits things to tidy up, and I think the tests are failing in CI ?

**Review by mokchira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1623)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic, @mokchira, and @puremourning)

___
*[ycmd/completers/cpp/clangd_completer.py, line 314 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1623#-Mu7Cx2NDDDLRMKdRNjg:-MuaNGP431quYv5v_PiH:b-dck87n) ([raw file](https://github.com/ycm-core/ycmd/blob/c488e909940b5102667590f480ec67b128be8afa/ycmd/completers/cpp/clangd_completer.py#L314)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

this should use `lsp.TextDocumentIdentifier`
</blockquote></details>

I'm not sure what you mean. I grepped for "TextDocumentIdentifier" and it only came up in some third_party files.

**Review by mokchira — COMMENTED** [review]
Thanks! I'm not sure what to do about the tests... I think I still don't really understand the testing framework. Perhaps one of you could make the remaining necessary changes for me? It would really help me out.
Also, this is my first time contributing to an Open Source project, and I may need to some extra instructions on here and there.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1623#-:-MuaUvk_9DOeeqbcRTp5:bg8nlbz)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic, @mokchira, and @puremourning)

**Review by puremourning — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1623)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic, @mokchira, and @puremourning)

___
*[ycmd/completers/cpp/clangd_completer.py, line 314 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1623#-Mu7Cx2NDDDLRMKdRNjg:-MuagiLCALB4cd02V1pM:b-b7e1y7) ([raw file](https://github.com/ycm-core/ycmd/blob/c488e909940b5102667590f480ec67b128be8afa/ycmd/completers/cpp/clangd_completer.py#L314)):*
<details><summary><i>Previously, mokchira (Michael Buckley) wrote…</i></summary><blockquote>

I'm not sure what you mean. I grepped for "TextDocumentIdentifier" and it only came up in some third_party files.  
</blockquote></details>

Ok never mind, I was thinking of a change that I have in [my fork](https://github.com/puremourning/ycmd-1/blob/master/ycmd/completers/language_server/language_server_protocol.py#L580-L583)

**Review by puremourning — APPROVED** [review]
:lgtm:

let's merge this.

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1623#-:-N9M_0N19D5VONX6VVOJ:bvzkuce)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic and @puremourning)

**Review by puremourning — APPROVED** [review]
> Dismissed @bstaletic from a discussion.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1623)* status: 1 of 2 LGTMs obtained (waiting on @mokchira)

**Comment by puremourning** [comment]
@MergifyIO rebase

**Comment by puremourning** [comment]
tests are failing

**Comment by puremourning** [comment]
Seems abandoned.

**Comment by puremourning** [comment]
@mergifyio rebase

**Comment by puremourning** [comment]
@mergifyio rebase

**Comment by puremourning** [comment]
Thanks @xpac27 - I've pushed that change. let's see.

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r5, 4 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1623#-:-NKrmC1REQHqouOeQtqH:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @mokchira)

**Pull request merged**
