### PR TITLE
@Wentao[download-faster]: update download faster - sansna

### PR DESCRIPTION
**Pull request by sansna**
take advantage of pget to download several times faster

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1479)

### CODE REVIEW

**Comment by bstaletic** [comment]
Thanks for the pull request. I don't know what `pget` is, but it doesn't come from the standard library.

**Comment by sansna** [comment]
> Thanks for the pull request. I don't know what `pget` is, but it doesn't come from the standard library.

So what should I do next?

**Review by puremourning — COMMENTED** [review]
Thanks for sending a PR, but we don't want the installer to have dependencies outside of the standard libary. indeed we would love to ditch any of our third-party python dependencies.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1479#-:-MHk2jMa5cpM0f8Jt2t3:bd9zazi)* status: 0 of 2 LGTMs obtained

**Comment by bstaletic** [comment]
I don't know what @puremourning thinks, but it could work with something like

```python
try:
  import pget
  has_pget = True
except ImportError:
  has_pget = False
```

**Review by puremourning — COMMENTED** [review]
I guess I would have to understand the real benefits and what the actual problem is here. The additional complexity (and non-testability) worry me for something like this.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1479#-:-MHk3c472BUg1HF8YY-n:bshoxlb)* status: 0 of 2 LGTMs obtained

**Comment by bstaletic** [comment]
> I guess I would have to understand the real benefits and what the actual problem is here.

I completely agree with this.

**Comment by sansna** [comment]
> Thanks for sending a PR, but we don't want the installer to have dependencies outside of the standard libary. indeed we would love to ditch any of our third-party python dependencies.
> 
> > _[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1479#-:-MHk2jMa5cpM0f8Jt2t3:bd9zazi)_ status: 0 of 2 LGTMs obtained

Reminds me of the third_party folder in the repo.
So if I put the whole pget src code inside third_party should work.

**Comment by sansna** [comment]
> I guess I would have to understand the real benefits and what the actual problem is here. The additional complexity (and non-testability) worry me for something like this.
> 
> > _[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1479#-:-MHk3c472BUg1HF8YY-n:bshoxlb)_ status: 0 of 2 LGTMs obtained

Real test of downloading speed with requests.get, about tens of kilobytes per sec.
Using pget of 8 splits, speed goes up to 600 kilobytes per sec.

**Comment by puremourning** [comment]
Hmm, that is quite a big difference - do you know what the bottleneck is ? Seems odd.

**Comment by sansna** [comment]
> Hmm, that is quite a big difference - do you know what the bottleneck is ? Seems odd.

Please do tell me where is the bottleneck.

**Comment by puremourning** [comment]
Thanks for the PR, but it seems this has stalled. We're not keen on relying on non-standard library things particularly in the installer.

**Pull request closed without merging**
