### PR TITLE
Update rust analyzer

### PR DESCRIPTION
**Pull request by theli-ua**
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1582)

### CODE REVIEW

**Review by bstaletic — APPROVED** [review]
Thanks for the PR! :lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1582#-:-MgKdCjX2ySekMTdG9Xk:b-nka0ij)* status: 1 of 2 LGTMs obtained (waiting on @theli-ua)

**Review by puremourning — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1582#-:-MgKdf0xCchMAjftxTjX:bnfp4nl)* status: :shipit: complete! 2 of 2 LGTMs obtained (waiting on @theli-ua)

**Review by puremourning — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1582#-:-MgKdf0xCchMAjftxTjX:bnfp4nl)* status: :shipit: complete! 2 of 2 LGTMs obtained (waiting on @theli-ua)

**Review by puremourning — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1582)* status: :shipit: complete! 2 of 2 LGTMs obtained (waiting on @theli-ua)

**Pull request merged**
