### PR TITLE
RustCompleter: fix server progress transition

### PR DESCRIPTION
**Pull request by toxeus**
`_server_progress` is of type string. Before, a dict was assigned to `_server_progress` causing all state checks to return `False`. This lead to `RustCompleter` waiting for initialization forever because `ServerIsReady()` would always return `False`. Now, a string value is assigned to `_server_progress` which restores proper detection in `ServerIsReady()`, c.f.
https://github.com/rust-analyzer/rust-analyzer/blob/cb78c40b0ed1e8cf609457d63c5137022d2e1907/crates/rust-analyzer/src/lsp_ext.rs#L239-L258

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1483)

### CODE REVIEW

**Comment by puremourning** [comment]
Thanks for sending a PR !

I can see the tests all timed out, but it's because all of the rust tests failed:

```
=========================== short test summary info ============================
ERROR ycmd/tests/rust/debug_info_test.py::DebugInfo_RlsVersion_test[] - Runti...
ERROR ycmd/tests/rust/debug_info_test.py::DebugInfo_NoRlsVersion_test[] - Run...
ERROR ycmd/tests/rust/diagnostics_test.py::Diagnostics_DetailedDiags_test[]
ERROR ycmd/tests/rust/diagnostics_test.py::Diagnostics_FileReadyToParse_test[]
ERROR ycmd/tests/rust/diagnostics_test.py::Diagnostics_Poll_test[] - RuntimeE...
ERROR ycmd/tests/rust/get_completions_test.py::GetCompletions_Basic_test[] - ...
ERROR ycmd/tests/rust/rust_completer_test.py::GetCompleter_RAFound_test - Run...
ERROR ycmd/tests/rust/rust_completer_test.py::GetCompleter_RANotFound_test - ...
ERROR ycmd/tests/rust/rust_completer_test.py::GetCompleter_RAFromUserOption_test
ERROR ycmd/tests/rust/rust_completer_test.py::GetCompleter_InvalidRustRootFromUser_test
ERROR ycmd/tests/rust/rust_completer_test.py::GetCompleter_WarnsAboutOldConfig_test
ERROR ycmd/tests/rust/server_management_test.py::ServerManagement_RestartServer_test[]
ERROR ycmd/tests/rust/server_management_test.py::ServerManagement_CloseServer_Unclean_test[]
ERROR ycmd/tests/rust/server_management_test.py::ServerManagement_StopServerTwice_test[]
ERROR ycmd/tests/rust/server_management_test.py::ServerManagement_StartServer_Fails_test[]
```

> This lead to RustCompleter waiting for initialization forever

I'm struggling to understand how this is possible, given that we have regression tests that pass (or passed before this change).

Is this. something that's changed upstream since the version we pin to ? If so we'll need to pin to something else, or make this backward compatible.

**Comment by bstaletic** [comment]
@toxeus Which commit of rust-analyzer are you running? Check `:YcmDebugInfo`.

The rust-analyzer-preview from rust nightly-2020-08-19 still uses strings for the status, which is the rust-analyzer that gets installed with `./build.py --rust-analyzer`.

**Comment by toxeus** [comment]
Sorry for the delayed response. Yes, I'm not using `rust-analyzer` that gets installed with `build.py`. `rust-analyzer` is in heavy development. Therefore, updating frequently is highly beneficial to get the latest bug fixes and features in. I have now updated the pinned version to the one I was successfully using for the past week since the API change has been [identified](https://github.com/rust-analyzer/rust-analyzer/commit/1eed036a6e68aee6128d099e3a8f2c06a90b846b#diff-c1b9b7c419982b41288d691b246e1466R246) and fixed in this commit. Otherwise, the next person bumping `rust-analyzer` will need to go through the same process.

**Comment by toxeus** [comment]
Ok, it looks like the `rust-analyzer` API changed even a bit more than I've initially suspected. I can go through it and fix it if you'd be willing to merge such an update.

image

**Comment by puremourning** [comment]
sure. it's not uncommon when taking a new server that some small details of things like hover change, so if we need to fix up those tests, it's fine.

**Comment by puremourning** [comment]
for the record, one of the reasons the version is a little behind is that IIRC some components we rely on disappeared from rustup nightly for quite some time (rustfmt if I remember corretctLY)

**Comment by toxeus** [comment]
Thanks for the heads up. I'll take a look into this.

**Review by bstaletic — CHANGES_REQUESTED** [review]
Looks like rust-analyzer started to return plain text.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1483#-:-MJN9gR31jNWXnSKVXum:b-fbk3u0)* status: 0 of 2 LGTMs obtained (waiting on @toxeus)

___
*[ycmd/completers/rust/rust_completer.py, line 186 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1483#-MJNAQt12pwfsBcm1WO8:-MJNAQt12pwfsBcm1WO9:b-et1jyh) ([raw file](https://github.com/ycm-core/ycmd/blob/9d309270f8ab6a33c2e55ea4fbc6908a34b58916/ycmd/completers/rust/rust_completer.py#L186)):*
> ```Python
>     start = hover_response.rfind( '```rust\n' ) + len( '```rust\n' )
>     end = hover_response.rfind( '\n```' )
>     return responses.BuildDisplayMessageResponse( hover_response[ start:end ] )
> ```

This function needs to be re-written.

If the new, plain text, format is

```
namespace
type info
---
docstring
```

then we want onthe second line only.
___
*[ycmd/completers/rust/rust_completer.py, line 200 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1483#-MJN9sO47BytcKFYjVZR:-MJN9sO47BytcKFYjVZS:ba2cots) ([raw file](https://github.com/ycm-core/ycmd/blob/9d309270f8ab6a33c2e55ea4fbc6908a34b58916/ycmd/completers/rust/rust_completer.py#L200)):*
> ```Python
>     documentation = '\n'.join(
>       line for line in lines if line and not line.startswith( '```' ) ).strip()
>     return responses.BuildDetailedInfoResponse( documentation )
> ```

Let's not mess around with strippingthe backticks now. Just do:

    return responses.BuildDetailedInfoResponse(
      self.GetHoverResponse( request_data)[ 'value' ] )

**Comment by toxeus** [comment]
It's weird that `GetCompletions_Basic_test` fails only on 3 test setups. Is there a way to see on which assert it fails? Currently, the output doesn't provide any helpful information.

**Review by bstaletic — COMMENTED** [review]
It's a known flake. I hope we've managed to stabilize the tests now, so just rebase onto latest master and pay no attention to it.

And yes, the test output is huge and takes a while to get used to reading it.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1483#-:-MJSMDMe8sqAsh7HH47G:b-14qyw0)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic and @toxeus)

**Comment by toxeus** [comment]
@bstaletic looks like your workaround worked except for one setup. 

> Looks like rust-analyzer started to return plain text.

Nope, it's still returning markdown format. Unless I get further feedback I will consider this PR to be done.

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1483#-:-MJTDJvCD8daRcislfwo:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @toxeus)

**Review by bstaletic — CHANGES_REQUESTED** [review]
> Nope, it's still returning markdown format.

Right, I read the logs wrong. Just one small thing and we can merge this.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1483#-:-MJTO6WL0HdlsB1eLVOR:b-nq2ybg)* status: 1 of 2 LGTMs obtained (waiting on @toxeus)

___
*[ycmd/completers/rust/rust_completer.py, line 183 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1483#-MJTNy6x-5z7tfD62ZAp:-MJTNy6x-5z7tfD62ZAq:b-hhx3f3) ([raw file](https://github.com/ycm-core/ycmd/blob/544f93a2db9c2ff2fb1cb31c11da287f37e59e33/ycmd/completers/rust/rust_completer.py#L183)):*
> ```Python
>     # then find the last occurence of "```" as the end index and "```rust"
>     # as the start index and return the slice.
>     hover_response = hover_response.split( '\n___\n', 2 )[ 0 ]
> ```

This should also be fixed to split on `\n---\n`.

**Comment by toxeus** [comment]
> This should also be fixed to split on \n---\n.

Done.

**Review by bstaletic — APPROVED** [review]
Thanks for the pull request. :lgtm_strong: 

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1483#-:-MJXZJWz2sxeS9YykirI:b-wsv9pw)* status: 1 of 2 LGTMs obtained (and 1 stale)

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1483#-:-MJYa__E02JPVvhPM6J1:bnfp4nl)* status: :shipit: complete! 2 of 2 LGTMs obtained

**Comment by toxeus** [comment]
> Could you rebase on master and re-push ?

done

**Pull request merged**
