### PR TITLE
cpp: support -imsvc

### PR DESCRIPTION
**Pull request by Chilledheart**
[](https://github.com/Chilledheart)the option is supported for the MSVC-like frontend, just like `-isystem`
for GNU-like frontend.

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1634)

### CODE REVIEW

**Review by puremourning — COMMENTED** [review]
Thanks. Can we update the tests?

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1634#-:-MzxXEFx7CFb6XXi2BBm:b-kvakxq)* status: 0 of 2 LGTMs obtained

**Review by puremourning — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1634)* status: 0 of 2 LGTMs obtained (waiting on @Chilledheart)

**Comment by Chilledheart** [comment]
> Thanks. Can we update the tests?
> 
> > _[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1634#-:-MzxXEFx7CFb6XXi2BBm:b-kvakxq)_ status: 0 of 2 LGTMs obtained

Nice idea!
One small problem remains, `--drive-mode=cl` mode is supported under macOS/Linux which means you can cross-compile Windows programs under macOS/Linux in a MSVC-like way. However, in the unittests the previous testcases are marked as `@WindowsOnly`. Should we remove this restriction?

ycmd/tests/clang/flags_test.py:L1066
```
  @WindowsOnly
  def test_RemoveUnusedFlags_RemoveStrayFilenames_CLDriver( self ):
```

**Comment by puremourning** [comment]
my recollection is that it's all quite fiddly in this area. if the tests pass reliably on linux/macOS, then yeah sure, but ideally minimise complexity in this area. Thanks!

**Comment by puremourning** [comment]
thanks!

**Review by puremourning — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1634)* status: 0 of 2 LGTMs obtained (waiting on @Chilledheart)

**Review by puremourning — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1634#-:-N9N1EZ67nT21jzerdY6:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @Chilledheart)

**Pull request merged**
