### PR TITLE
Update gopls to v0.6.0

### PR DESCRIPTION
**Pull request by icholy**
https://github.com/golang/tools/releases/tag/gopls/v0.6.0

This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1514)

### CODE REVIEW

**Comment by bstaletic** [comment]
Thanks for the pull request. :lgtm:

Don't mind the CI failures. Even master is currently busted.

**Review by icholy — COMMENTED** [review]
Ok, FWIW the go tests pass locally for me.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1514#-:-MOlqKOn3yBpTAklE8s5:b-ybvjy4)* status: 1 of 2 LGTMs obtained

**Comment by bstaletic** [comment]
This is javascript being an ass. I have a fix waiting for review, here: #1512 .

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1514#-:-MOm7Xxm2_oRgfTUxgTa:bnfp4nl)* status: :shipit: complete! 2 of 2 LGTMs obtained (waiting on @icholy)

**Comment by puremourning** [comment]
> This is javascript being an ass. I have a fix waiting for review, here: #1512 .

Sorry I totally missed this one. Approved now

**Comment by bstaletic** [comment]
@icholy You'll have to rebase your pull request.

**Comment by icholy** [comment]
@bstaletic done.

**Review by puremourning — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1514#-:-MOmNzjj1MjMBFNfFenI:b-uwkowd)* status: 1 of 2 LGTMs obtained (and 1 stale) (waiting on @icholy)

**Comment by bstaletic** [comment]
Okay, CI is definitely passing, so :lgtm_strong:.

**Pull request merged**
