### PR TITLE
[READY] Avoid the deprecated SourceFileLoader.load_module

### PR DESCRIPTION
**Pull request by bstaletic**
Python 3.4 deprecated `SourceFileLoader.load_module` in favour of
`exec_module` and at the expense of writing 5 lines of pure boilerplate.

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1500)

### CODE REVIEW

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1500)* status: 0 of 2 LGTMs obtained

___
*[ycmd/tests/utils_test.py, line 428 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1500#-MLvuRiOD3HCZuZ3RSJo:-MLvuRiOD3HCZuZ3RSJp:bwcq03d) ([raw file](https://github.com/ycm-core/ycmd/blob/6b19d938e52a877f403b530c1fcfd21cdbb6f284/ycmd/tests/utils_test.py#L428)):*
> ```Python
>   assert_that( module, has_property( 'SomeMethod' ) )
>   assert_that( module.SomeMethod(), equal_to( True ) )
>   assert_that( sys.modules.keys(), has_item( module.__name__ ) )
> ```

Should this be

    assert_that( sys.modules, has_entry( module.__name__, module ) )

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1500)* status: 0 of 2 LGTMs obtained

___
*[ycmd/server_utils.py, line 35 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1500#-MLw0fI737HoIYT9I0uy:-MLw0fI737HoIYT9I0uz:b-avu18r) ([raw file](https://github.com/ycm-core/ycmd/blob/f876f207f2ff09c70a8e3087245281915383e2c2/ycmd/server_utils.py#L35)):*
> ```Python
> 
> 
> def SetUpPythonPath():
> ```

This is only called in `__main__.py`. Should we inline it and remove the file?

**Review by puremourning — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1500)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[ycmd/server_utils.py, line 35 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1500#-MLw0fI737HoIYT9I0uy:-MLw7l3b1HwAvtS3uwmu:beuky9u) ([raw file](https://github.com/ycm-core/ycmd/blob/f876f207f2ff09c70a8e3087245281915383e2c2/ycmd/server_utils.py#L35)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

This is only called in `__main__.py`. Should we inline it and remove the file?
</blockquote></details>

I was wondering that the other day. I thought maybe we used it in the tests, but it doesn't look like it. then I wondered if we imported it from the client, but again I don't think so.

so yeah inlining it seems fine, but also not necessary. up to you.
___
*[ycmd/utils.py, line 374 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1500#-MLw89HZ6AAxXP3qZzrz:-MLw89HZ6AAxXP3qZzs-:b-23y1l3) ([raw file](https://github.com/ycm-core/ycmd/blob/41deff708c1a064deee232f2be80b6f00e376a48/ycmd/utils.py#L374)):*
> ```Python
> 
> # Read the link and don't ask questions. Python is stupid.
> # https://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-full-path/50395128#50395128
> ```

maybe better to link to the actual python docs?

https://docs.python.org/3/library/importlib.html#importing-a-source-file-directly

we can also use the SO shortened link here.
___
*[ycmd/tests/utils_test.py, line 428 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1500#-MLvuRiOD3HCZuZ3RSJo:-MLw8QLR7T5ijclx32T8:b-a0kn07) ([raw file](https://github.com/ycm-core/ycmd/blob/6b19d938e52a877f403b530c1fcfd21cdbb6f284/ycmd/tests/utils_test.py#L428)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Should this be

    assert_that( sys.modules, has_entry( module.__name__, module ) )
</blockquote></details>

yeah I think so

maybe we can consider adding a test where a extra_conf_file does a relative import just to check that it works before/after?

**Comment by bstaletic** [comment]
WTF? How has this PR broken jdt on Windows *and only with VS 2017*??

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1500)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

___
*[ycmd/server_utils.py, line 35 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1500#-MLw0fI737HoIYT9I0uy:-MLwZpmV4PkpQ6urF2fc:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/f876f207f2ff09c70a8e3087245281915383e2c2/ycmd/server_utils.py#L35)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I was wondering that the other day. I thought maybe we used it in the tests, but it doesn't look like it. then I wondered if we imported it from the client, but again I don't think so.

so yeah inlining it seems fine, but also not necessary. up to you.
</blockquote></details>

Done.
___
*[ycmd/utils.py, line 374 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1500#-MLw89HZ6AAxXP3qZzrz:-MLw_99N5Q4rKv0eV-oO:b-ce5zkt) ([raw file](https://github.com/ycm-core/ycmd/blob/41deff708c1a064deee232f2be80b6f00e376a48/ycmd/utils.py#L374)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

maybe better to link to the actual python docs?

https://docs.python.org/3/library/importlib.html#importing-a-source-file-directly

we can also use the SO shortened link here.
</blockquote></details>

I used the docs.python.org link.
___
*[ycmd/tests/utils_test.py, line 428 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1500#-MLvuRiOD3HCZuZ3RSJo:-MLwfR1q-jZGn1Eteb4V:buh5b46) ([raw file](https://github.com/ycm-core/ycmd/blob/6b19d938e52a877f403b530c1fcfd21cdbb6f284/ycmd/tests/utils_test.py#L428)):*
> yeah I think so

Sure.

> maybe we can consider adding a test where a extra_conf_file does a relative import just to check that it works before/after?

Do you think it's worth the effort? I don't think I've ever seen a relative import in an extra conf and it sounds to me like this would be testing for a python bug.

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1500#-:-MLxb_AZ4ms__G5CeeXo:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[ycmd/tests/utils_test.py, line 428 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1500#-MLvuRiOD3HCZuZ3RSJo:-MLxbR7YBv43TvLnMr4v:b-qbczut) ([raw file](https://github.com/ycm-core/ycmd/blob/6b19d938e52a877f403b530c1fcfd21cdbb6f284/ycmd/tests/utils_test.py#L428)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

> yeah I think so

Sure.

> maybe we can consider adding a test where a extra_conf_file does a relative import just to check that it works before/after?

Do you think it's worth the effort? I don't think I've ever seen a relative import in an extra conf and it sounds to me like this would be testing for a python bug.
</blockquote></details>

nah, it's fine. I'll tel you if this breaks my relative imports in my extra conf files at work >......< :)

**Review by puremourning — APPROVED** [review]
:lgtm:

nice one

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1500#-:-MM1IOzk4EayjzXVcU6r:b-bsmtcc)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Comment by bstaletic** [comment]
:lgtm:

**Pull request merged**
