### PR TITLE
Clean up a gopls hack

### PR DESCRIPTION
**Pull request by bstaletic**
I have given it a very brief test and it seems to work.
@puremourning please give it a shot as well.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1706)

### CODE REVIEW

**Comment by puremourning** [comment]
I'll see if I can try this today. I'm working with docker and its cli is so bizarre I haven't intend the source most of the time.

**Comment by bstaletic** [comment]
Coverage data also suggests that this part was not used.

**Comment by puremourning** [comment]
Confirmed that this works only after I do `./build.py --skip-build --go-completer`

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1706#-:-NePL7qnD5geJXpgUktu:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Pull request merged**
