### PR TITLE
Add {server}_binary_path option for gopls, tsserver, rls

### PR DESCRIPTION
**Pull request by tomwei7**
Hi, as we known gopls in active development and still in alpha, gopls in submodule will outdated very quick. so i think give user option to manually specify gopls path will be great!

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1282)

### CODE REVIEW

**Comment by bstaletic** [comment]
Thanks for the PR.

Before I say anything, I should mention that I don't write in go and neither does @puremourning.

The rust server is just as fast moving as gopls at this point. This makes me wonder if creating `<server>_binary_path` for each LSP server is a good idea, especially considering `language_server` user option. Right now, I would prefer users to experiment with newer `gopls` commits through `language_server` option and send us PR (if not, just open an issue) to update the go tools submodule.

**Comment by tomwei7** [comment]
Thanks, I will try to update this pr.

**Comment by bstaletic** [comment]
@tomwei7 Take a look at #1289 and especially my patch. I'd say we should go that way, but @puremourning may disagree.

**Comment by puremourning** [comment]
I think I prefer to make use of an external one explicit, like we do in clangd. I know we discussed it at length for clangd and I'm happy with that solution.

**Comment by bstaletic** [comment]
I'm fine with that, but then I'd like to ask you to state your opinion in #1289 when you have the time.

**Comment by yan12125** [comment]
___
*[README.md, line 102 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1282#-LkJgrgz4iz-ye3C6zBk:-LkJgrh-5h7DhV8Ncrvt:b-ibebss) ([raw file](https://github.com/ycm-core/ycmd/blob/eefc22b148ea53ce318f5646ada7243ec812e12b/README.md#L102)):*
> ```Markdown
> **experimental** and changes in the near future might break backwards
> compatibility. There's also a Jedi-based completer for semantic completion for
> Python, an OmniSharp-based completer for C#, a [gopls]-based completer for Go,
> ```

I guess gocode reference in the end of this file should be updated to gopls, too.

**Comment by tomwei7** [comment]
Hi, I do update for this pr.

- add {server}_binary_path option for gopls, rls, and tsserver.
- check file exists and executable.
- add some test.

@puremourning It little hard to check file version isn't a supported, because we don't known what version is supported by current completer, need a lot of work to figure out.

**Comment by tomwei7** [comment]
___
*[README.md, line 102 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1282#-LkJgrgz4iz-ye3C6zBk:-LkOOnSs0bnqZru7b_mr:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/eefc22b148ea53ce318f5646ada7243ec812e12b/README.md#L102)):*
<details><summary><i>Previously, yan12125 (Chih-Hsuan Yen) wrote…</i></summary><blockquote>

I guess gocode reference in the end of this file should be updated to gopls, too.
</blockquote></details>

Done.

**Comment by tomwei7** [comment]
___
*[ycmd/completers/go/go_completer.py, line 51 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1282#-LkFOo5OB6D8W0oa75Yl:-LkOOr9g050lfCVqOa7Q:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/eefc22b148ea53ce318f5646ada7243ec812e12b/ycmd/completers/go/go_completer.py#L51)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Clangd is a bit more complex, since it figures out the whole command line. It's fine to just test if `utils.FindExecutable( user_options[ 'gopls_binary_path' ] )` returns `None`inside `__init__()`.
</blockquote></details>

Done.

**Comment by tomwei7** [comment]
___
*[README.md, line 467 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1282#-LkdYY4yAwfcz_Tgtrqj:-Lky_efJ2RYta8e0XXn6:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/0891469ad27b82a3e7fd7ced86155dce8aebb4b4/README.md#L467)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Godef isn't used any more either.
</blockquote></details>

Done.

**Comment by tomwei7** [comment]
___
*[ycmd/utils.py, line 675 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1282#-LkdiQiLBRBsFBmUfQDj:-Lky_j27COne9SzZUe4F:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/0891469ad27b82a3e7fd7ced86155dce8aebb4b4/ycmd/utils.py#L675)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

New options should be placed in `ycmd/default_settings.json` with their default values.

That would also make `GetExecutableOption` equivalent to `GetExecutable`, so let's just use that instead.
</blockquote></details>

Done.

**Comment by tomwei7** [comment]
___
*[ycmd/completers/rust/rust_completer.py, line 66 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1282#-LkdZXa10x1s4_KPdt3A:-Lky_oPH2mY6dtkqs3-y:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/0891469ad27b82a3e7fd7ced86155dce8aebb4b4/ycmd/completers/rust/rust_completer.py#L66)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

This needs to be worded better. One example:

    LOGGER.error( 'rustc_binary_path not specified, rls_binary_path ignored' )

@puremourning any other suggestions?
</blockquote></details>

Done.

**Comment by tomwei7** [comment]
___
*[ycmd/completers/typescript/typescript_completer.py, line 90 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1282#-Lkdgyfe7pC_qePQTMVd:-LkybLPO0n7ArX49upqy:bdb34mr) ([raw file](https://github.com/ycm-core/ycmd/blob/0891469ad27b82a3e7fd7ced86155dce8aebb4b4/ycmd/completers/typescript/typescript_completer.py#L90)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Drop `'tsserver'` here, so we don't look in `$PATH` any more.

Technically, this would be a breaking change, but it was never officially supported, so I think we're fine.

@puremourning Any objections?
</blockquote></details>

I don't want to any breaking change in this pr :face_with_head_bandage:

**Comment by tomwei7** [comment]
___
*[ycmd/tests/go/go_completer_test.py, line 42 at r6](https://reviewable.io/reviews/ycm-core/ycmd/1282#-LkyzdlVC-ahsm7zWQ6q:-LlX6gDh0fSZBPazLMhp:b-p59341) ([raw file](https://github.com/ycm-core/ycmd/blob/1bb06fc9f18216625a353ddd5bd54be89b2b5a92/ycmd/tests/go/go_completer_test.py#L42)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

> patching 'ycmd.completers.go.go_completer.GetExecutable' works. However, I'm not sure that's correct.

That's the correct thing to patch. 

> Obligatory "where to patch" which always gets me confused:

Yep. It's always confusing and always requires 3 readings.
</blockquote></details>

Thanks. This also confusing me.

**Comment by tomwei7** [comment]
___
*[ycmd/completers/rust/rust_completer.py, line 120 at r6](https://reviewable.io/reviews/ycm-core/ycmd/1282#-Lkz8Wtt5vaDsenJe6ZX:-LlXUwgp6o0VsPixL9zF:b-usw9d3) ([raw file](https://github.com/ycm-core/ycmd/blob/1bb06fc9f18216625a353ddd5bd54be89b2b5a92/ycmd/completers/rust/rust_completer.py#L120)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

is this in the debug info? I think now that these are all configurable, they should be debug info items so that we can clearly see them when there are issues.
</blockquote></details>

I'm not familiar with rust, so i just put it into debug info hope it useful.

**Comment by tomwei7** [comment]
@bstaletic Sounds good, I add roslyn_omnisharp_binary_path for cs completer.

**Comment by puremourning** [comment]
@bstaletic  - ok sure. there are only like minor revisions required to the docs right ?

**Comment by bstaletic** [comment]
We have both made comments that went unaddressed, but nothing major is missing.

**Comment by puremourning** [comment]
This PR seems to be abandoned :(

**Comment by bstaletic** [comment]
Not quite. I still have the updated version in my fork. It's lacking tests and I'm waiting for the migration to pytest to finish it.

I'll reopen this to serve as a reminder to myself.

**Comment by puremourning** [comment]
ok sure, thanks!

**Comment by bstaletic** [comment]
Superseded by #1395

**Pull request closed without merging**
