### PR TITLE
[READY] Update go completer

### PR DESCRIPTION
**Pull request by bstaletic**
Significant changes:

- Rename support
- References support
- Single file outside `$GOPATH` or a go module support

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1301)

### CODE REVIEW

**Comment by bstaletic** [comment]
I updated the PR to the latest gopls. Diagnostics are behaving odd:

- Running `ycmd/tests/go/diagnostics_test.py` passes, but only if tests aren't isolated.
- Running the test along with the rest of the test suite fails.
  - Relevant gist: https://gist.github.com/bstaletic/711145d1c663a86b223e8b039d67a4c2
- Spinning the tests using `WithRetry` fixes the `FileReadyToParse` and gopls eventually returns correct diags.
- `WithRetry` didn't help with the message poll diag test. I couldn't figure out how to make it pass, so I used `ExpectedFailure()` to skip it.

**Comment by preslavmihaylov** [comment]
can we revive this?

**Comment by preslavmihaylov** [comment]
We could also fast forward to latest gopls changes as this PR is a bit dated

**Comment by puremourning** [comment]
Boris updated it on Momday

**Comment by laoshaw** [comment]
youcompleteme does clangd etc just fine but not doing any autocomplete for golang, there is gopls installed under ycmd/third_party/go/bin/gopls(newest version 0.4.0), do I need configure it somehow in .vimrc to activate that? all I did is "python3 install.py --all", after that go is not autocompleting at all.

**Comment by bstaletic** [comment]
> do I need configure it somehow

No, but please open an issue report instead of discussing here.

**Pull request merged**
