### PR TITLE
[READY] Unify singleton repositories

### PR DESCRIPTION
**Pull request by bstaletic**
Not sure if `GetElements()`/`ClearElements()` is the right word, but I couldn't find a better name.

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1544)

### CODE REVIEW

**Review by bstaletic — COMMENTED** [review]
Mostly these are all mechanical changes from `ThingRepository` to `Repository< Thing >`.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1544#-:-MVmWrKiCs0O7KGfCxIo:bs4wupq)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[cpp/ycm/Repository.h, line 93 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1544#-MVmWzjDBPGe0QSBeZ7j:-MVmWzjDBPGe0QSBeZ7k:b9r8zgl) ([raw file](https://github.com/ycm-core/ycmd/blob/9c1936720cd2e78d86dab4ed8777869e197b63dc/cpp/ycm/Repository.h#L93)):*
> ```objc
> private:
>   Repository() = default;
>   [[gnu::visibility("hidden")]] ~Repository() = default;
> ```

Since we had to expose the entire class in the dynamic table, the destructor became visible, so this attribute keeps the old visibility setting. I've used `[[namespace::attribute(value)]]` form because compilers need to ignore unknown attributes of this form, as opposed to `__attribute__`. I didn't use some macro to include `[[msvc::whatever]]`, because I didn't feel like looking for MS docs. Yes, MSVC will issue a warning.

**Review by puremourning — CHANGES_REQUESTED** [review]
I don't think I fully reviewed this but I have some unpublished comments, I'll just publish them and review fully ..

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1544#-:-MXI0wea3rEIK92ayr4E:b-7c7jbj)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[cpp/ycm/Repository.h, line 76 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1544#-MVm4cn03_uJIjAZtVao:-MVm4cn03_uJIjAZtVap:biw49ho) ([raw file](https://github.com/ycm-core/ycmd/blob/30d472b94097c3aac2b7b77be86d32b5ec0a52ee/cpp/ycm/Repository.h#L76)):*
> ```objc
>   
>         if ( !element_object ) {
>           element_object = std::make_unique< T >( std::move( element ) );
> ```

`element_object =  std::move( element )` ?

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1544)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

___
*[cpp/ycm/Repository.h, line 76 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1544#-MVm4cn03_uJIjAZtVao:-MXI4G2XEgGaWeQrTLGa:bkvsgjv) ([raw file](https://github.com/ycm-core/ycmd/blob/30d472b94097c3aac2b7b77be86d32b5ec0a52ee/cpp/ycm/Repository.h#L76)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

`element_object =  std::move( element )` ?
</blockquote></details>

That wouldn't work because of the explicit constructor.

**Review by puremourning — CHANGES_REQUESTED** [review]
> Reviewed 15 of 23 files at r1, 2 of 3 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1544)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[cpp/ycm/Repository.h, line 93 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1544#-MVmWzjDBPGe0QSBeZ7j:-MXXTl3BDlz5Fwqao844:b-pxko4b) ([raw file](https://github.com/ycm-core/ycmd/blob/9c1936720cd2e78d86dab4ed8777869e197b63dc/cpp/ycm/Repository.h#L93)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Since we had to expose the entire class in the dynamic table, the destructor became visible, so this attribute keeps the old visibility setting. I've used `[[namespace::attribute(value)]]` form because compilers need to ignore unknown attributes of this form, as opposed to `__attribute__`. I didn't use some macro to include `[[msvc::whatever]]`, because I didn't feel like looking for MS docs. Yes, MSVC will issue a warning.
</blockquote></details>

do we really care? I mean should we just let the destructor be visible ? I;d rather than that fiddly gnu-specific attributes.
___
*[cpp/ycm/Repository.h, line 41 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1544#-MXXU7H28yoCVvki5VdB:-MXXU7H28yoCVvki5VdC:bcjddv5) ([raw file](https://github.com/ycm-core/ycmd/blob/2dd9c6688fba888672e8b1db61401f8262b24b71/cpp/ycm/Repository.h#L41)):*
> ```objc
> class Repository {
> public:
>   using Holder = std::unordered_map< std::string, std::unique_ptr< T > >;
> ```

absl::flat_hash_map ?
___
*[cpp/ycm/tests/Character_test.cpp, line 217 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1544#-MXXTzFZEjPBRa2nDAyb:-MXXTzFZEjPBRa2nDAyc:brcnxcz) ([raw file](https://github.com/ycm-core/ycmd/blob/2dd9c6688fba888672e8b1db61401f8262b24b71/cpp/ycm/tests/Character_test.cpp#L217)):*
> ```cpp
>   // represented as the Latin capital letter "E" plus the combining acute
>   // character) is the Latin small letter e with acute "é".
> <<<<<<< HEAD
> ```

conflict marker

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1544)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

___
*[cpp/ycm/Repository.h, line 93 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1544#-MVmWzjDBPGe0QSBeZ7j:-MXl7K5hAvZ4f4DUB2hK:b-r5qr4n) ([raw file](https://github.com/ycm-core/ycmd/blob/9c1936720cd2e78d86dab4ed8777869e197b63dc/cpp/ycm/Repository.h#L93)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

do we really care? I mean should we just let the destructor be visible ? I;d rather than that fiddly gnu-specific attributes.
</blockquote></details>

I was going to offer arguments why we might care:

1. "gnu-specific" works with clang and only MSVC is left out.
2. Smaller binary size.
3. Why expose things that have no purpose being exposed?

However, all this talk is only applicable when compiled for our benchmarks or tests. Otherwise `YCM_EXPORT` is defined as nothing. So I don't think we should care. Removed.
___
*[cpp/ycm/Repository.h, line 41 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1544#-MXXU7H28yoCVvki5VdB:-MXl6Lwr3QfsGJfE6Pln:bjl05y6) ([raw file](https://github.com/ycm-core/ycmd/blob/2dd9c6688fba888672e8b1db61401f8262b24b71/cpp/ycm/Repository.h#L41)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

absl::flat_hash_map ?
</blockquote></details>

Obviously! Done.
___
*[cpp/ycm/tests/Character_test.cpp, line 217 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1544#-MXXTzFZEjPBRa2nDAyb:-MXl7DHR0D8YPbFGwYzA:b-8agds0) ([raw file](https://github.com/ycm-core/ycmd/blob/2dd9c6688fba888672e8b1db61401f8262b24b71/cpp/ycm/tests/Character_test.cpp#L217)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

conflict marker
</blockquote></details>

D'oh!

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1544#-:-MXlUpwJ74QC4U784dAF:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Review by bstaletic — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1544#-:-MXlWVmE4a7u2Je0ut4Z:bnfp4nl)* status: :shipit: complete! 2 of 2 LGTMs obtained (waiting on @bstaletic)

**Pull request merged**
