### PR TITLE
[READY] Upgrade Omnisharp-Roslyn and add OgranizeImports subcommand

### PR DESCRIPTION
**Pull request by bstaletic**
Let's see how well this goes.

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1601)

### CODE REVIEW

**Comment by bstaletic** [comment]
@xiguichen Here's a PR, but I don't know how to go about these test failures. Do we need `msbuild` and/or dotnet SDKs?

**Comment by xiguichen** [comment]
@bstaletic  I think we don't need them.From the error, there should be some unit test failed. I made a fork of the project and checked that current master branch is OK, so the problem should not be caused by a dependency error.

**Comment by bstaletic** [comment]
>  I think we don't need them.

I asked because, without `msbuild`, I see this in the omnishar-roslyn log:

      It looks like you have Mono 6.4.0 or greater installed but MSBuild could not be found.
      Try installing MSBuild into Mono (e.g. 'sudo apt-get install msbuild') to enable better MSBuild support, or upgrade to latest Mono: https://www.mono-project.com/download/stable/.

And when I install msbuild, I get this message:

      It looks like you have Visual Studio 2019 installed without .NET Core SDK support which is required by OmniSharp.
       Try updating Visual Studio 2019 installation with .NET Core SDK to enable better MSBuild support.

> From the error, there should be some unit test failed.

Ugh... the C# test failures get really messy... The summary is that Omnisharp-Roslyn, in some cases doesn't respond with diagnostics, so we end up thinking it isn't ready yet. Here's where the exception is coming from: https://github.com/ycm-core/ycmd/blob/master/ycmd/tests/cs/__init__.py#L138

Here's the list of failed tests:

```
ERROR: test_Diagnostics_MaximumDiagnosticsNumberExceeded (diagnostics_test.DiagnosticsTest)
ERROR: test_GetCompletions_Unicode (get_completions_test.GetCompletionsTest)
ERROR: test_Subcommands_GetDoc_Function (subcommands_test.SubcommandsTest)
ERROR: test_Subcommands_GetToImplementation_Unicode (subcommands_test.SubcommandsTest)
 FAIL: test_Diagnostics_WithRange (diagnostics_test.DiagnosticsTest)
```

Once again, thanks for helping us with this.

**Comment by bstaletic** [comment]
Here's a link to a, hopefully, more readable log; https://gist.github.com/bstaletic/874a86f36d601d18b65c151bdb7e79a5

**Comment by xiguichen** [comment]
I tried to reproduce the problem. But seems I get different problem in two of my PC. In one of my PC I setup today, i always have the following problem:

`
    def decode(self, input, final=False):
        # decode input (taking the buffer into account)
        data = self.buffer + input
>       (result, consumed) = self._buffer_decode(data, self.errors, final)
E       UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 206: invalid continuation b
`

**Comment by bstaletic** [comment]
If you have a non-utf-8 filepath, ycmd might trip on that. Anyway, now you can see why we haven't upgraded the omnisharp-roslyn dependency in such a long time.

The up side is that users can point YCM to any roslyn server they like with `g:ycm_roslyn_binary_path`.

If you don't know how to get this working, I'll drop the second commit and just leave the `OrganizeImports` part.

**Comment by xiguichen** [comment]
May be you can drop the second commit for now. The failed testcase might be bug of OmniSharp again, I will do more test when I have time.

**Comment by bstaletic** [comment]
Dropped.

**Review by puremourning — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1601)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

**Review by puremourning — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1601#-:-MngN9K_D49SpKevq7Hm:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Pull request merged**
