### PR TITLE
[READY] Fix ycmd API documentation

### LINKED ISSUE #1577: Couple documentation issues
https://ycm-core.github.io/ycmd/#path--semantic_completer_available   , it is "completion" not "completer" 

https://ycm-core.github.io/ycmd/#path--event_notification
`ultisnips_snippets: object` was probably meant to be `ultisnips_snippets: []object`

### PR DESCRIPTION
**Pull request by bstaletic**
Fixes #1577 

Pay attention to the `/shutdown` request. It lacks a detailed description, so it looks ugly when viewed in browser.

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1578)

### CODE REVIEW

**Review by puremourning — APPROVED** [review]
:lgtm:

THanks.

If we want to write a description for shutdown, we should pobvably describe how there is a race that means you _might not_ get a response, in which case you should react to the PID exiting etc.

But I think meh about it mostly.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1578#-:-MeHBn2d-YXOsJGY45NS:b-mnna6i)* status: 1 of 2 LGTMs obtained

**Review by puremourning — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1578)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Review by bstaletic — COMMENTED** [review]
This is the description that I came up with:

```diff
diff --git a/docs/openapi.yml b/docs/openapi.yml
index c9ef5597b..f9feb8330 100644
--- a/docs/openapi.yml
+++ b/docs/openapi.yml
@@ -1649,6 +1649,15 @@ paths:
   /shutdown:
     post:
       summary: Request ycmd to shut down.
+      description: |-
+        When receiving `/shutdown` request, ycmd starts a new thread to
+        bring down all active subservers and shut itself down. This is done
+        in order to be able to send the response to the request from the
+        "old" thread.
+
+        Note that this means there's a race condition currently. If the shutdown
+        thread finishes before the response thread, there will be no response.
+        In that case, the client can react to ycmd's PID exiting.
       produces:
         application/json
       responses:
```

Does that look alright?

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1578#-:-MeHy00UAQ9Acd806MKq:b-ha8jlf)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Review by puremourning — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1578#-:-Mett4OWDI6KHECewMm8:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Pull request merged**
