### PR TITLE
[READY] Use urllib in update/build scripts

### PR DESCRIPTION
**Pull request by bstaletic**
Note that this doesn't call `request.close()`, unlike vimspector. The reason is that the examples in the docs don't use them. Should we? If we should, should we use context manager/`close()` in the completers that use urllib?

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1508)

### CODE REVIEW

**Review by puremourning — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1508)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[build.py, line 133 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1508#-MOwTnBn-CSFgTHSf8At:-MOwTnBn-CSFgTHSf8Au:b4jmjfy) ([raw file](https://github.com/ycm-core/ycmd/blob/9b5ea9f8e657f2e68fdad341ec47451abe8a6d19/build.py#L133)):*
> ```Python
> 
> def DownloadFileTo( download_url, file_path ):
>   request = urllib.request.urlopen( download_url )
> ```

isn't one of the things that requests does for us implement a timeout/retry ? 

In vimspector I have this: https://github.com/puremourning/vimspector/blob/f8d1e484f95e742ea6dac3cdcaeb94a64c501e78/python3/vimspector/installer.py#L538-L559
___
*[update_clang.py, line 207 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1508#-MOwU8fKBgllNGk4tPV0:-MOwU8fKBgllNGk4tPV1:b-rbdrtx) ([raw file](https://github.com/ycm-core/ycmd/blob/9b5ea9f8e657f2e68fdad341ec47451abe8a6d19/update_clang.py#L207)):*
> ```Python
> def DownloadClangLicense( version, destination ):
>   print( 'Downloading license...' )
>   request = urllib.request.urlopen(
> ```

same here, do we need to implement retry/timeout here?
___
*[update_clang.py, line 220 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1508#-MOwUIw09haz9zleJUSh:-MOwUIw09haz9zleJUSi:b-wqv11r) ([raw file](https://github.com/ycm-core/ycmd/blob/9b5ea9f8e657f2e68fdad341ec47451abe8a6d19/update_clang.py#L220)):*
> ```Python
> def Download( url ):
>   print( 'Downloading {}'.format( url.rsplit( '/', 1 )[ -1 ] ) )
>   return urllib.request.urlopen( url ).read()
> ```

we don't have to close this? 
___
*[update_omnisharp.py, line 45 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1508#-MOwUcOJ0wSuMwN0P_WZ:-MOwUcOJ0wSuMwN0P_W_:bp5sj0g) ([raw file](https://github.com/ycm-core/ycmd/blob/9b5ea9f8e657f2e68fdad341ec47451abe8a6d19/update_omnisharp.py#L45)):*
> ```Python
> def Download( url ):
>   print( 'Downloading {}'.format( url.rsplit( '/', 1 )[ -1 ] ) )
>   return urllib.request.urlopen( url, stream=True ).read()
> ```

is stream=True valid here? I thought we removed that elsewhere.
___
*[ycmd/__main__.py, line 41 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1508#-MOwUimbEt2rTZXNwSWB:-MOwUimbEt2rTZXNwSWC:b-nnhsab) ([raw file](https://github.com/ycm-core/ycmd/blob/f08a6df27e3af701eb36deef90eb337206b0a50f/ycmd/__main__.py#L41)):*
> ```Python
>     os.path.join( DIR_OF_REQUESTS_DEPS, 'urllib3', 'src' ),
>     os.path.join( DIR_OF_WATCHDOG_DEPS, 'watchdog', 'build', 'lib3' ),
>     os.path.join( DIR_OF_WATCHDOG_DEPS, 'pathtools' ),
> ```

I think this is from a different change ?

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1508)* status: 0 of 2 LGTMs obtained (waiting on @puremourning)

___
*[build.py, line 133 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1508#-MOwTnBn-CSFgTHSf8At:-MOx3kSZDIh51HsJuKlR:bcyywmi) ([raw file](https://github.com/ycm-core/ycmd/blob/9b5ea9f8e657f2e68fdad341ec47451abe8a6d19/build.py#L133)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

isn't one of the things that requests does for us implement a timeout/retry ? 

In vimspector I have this: https://github.com/puremourning/vimspector/blob/f8d1e484f95e742ea6dac3cdcaeb94a64c501e78/python3/vimspector/installer.py#L538-L559
</blockquote></details>

It does implement timeout capabilities, but the default timeout is `None`. Same goes for urllib.
___
*[update_clang.py, line 207 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1508#-MOwU8fKBgllNGk4tPV0:-MOx3v1AERUdwHqGGDH4:b-bk6bu6) ([raw file](https://github.com/ycm-core/ycmd/blob/9b5ea9f8e657f2e68fdad341ec47451abe8a6d19/update_clang.py#L207)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

same here, do we need to implement retry/timeout here?
</blockquote></details>

Same answer. Both libraries use the same value for the default timeout.
___
*[update_clang.py, line 220 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1508#-MOwUIw09haz9zleJUSh:-MOx4-yOEzss2Qi5-8_7:b-dzan4o) ([raw file](https://github.com/ycm-core/ycmd/blob/9b5ea9f8e657f2e68fdad341ec47451abe8a6d19/update_clang.py#L220)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

we don't have to close this? 
</blockquote></details>

I thought we don't, but now I'm not sure any more... 

Some examples in the docs do call `close()` (or the `with` thing) and some don't.
___
*[update_omnisharp.py, line 45 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1508#-MOwUcOJ0wSuMwN0P_WZ:-MOx6IZL1OpyCKh3ml49:b-4grvzq) ([raw file](https://github.com/ycm-core/ycmd/blob/9b5ea9f8e657f2e68fdad341ec47451abe8a6d19/update_omnisharp.py#L45)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

is stream=True valid here? I thought we removed that elsewhere.
</blockquote></details>

Good catch! Removed.
___
*[ycmd/__main__.py, line 41 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1508#-MOwUimbEt2rTZXNwSWB:-MOx5AYo6DVyqpm0nKMR:b-vkjikh) ([raw file](https://github.com/ycm-core/ycmd/blob/f08a6df27e3af701eb36deef90eb337206b0a50f/ycmd/__main__.py#L41)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I think this is from a different change ?
</blockquote></details>

Sorry, it is a separate commit. Earlier today we updated watchdog, but I forgot to clean up `sys.path` in a few files. I know it's sloppy, so... reverted.

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1508#-:-MPo_yqp1tZZvGbaLQou:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Review by inglor — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1508#-:-MPp-76MDGOx41xhTYGE:bnfp4nl)* status: :shipit: complete! 2 of 2 LGTMs obtained (waiting on @bstaletic)

**Pull request merged**
