### PR TITLE
Fix vswhere for Build Tools

### PR DESCRIPTION
**Pull request by dkaszews**
According to https://github.com/microsoft/vswhere/issues/22, `vswhere.exe` only finds full Visual Studio IDE instances. To find a naked Build Tools instance, one needs to explicitly add `-products 'Microsoft.VisualStudio.Product.BuildTools'` to the call, but that won't find IDE instances in turn.

The PR adds the second form as a fallback to support users who only have Build Tools installed without the full IDE.

```shell
> ./install.py --skip-build --verbose
Calling C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -latest -property installationVersion
vswhere returned nothing usable: ""
Retrying vswhere for Build Tools
Calling C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -latest -property installationVersion
 -products Microsoft.VisualStudio.Product.BuildTools
vswhere -latest returned version 17.10.35122.118
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1753)

### CODE REVIEW

**Review by bstaletic — CHANGES_REQUESTED** [review]
Thanks for fixing this! I've left two small comments.

Also, the diff is not that bad on Reviewable!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1753#-:-O3wAMg1E6XmOnP3VGNg:b-j6ktdc)* status: 0 of 2 LGTMs obtained (waiting on @dkaszews)

___
*[`build.py` line 150 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1753#-O3wAD0XDn4RWnjapJnT:-O3wAD0XDn4RWnjapJnU:bhbmbfe) ([raw file](https://github.com/ycm-core/ycmd/blob/3db0bfac2eb4a21dbbc960ec7f95c3b01db5aece/build.py#L150)):*
> ```Python
> 
> def FindLatestMSVC( quiet, preview=False ):
>   ACCEPTABLE_VERSIONS = [ 17, 16, 15 ]
> ```

This does not seem to be needed here.
___
*[`build.py` line 162 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1753#-O3w9dTQ2F-FOqInfkdm:-O3w9dTQ2F-FOqInfkdn:b-7um5be) ([raw file](https://github.com/ycm-core/ycmd/blob/3db0bfac2eb4a21dbbc960ec7f95c3b01db5aece/build.py#L162)):*
> ```Python
>       vswhere_args.append( '-prerelease' )
> 
>     if msvc := UseVsWhere( quiet, vswhere_args ):
> ```

`:=` operator is python 3.9+.
We should hold back just a little longer. Python 3.8 goes EOL in October.

Yes, our CI uses python 3.9, but that's because new ubuntu does not have python 3.8 and I didn't want to drag in `pyenv` to compile an old version.is\_accessible

**Review by dkaszews — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1753)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[`build.py` line 150 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1753#-O3wAD0XDn4RWnjapJnT:-O3wBVNQ8hnvdEZ8P5NP:bgmga30) ([raw file](https://github.com/ycm-core/ycmd/blob/3db0bfac2eb4a21dbbc960ec7f95c3b01db5aece/build.py#L150)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

This does not seem to be needed here.
</blockquote></details>

It is used below for the registry loop. I moved it to file scope to remove duplication.
___
*[`build.py` line 162 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1753#-O3w9dTQ2F-FOqInfkdm:-O3wBub9-ZcgAkSWUgNA:b1xjh20) ([raw file](https://github.com/ycm-core/ycmd/blob/3db0bfac2eb4a21dbbc960ec7f95c3b01db5aece/build.py#L162)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

`:=` operator is python 3.9+.
We should hold back just a little longer. Python 3.8 goes EOL in October.

Yes, our CI uses python 3.9, but that's because new ubuntu does not have python 3.8 and I didn't want to drag in `pyenv` to compile an old version.is\_accessible
</blockquote></details>

Walrus was introduced in 3.8: https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions

**Review by bstaletic — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1753)* status: 0 of 2 LGTMs obtained (waiting on @dkaszews)

___
*[`build.py` line 150 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1753#-O3wAD0XDn4RWnjapJnT:-O3wCfWW1b425B9bq-DE:bvmpus7) ([raw file](https://github.com/ycm-core/ycmd/blob/3db0bfac2eb4a21dbbc960ec7f95c3b01db5aece/build.py#L150)):*
<details><summary><i>Previously, dkaszews (Dominik Kaszewski) wrote…</i></summary><blockquote>

It is used below for the registry loop. I moved it to file scope to remove duplication.
</blockquote></details>

That was outside the diff. Yeah, let's move it to the file scope, with a better name for context.

I'm just not seeing the second push in the diff.
___
*[`build.py` line 162 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1753#-O3w9dTQ2F-FOqInfkdm:-O3wC_JN4CfSgBARH1Ew:bt4h3ia) ([raw file](https://github.com/ycm-core/ycmd/blob/3db0bfac2eb4a21dbbc960ec7f95c3b01db5aece/build.py#L162)):*
<details><summary><i>Previously, dkaszews (Dominik Kaszewski) wrote…</i></summary><blockquote>

Walrus was introduced in 3.8: https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions
</blockquote></details>

So it is. Nevermind.

**Review by dkaszews — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1753)* status: 0 of 2 LGTMs obtained (waiting on @bstaletic)

___
*[`build.py` line 150 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1753#-O3wAD0XDn4RWnjapJnT:-O3wDMRW9gjEvom9Xh6g:blhhsj0) ([raw file](https://github.com/ycm-core/ycmd/blob/3db0bfac2eb4a21dbbc960ec7f95c3b01db5aece/build.py#L150)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

That was outside the diff. Yeah, let's move it to the file scope, with a better name for context.

I'm just not seeing the second push in the diff.
</blockquote></details>

Pushed now, was having some connection issues

**Review by bstaletic — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1753#-:-O3wE4D-54_aDR3vQTas:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @dkaszews)

**Comment by bstaletic** [comment]
Turns out i did not merge the CI pull request when I thought I had.
*Now* that #1746 has been merged, please rebase again.

**Comment by dkaszews** [comment]
Rebased again

**Review by bstaletic — APPROVED** [review]
:lgtm_strong: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1753#-:-O3xDBuC4J59zLFhoQeo:b-uwkowd)* status: 1 of 2 LGTMs obtained (waiting on @dkaszews)

**Pull request merged**
