### PR TITLE
[READY] Update jdt.ls to 0.67.0

### PR DESCRIPTION
**Pull request by puremourning**
not much to say about it. just the latest version.

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1524)

### CODE REVIEW

**Comment by bstaletic** [comment]
LGTM, assuming the tests pass. I've noticed the reformatted `.project` files with earlier versions and have avoided committing those changes.

**Comment by puremourning** [comment]
>  I've noticed the reformatted .project files with earlier versions and have avoided committing those changes.

(yeah it was starting to bug me, so included in this patch )

**Comment by puremourning** [comment]
I think there might be a jdt.ls option to tell it not to rewrite the project files, but meh I don't really mind either way.

**Review by puremourning — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1524#-:-MQXvjRTDjI6PcdBVQ5U:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @puremourning)

**Comment by bstaletic** [comment]
Looks like tests are green, MSVC is just slow. :lgtm_strong:

**Pull request merged**
