### PR TITLE
Support MSVC 17 (Visual Studio 2022)

### PR DESCRIPTION
**Pull request by mispencer**
Now that VS 2022 is released, ycmd should be buildable on Windows without requiring installing old versions of the build tools.

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1608)

### CODE REVIEW

**Review by bstaletic — APPROVED** [review]
Thanks for the PR. :lgtm:, with a few non-blocking comments.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1608#-:-Mo_Ghm9AO7yramFXaGc:b3tcnj8)* status: 1 of 2 LGTMs obtained (waiting on @mispencer)

___
*[build.py, line 381 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1608#-Mo_EogJ-fzbXIppMAAV:-Mo_EogJ-fzbXIppMAAW:b-698ult) ([raw file](https://github.com/ycm-core/ycmd/blob/927a84b1eccd50154722c0b6507fec7a91a65878/build.py#L381)):*
> ```Python
>       return 'Visual Studio 16'
>     if args.msvc == 17:
>       return 'Visual Studio 17 2022'
> ```

I just love that we can't just do `return f'Visual Studio {args.msvc}'`.
___
*[build.py, line 409 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1608#-Mo_F0XBEjrfb0fuF5FQ:-Mo_F0XBEjrfb0fuF5FR:b-1cxz1d) ([raw file](https://github.com/ycm-core/ycmd/blob/927a84b1eccd50154722c0b6507fec7a91a65878/build.py#L409)):*
> ```Python
>                        'from llvm.org. NOT RECOMMENDED OR SUPPORTED!' )
>   parser.add_argument( '--msvc', type = int, choices = [ 15, 16, 17 ],
>                        default = 16, help = 'Choose the Microsoft Visual '
> ```

Should we change the default too?
___
*[run_tests.py, line 136 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1608#-Mo_FDDg5SKggHApdydv:-Mo_FDDg5SKggHApdydw:b2o7re1) ([raw file](https://github.com/ycm-core/ycmd/blob/927a84b1eccd50154722c0b6507fec7a91a65878/run_tests.py#L136)):*
> ```Python
>                        help = 'Do not build ycmd before testing.' )
>   parser.add_argument( '--msvc', type = int, choices = [ 15, 16, 17 ],
>                        default = 16, help = 'Choose the Microsoft Visual '
> ```

Again, should we change the default?
___
*[.github/workflows/ci.yml, line 163 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1608#-Mo_G3xe4laq-L2Nz9Mb:-Mo_G3xe4laq-L2Nz9Mc:bw3qfo9) ([raw file](https://github.com/ycm-core/ycmd/blob/927a84b1eccd50154722c0b6507fec7a91a65878/.github/workflows/ci.yml#L163)):*
> ```YAML
>       uses: actions/setup-python@v2
>       with:
>         python-version: 3.9
> ```

Since we're already touching `ci.yml`, Windows jobs should be using latest python. That's 3.10 since recently.

@mispencer If you don't mind, change that too. Or I can in a different PR.

**Review by bstaletic — APPROVED** [review]
Thanks for the PR. :lgtm:, with a few non-blocking comments.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1608#-:-Mo_Ghm9AO7yramFXaGc:b3tcnj8)* status: 1 of 2 LGTMs obtained (waiting on @mispencer)

___
*[build.py, line 381 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1608#-Mo_EogJ-fzbXIppMAAV:-Mo_EogJ-fzbXIppMAAW:b-698ult) ([raw file](https://github.com/ycm-core/ycmd/blob/927a84b1eccd50154722c0b6507fec7a91a65878/build.py#L381)):*
> ```Python
>       return 'Visual Studio 16'
>     if args.msvc == 17:
>       return 'Visual Studio 17 2022'
> ```

I just love that we can't just do `return f'Visual Studio {args.msvc}'`.
___
*[build.py, line 409 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1608#-Mo_F0XBEjrfb0fuF5FQ:-Mo_F0XBEjrfb0fuF5FR:b-1cxz1d) ([raw file](https://github.com/ycm-core/ycmd/blob/927a84b1eccd50154722c0b6507fec7a91a65878/build.py#L409)):*
> ```Python
>                        'from llvm.org. NOT RECOMMENDED OR SUPPORTED!' )
>   parser.add_argument( '--msvc', type = int, choices = [ 15, 16, 17 ],
>                        default = 16, help = 'Choose the Microsoft Visual '
> ```

Should we change the default too?
___
*[run_tests.py, line 136 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1608#-Mo_FDDg5SKggHApdydv:-Mo_FDDg5SKggHApdydw:b2o7re1) ([raw file](https://github.com/ycm-core/ycmd/blob/927a84b1eccd50154722c0b6507fec7a91a65878/run_tests.py#L136)):*
> ```Python
>                        help = 'Do not build ycmd before testing.' )
>   parser.add_argument( '--msvc', type = int, choices = [ 15, 16, 17 ],
>                        default = 16, help = 'Choose the Microsoft Visual '
> ```

Again, should we change the default?
___
*[.github/workflows/ci.yml, line 163 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1608#-Mo_G3xe4laq-L2Nz9Mb:-Mo_G3xe4laq-L2Nz9Mc:bw3qfo9) ([raw file](https://github.com/ycm-core/ycmd/blob/927a84b1eccd50154722c0b6507fec7a91a65878/.github/workflows/ci.yml#L163)):*
> ```YAML
>       uses: actions/setup-python@v2
>       with:
>         python-version: 3.9
> ```

Since we're already touching `ci.yml`, Windows jobs should be using latest python. That's 3.10 since recently.

@mispencer If you don't mind, change that too. Or I can in a different PR.

**Review by mispencer — COMMENTED** [review]
Looks like the C# tests are failing in Window 2022. Likely because the new images has something different (a new default .NET version)?

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1608#-:-Mo_OfhM7KCKBkiDUtK7:b6ed7e0)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @bstaletic)

___
*[build.py, line 409 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1608#-Mo_F0XBEjrfb0fuF5FQ:-Mo_OEQg2jbh9KnGScd3:b-w8mish) ([raw file](https://github.com/ycm-core/ycmd/blob/927a84b1eccd50154722c0b6507fec7a91a65878/build.py#L409)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Should we change the default too?
</blockquote></details>

17 was officially released mere days ago. It is too soon to change the default.
___
*[run_tests.py, line 136 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1608#-Mo_FDDg5SKggHApdydv:-Mo_OYKDDzE4ZhtDyLrX:bqgt82z) ([raw file](https://github.com/ycm-core/ycmd/blob/927a84b1eccd50154722c0b6507fec7a91a65878/run_tests.py#L136)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Again, should we change the default?
</blockquote></details>

Probably not yet.
___
*[.github/workflows/ci.yml, line 163 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1608#-Mo_G3xe4laq-L2Nz9Mb:-Mo_Ocl-38TvNwGqh34B:b-k60tyz) ([raw file](https://github.com/ycm-core/ycmd/blob/927a84b1eccd50154722c0b6507fec7a91a65878/.github/workflows/ci.yml#L163)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Since we're already touching `ci.yml`, Windows jobs should be using latest python. That's 3.10 since recently.

@mispencer If you don't mind, change that too. Or I can in a different PR.
</blockquote></details>

I can update this.

**Review by bstaletic — CHANGES_REQUESTED** [review]
Wonderful... We were not able to update Omnisharp-Roslyn for a very long time due to test failures on newer versions. I'm assuming the tests pass on your machine?

@puremourning and I should look into why there are no logs on error. That's annoying.

@mispencer Maybe try with [tmate](https://github.com/marketplace/actions/debugging-with-tmate) to log into the CI machine.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1608#-:-Mo_Qgqt188eEW2ubALg:bq90b5g)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @bstaletic and @mispencer)

___
*[.github/workflows/ci.yml, line 132 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1608#-Mo_R1fl2M35jOweVkgn:-Mo_R1fl2M35jOweVkgo:b-rb6gsj) ([raw file](https://github.com/ycm-core/ycmd/blob/009ead8909819a8b8b8d720a7da3ce5a0fb693c4/.github/workflows/ci.yml#L132)):*
> ```YAML
>         msvc: [ 17 ]
>         exclude:
>           - runs-on: windows-2019
> ```

This line should be windows-2022. The idea is to exclude the 32bit benchmark run on Windows.

**Review by mispencer — COMMENTED** [review]
I was able to get more logs in CI by removing the `b` flag.
I am guessing this is the relevant error:
```
fail: OmniSharp.MSBuild.ProjectLoader[0]
      The reference assemblies for .NETFramework,Version=v4.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
```

It looks like the [window-2022 image doesn't have the 4.0 targeting pack installed anymore](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md). 4.0 is long past its end-of-life at this point, so the proper fix is likely to upgrade the .NET version of the C# test projects.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1608#-:-MocqtAhDRiR_IRv6fTC:b-nuwbji)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @bstaletic and @mispencer)

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1608)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @bstaletic and @mispencer)

___
*[-- commits, line 1 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1608#-MocsbmhECOYDnM5rFS1):*
can we squash the commits?
___
*[build.py, line 524 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1608#-MoctlHbBvVaDBGV6zdN:-MoctlHbBvVaDBGV6zdO:bsx7h71) ([raw file](https://github.com/ycm-core/ycmd/blob/f40e2a1e369d522b37a0ec7f4a4b02b1d13cc396/build.py#L524)):*
> ```Python
> 
>   # Set the architecture for the Visual Studio 16/17 generator.
>   is_1617 = args.msvc == 16 or args.msvc == 17
> ```

should we expect this to really be `args.msvc >= 16` ?
___
*[run_tests.py, line 12 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1608#-Moct-K5D3flhitKhZEh:-Moct-K5D3flhitKhZEi:b54o9xw) ([raw file](https://github.com/ycm-core/ycmd/blob/f40e2a1e369d522b37a0ec7f4a4b02b1d13cc396/run_tests.py#L12)):*
> ```Python
> import urllib.request
> 
> BASE_UNITTEST_ARGS = [ '-cv' ]
> ```

Unfortunately this change (or the removal of `--quiet`) makes the test output _extremely_ verbose. Many tests are written as if they can `print()` something and that is only visible if the test fails. If you look now, there's pages and pages of output. We had all sorts of problems diagnosing issues previously when the output was so verbose.

I realise that there are some bugs that are causing the retried tests to not print the failure message (and that's annoying) but I'd rather fix that medium/long term than regress to having extremely noisy output.

**Review by puremourning — COMMENTED** [review]
Thanks for the update!

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1608#-:-MoctqmUC8HjxBaiyqHF:b-vsu5ts)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @bstaletic and @mispencer)

**Review by bstaletic — COMMENTED** [review]
I'm not at all against retargetting the application. I also have no idea how. I don't see `4.0` mentioned anywhere in our solution files. Nor do I see anything with a `.config` extension.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1608#-:-MocxINMCmUbiCCq6nRq:bj7ny82)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @bstaletic, @mispencer, and @puremourning)

___
*[build.py, line 381 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1608#-Mo_EogJ-fzbXIppMAAV:-Mocw12f6irRnxWNMFa-:b69k2is) ([raw file](https://github.com/ycm-core/ycmd/blob/927a84b1eccd50154722c0b6507fec7a91a65878/build.py#L381)):*
> TBH it's baffling this is required at all. Like, can't cmake just work this out based on CC -v ?

CMake *does* detect the version of `cl.exe`. Yeah, don't ask.
___
*[build.py, line 524 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1608#-MoctlHbBvVaDBGV6zdN:-MocwI3jDlAHvz_MkJ74:b-8dvksb) ([raw file](https://github.com/ycm-core/ycmd/blob/f40e2a1e369d522b37a0ec7f4a4b02b1d13cc396/build.py#L524)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

should we expect this to really be `args.msvc >= 16` ?
</blockquote></details>

We should, I believe.
___
*[run_tests.py, line 12 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1608#-Moct-K5D3flhitKhZEh:-MoczxmbC2-rxt6dF4Fp:bkogxhh) ([raw file](https://github.com/ycm-core/ycmd/blob/f40e2a1e369d522b37a0ec7f4a4b02b1d13cc396/run_tests.py#L12)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Unfortunately this change (or the removal of `--quiet`) makes the test output _extremely_ verbose. Many tests are written as if they can `print()` something and that is only visible if the test fails. If you look now, there's pages and pages of output. We had all sorts of problems diagnosing issues previously when the output was so verbose.

I realise that there are some bugs that are causing the retried tests to not print the failure message (and that's annoying) but I'd rather fix that medium/long term than regress to having extremely noisy output.
</blockquote></details>

We can revert this after we figure out the C# test failures.

**Review by mispencer — COMMENTED** [review]
I have re-targeted all the C# test projects to 4.8.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1608#-:-ModCGvO3b1X_QkyZv1m:ba15cn1)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @bstaletic and @puremourning)

___
*[-- commits, line 1 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1608#-MocsbmhECOYDnM5rFS1):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

can we squash the commits?
</blockquote></details>

You want a single commit?
___
*[build.py, line 524 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1608#-MoctlHbBvVaDBGV6zdN:-ModCbBv3J-7cMVo_S0Y:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/f40e2a1e369d522b37a0ec7f4a4b02b1d13cc396/build.py#L524)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

We should, I believe.
</blockquote></details>

Done.
___
*[run_tests.py, line 12 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1608#-Moct-K5D3flhitKhZEh:-ModCgNd7VM8I0Gwqc_q:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/f40e2a1e369d522b37a0ec7f4a4b02b1d13cc396/run_tests.py#L12)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

We can revert this after we figure out the C# test failures.
</blockquote></details>

Done.
___
*[.github/workflows/ci.yml, line 163 at r1](https://reviewable.io/reviews/ycm-core/ycmd/1608#-Mo_G3xe4laq-L2Nz9Mb:-ModCiQg52wQNiG1QDFJ:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/927a84b1eccd50154722c0b6507fec7a91a65878/.github/workflows/ci.yml#L163)):*
<details><summary><i>Previously, mispencer wrote…</i></summary><blockquote>

I can update this.
</blockquote></details>

Done.
___
*[.github/workflows/ci.yml, line 132 at r2](https://reviewable.io/reviews/ycm-core/ycmd/1608#-Mo_R1fl2M35jOweVkgn:-ModChmg2DxQ6aJZ5ZM8:b-896fix) ([raw file](https://github.com/ycm-core/ycmd/blob/009ead8909819a8b8b8d720a7da3ce5a0fb693c4/.github/workflows/ci.yml#L132)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

This line should be windows-2022. The idea is to exclude the 32bit benchmark run on Windows.
</blockquote></details>

Done.

**Review by mispencer — COMMENTED** [review]
CI is passing now. The codecov changes are baffling to me.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1608#-:-ModNWfn4yg0Ap7xW7la:b-vzz13)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @bstaletic and @puremourning)

**Review by bstaletic — APPROVED** [review]
My guess is that the last build on master failed due to some flake, so master only has a partial report. Just ignore it.

> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1608#-:-Moemz6vAtMgyTnMbuhb:bd3awzr)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)

___
*[-- commits, line 1 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1608#-MocsbmhECOYDnM5rFS1):*
<details><summary><i>Previously, mispencer wrote…</i></summary><blockquote>

You want a single commit?
</blockquote></details>

Maybe two - MSVC related stuff and C# target related stuff.

**Review by mispencer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1608)* status: 0 of 2 LGTMs obtained (and 1 stale) (waiting on @bstaletic and @puremourning)

___
*[-- commits, line 1 at r3](https://reviewable.io/reviews/ycm-core/ycmd/1608#-MocsbmhECOYDnM5rFS1):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Maybe two - MSVC related stuff and C# target related stuff.
</blockquote></details>

Done.

**Review by bstaletic — APPROVED** [review]
Great! :lgtm_strong: 

I wonder if this retargetting will help us update the Omnisharp-Roslyn version we ship. I think I failed to update it ~5 times so far.

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1608#-:-MogitPn8ahrs_4kCfWK:b-99tef6)* status: 1 of 2 LGTMs obtained (waiting on @puremourning)

**Review by puremourning — APPROVED** [review]
:lgtm:

sweet! ta!

> Reviewed 2 of 5 files at r1, 10 of 11 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1608#-:-Mohd343A-m-d5a4wZWx:b-ouclu2)* status: :shipit: complete! 2 of 2 LGTMs obtained (waiting on @mispencer)

**Review by mispencer — COMMENTED** [review]
:lgtm:

I am guessing you will need to do something about codecov to get this merged?

FYI - I am planning to look into upgrading Omnisharp next.

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1608#-:-Moja6MtARx_-rmOHloI:b-msocem)* status: :shipit: complete! 3 of 2 LGTMs obtained (waiting on @mispencer)

**Comment by bstaletic** [comment]
@MergifyIO refresh

It's thinking MSVC builds failed.

**Review by bstaletic — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1608)* status: :shipit: complete! 3 of 2 LGTMs obtained (waiting on @mispencer)

*[a discussion](https://reviewable.io/reviews/ycm-core/ycmd/1608#-Moj8sBq5RzoaWodn1i-:-Moj8sBq5RzoaWodn1i0:bqks5mw) (no related file):*
Okay, mergify is right for once... We forgot to update its config as well. Here's the diff that needs to be applied:

```diff
diff --git a/.mergify.yml b/.mergify.yml
index c79bbde2..7c98af7f 100644
--- a/.mergify.yml
+++ b/.mergify.yml
@@ -12,8 +12,9 @@ pull_request_rules:
       - status-success=C++ Lint
       - status-success=Windows MSVC 15 x64 - test run
       - status-success=Windows MSVC 16 x64 - test run
-      - status-success=Windows MSVC 16 x86 - test run
-      - status-success=Windows MSVC 16 x64 - C++ Benchmark
+      - status-success=Windows MSVC 17 x64 - test run
+      - status-success=Windows MSVC 17 x86 - test run
+      - status-success=Windows MSVC 17 x64 - C++ Benchmark
       - status-success=code-review/reviewable
     actions:
       merge:
@@ -33,8 +34,9 @@ pull_request_rules:
       - status-success=C++ Lint
       - status-success=Windows MSVC 15 x64 - test run
       - status-success=Windows MSVC 16 x64 - test run
-      - status-success=Windows MSVC 16 x86 - test run
-      - status-success=Windows MSVC 16 x64 - C++ Benchmark
+      - status-success=Windows MSVC 17 x64 - test run
+      - status-success=Windows MSVC 17 x86 - test run
+      - status-success=Windows MSVC 17 x64 - C++ Benchmark

       - "#approved-reviews-by>=1"
       - "#changes-requested-reviews-by=0"
```

Then we'll still need a manual merge, because mergify refuses to merge PRs that touch its config.

---

**Review by mispencer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1608)* status: 1 of 2 LGTMs obtained (and 2 stale) (waiting on @bstaletic and @puremourning)

*[a discussion](https://reviewable.io/reviews/ycm-core/ycmd/1608#-Moj8sBq5RzoaWodn1i-:-MojIb569QDPEW4nhisa:b-896fix) (no related file):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Okay, mergify is right for once... We forgot to update its config as well. Here's the diff that needs to be applied:

```diff
diff --git a/.mergify.yml b/.mergify.yml
index c79bbde2..7c98af7f 100644
--- a/.mergify.yml
+++ b/.mergify.yml
@@ -12,8 +12,9 @@ pull_request_rules:
       - status-success=C++ Lint
       - status-success=Windows MSVC 15 x64 - test run
       - status-success=Windows MSVC 16 x64 - test run
-      - status-success=Windows MSVC 16 x86 - test run
-      - status-success=Windows MSVC 16 x64 - C++ Benchmark
+      - status-success=Windows MSVC 17 x64 - test run
+      - status-success=Windows MSVC 17 x86 - test run
+      - status-success=Windows MSVC 17 x64 - C++ Benchmark
       - status-success=code-review/reviewable
     actions:
       merge:
@@ -33,8 +34,9 @@ pull_request_rules:
       - status-success=C++ Lint
       - status-success=Windows MSVC 15 x64 - test run
       - status-success=Windows MSVC 16 x64 - test run
-      - status-success=Windows MSVC 16 x86 - test run
-      - status-success=Windows MSVC 16 x64 - C++ Benchmark
+      - status-success=Windows MSVC 17 x64 - test run
+      - status-success=Windows MSVC 17 x86 - test run
+      - status-success=Windows MSVC 17 x64 - C++ Benchmark

       - "#approved-reviews-by>=1"
       - "#changes-requested-reviews-by=0"
```

Then we'll still need a manual merge, because mergify refuses to merge PRs that touch its config.
</blockquote></details>

Done.

---

**Pull request merged**
