### PR TITLE
[READY] Call close() on urllib socket handles after use

### PR DESCRIPTION
**Pull request by bstaletic**
As discussed yesterday, this stops ycmd from leaking all those socket handles.

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1520)

### CODE REVIEW

**Review by puremourning — APPROVED** [review]
:lgtm:

I haven’t checked why the tests are red. 

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1520#-:-MPs6ytO-Y-4OIMLKwaY:bh2khch)* status: 1 of 2 LGTMs obtained

**Comment by bstaletic** [comment]
Flake8 errors. Fixed.

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1520#-:-MPsBmpc1KxQ7slY5l__:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @bstaletic)

**Review by bstaletic — COMMENTED** [review]
Okay, now flake8 errors have been fixed! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1520#-:-MPu63xC6BxbMjV83BrR:b-qodc0k)* status: 1 of 2 LGTMs obtained (and 1 stale) (waiting on @puremourning)

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1520#-:-MPu7hw_6ZhuzVWfMb6C:bnfp4nl)* status: :shipit: complete! 2 of 2 LGTMs obtained (waiting on @bstaletic)

**Review by bstaletic — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ycm-core/ycmd/1520#-:-MPuAhqNCAf6ru-ckM8v:bnfp4nl)* status: :shipit: complete! 2 of 2 LGTMs obtained (waiting on @bstaletic)

**Pull request merged**
